// Per-level class progression content (Part B). Feature names and the levels they are gained
// are verified against each class's d20pfsrd table; descriptions are paraphrased. Attached to
// ClassDef.features / .bonusFeats / .choices by a loop in classes.ts, so the data lives here
// rather than bloating the class stat blocks. Subsystem picks (rage powers, talents, mercies…)
// are ClassChoiceDef entries with a `levels` array; the engine emits one slot per granted level.

import type { LeveledFeatureDef, ClassChoiceDef } from './model';
import {
  BARBARIAN_RAGE_POWERS, ROGUE_TALENTS, ROGUE_ADVANCED_TALENTS, PALADIN_MERCIES, PALADIN_DIVINE_BOND,
  ALCHEMIST_DISCOVERIES, MAGUS_ARCANA, WITCH_HEXES,
  ARCANIST_EXPLOITS, SHIFTER_ASPECTS,
} from './subsystems';

const ROGUE_TALENTS_ALL = [...ROGUE_TALENTS, ...ROGUE_ADVANCED_TALENTS];

export interface ClassProgression {
  features: LeveledFeatureDef[];
  bonusFeats?: { levels: number[]; combatOnly?: boolean; label?: string };
  /** Fixed feats the class grants automatically (not player picks) — shown read-only in Feats. */
  grantedFeats?: { level: number; feat: string; note?: string }[];
  /** Per-level subsystem picks, merged after the class's level-1 choices. */
  choices?: ClassChoiceDef[];
}

const f = (level: number, id: string, name: string, desc: string, extra?: Partial<LeveledFeatureDef>): LeveledFeatureDef =>
  ({ level, id, name, desc, ...extra });

export const CLASS_PROGRESSION: Record<string, ClassProgression> = {
  // ---------------------------------------------------------------- Core martials
  barbarian: {
    features: [
      f(1, 'barb-rage', 'Rage', 'Rage 4 + Con-mod rounds/day (+2 per level after 1st): +4 morale to Str and Con, +2 morale on Will, −2 AC.'),
      f(1, 'barb-fast-movement', 'Fast Movement', '+10 ft to base land speed.'),
      f(2, 'barb-uncanny-dodge', 'Uncanny Dodge', 'Keep your Dex bonus to AC when flat-footed or caught off guard.'),
      f(3, 'barb-trap-sense', 'Trap Sense +1', '+1 to AC and Reflex saves vs traps; rises to +2/+3/+4/+5/+6 at 6th/9th/12th/15th/18th.'),
      f(5, 'barb-improved-uncanny-dodge', 'Improved Uncanny Dodge', 'Cannot be flanked except by a rogue at least 4 levels higher.'),
      f(7, 'barb-dr', 'Damage Reduction 1/—', 'DR 1/—, improving by 1 at 10th, 13th, 16th, and 19th.'),
      f(11, 'barb-greater-rage', 'Greater Rage', 'Rage bonuses rise to +6 Str/Con and +3 Will.'),
      f(14, 'barb-indomitable-will', 'Indomitable Will', '+4 vs enchantment spells while raging.'),
      f(17, 'barb-tireless-rage', 'Tireless Rage', 'No longer fatigued when your rage ends.'),
      f(20, 'barb-mighty-rage', 'Mighty Rage', 'Rage bonuses rise to +8 Str/Con and +4 Will.'),
    ],
    choices: [{ id: 'rage-power', label: 'Rage power', kind: 'list', count: 1, levels: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], options: BARBARIAN_RAGE_POWERS }],
  },
  fighter: {
    bonusFeats: { levels: [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20], combatOnly: true, label: 'Fighter bonus feat' },
    features: [
      f(1, 'fighter-bonus-feat', 'Bonus Feat', 'A bonus combat feat at 1st level and every even level.'),
      f(2, 'fighter-bravery', 'Bravery +1', '+1 on saves vs fear; +1 more at 6th, 10th, 14th, and 18th.'),
      f(3, 'fighter-armor-training', 'Armor Training 1', 'Reduce armor check penalty by 1 and raise max Dex by 1; improves at 7th, 11th, 15th.'),
      f(5, 'fighter-weapon-training', 'Weapon Training 1', '+1 attack/damage with a chosen weapon group; a new group and +1 to all prior groups at 9th, 13th, 17th.'),
      f(19, 'fighter-armor-mastery', 'Armor Mastery', 'DR 5/— whenever wearing armor or using a shield.'),
      f(20, 'fighter-weapon-mastery', 'Weapon Mastery', 'With a chosen weapon: always confirm crits, +1 crit multiplier, cannot be disarmed.'),
    ],
  },
  monk: {
    bonusFeats: { levels: [1, 2, 6, 10, 14, 18], label: 'Monk bonus feat' },
    grantedFeats: [
      { level: 1, feat: 'improved-unarmed-strike' },
      { level: 1, feat: 'stunning-fist' },
    ],
    features: [
      f(1, 'monk-flurry', 'Flurry of Blows', 'Extra attacks with unarmed strikes or monk weapons as a full attack.'),
      f(1, 'monk-unarmed', 'Unarmed Strike', 'Deal lethal 1d6 unarmed damage (scaling), always armed; gain Improved Unarmed Strike.'),
      f(1, 'monk-stunning-fist', 'Stunning Fist', 'Gain Stunning Fist as a bonus feat.'),
      f(2, 'monk-evasion', 'Evasion', 'No damage on a successful Reflex save vs area effects.'),
      f(3, 'monk-fast-movement', 'Fast Movement', '+10 ft speed while unarmored, rising to +60 ft by 20th.'),
      f(3, 'monk-maneuver-training', 'Maneuver Training', 'Use monk level as BAB for combat maneuvers.'),
      f(3, 'monk-still-mind', 'Still Mind', '+2 on saves vs enchantment.'),
      f(4, 'monk-ki-pool', 'Ki Pool', 'A pool of ki fuels extra attacks, speed, and defense; unarmed strikes count as magic.'),
      f(4, 'monk-slow-fall', 'Slow Fall', 'Treat falls near a wall as shorter; improves every 4 levels to any distance at 20th.'),
      f(5, 'monk-high-jump', 'High Jump', 'Add level to Acrobatics jumps; spend ki for a further boost.'),
      f(5, 'monk-purity-of-body', 'Purity of Body', 'Immune to all diseases, magical or mundane.'),
      f(7, 'monk-wholeness-of-body', 'Wholeness of Body', 'Spend ki to heal your own wounds.'),
      f(9, 'monk-improved-evasion', 'Improved Evasion', 'Half damage even on a failed Reflex save.'),
      f(11, 'monk-diamond-body', 'Diamond Body', 'Immune to poison.'),
      f(12, 'monk-abundant-step', 'Abundant Step', 'Spend ki to teleport a short distance (dimension door).'),
      f(13, 'monk-diamond-soul', 'Diamond Soul', 'Gain spell resistance equal to level + 10.'),
      f(15, 'monk-quivering-palm', 'Quivering Palm', 'Set up a lethal vibration in a struck foe, once per day.'),
      f(17, 'monk-timeless-body', 'Timeless Body', 'No longer take penalties for aging.'),
      f(17, 'monk-tongue', 'Tongue of the Sun and Moon', 'Speak with any living creature.'),
      f(19, 'monk-empty-body', 'Empty Body', 'Spend ki to become briefly ethereal.'),
      f(20, 'monk-perfect-self', 'Perfect Self', 'You become an outsider; DR 10/chaotic.'),
    ],
  },
  rogue: {
    features: [
      f(1, 'rogue-sneak-attack', 'Sneak Attack +1d6', 'Extra 1d6 vs flanked/flat-footed foes; +1d6 every odd level to +10d6 at 19th.'),
      f(1, 'rogue-trapfinding', 'Trapfinding', 'Add half level to find and disable traps, including magical ones.'),
      f(2, 'rogue-evasion', 'Evasion', 'No damage on a successful Reflex save vs area effects.'),
      f(3, 'rogue-trap-sense', 'Trap Sense +1', '+1 to AC and Reflex vs traps; rises every 3 levels to +6 at 18th.'),
      f(4, 'rogue-uncanny-dodge', 'Uncanny Dodge', 'Keep Dex bonus to AC when flat-footed or surprised.'),
      f(8, 'rogue-improved-uncanny-dodge', 'Improved Uncanny Dodge', 'Cannot be flanked except by a rogue 4+ levels higher.'),
      f(20, 'rogue-master-strike', 'Master Strike', 'A sneak attack can leave a foe asleep, paralyzed, or slain (Fort negates).'),
    ],
    choices: [
      { id: 'rogue-talent', label: 'Rogue talent', kind: 'list', count: 1, levels: [2, 4, 6, 8], options: ROGUE_TALENTS },
      { id: 'rogue-adv-talent', label: 'Rogue talent (advanced eligible)', kind: 'list', count: 1, levels: [10, 12, 14, 16, 18, 20], options: [...ROGUE_TALENTS, ...ROGUE_ADVANCED_TALENTS] },
    ],
  },
  ranger: {
    bonusFeats: { levels: [2, 6, 10, 14, 18], label: 'Combat style feat' },
    grantedFeats: [{ level: 3, feat: 'endurance' }],
    features: [
      f(1, 'ranger-favored-enemy', 'Favored Enemy', '+2 (scaling) attack/damage and skills vs one creature type; add another at 5th, 10th, 15th, 20th.'),
      f(1, 'ranger-track', 'Track', 'Add half level to Survival to follow tracks.'),
      f(1, 'ranger-wild-empathy', 'Wild Empathy', 'Influence animals as a Diplomacy check.'),
      f(3, 'ranger-endurance', 'Endurance', 'Gain Endurance as a bonus feat.'),
      f(3, 'ranger-favored-terrain', 'Favored Terrain', 'Initiative and skill bonuses in one terrain; add another at 8th, 13th, 18th.'),
      f(4, 'ranger-hunters-bond', "Hunter's Bond", 'Bond with an animal companion or grant allies favored-enemy bonuses.'),
      f(4, 'ranger-spells', 'Spellcasting', 'Begin casting divine ranger spells (caster level = ranger level − 3).'),
      f(7, 'ranger-woodland-stride', 'Woodland Stride', 'Move through undergrowth unhindered.'),
      f(8, 'ranger-swift-tracker', 'Swift Tracker', 'Track at full speed without penalty.'),
      f(9, 'ranger-evasion', 'Evasion', 'No damage on a successful Reflex save.'),
      f(11, 'ranger-quarry', 'Quarry', 'Designate a target for bonus attacks and guaranteed tracking.'),
      f(12, 'ranger-camouflage', 'Camouflage', 'Hide in favored terrain even without cover.'),
      f(16, 'ranger-improved-evasion', 'Improved Evasion', 'Half damage even on a failed Reflex save.'),
      f(17, 'ranger-hide-in-plain-sight', 'Hide in Plain Sight', 'Use Stealth in favored terrain while observed.'),
      f(19, 'ranger-improved-quarry', 'Improved Quarry', 'Quarry bonuses increase and re-designate as a free action.'),
      f(20, 'ranger-master-hunter', 'Master Hunter', 'Study and slay a favored enemy with a single strike (Fort negates).'),
    ],
  },
  paladin: {
    features: [
      f(1, 'paladin-aura', 'Aura of Good / Detect Evil', 'Project a strong aura of good; detect evil at will.'),
      f(1, 'paladin-smite', 'Smite Evil 1/day', 'Add Cha to attack and level to damage vs an evil foe; +1 use at 4th, 7th, and every 3 levels to 7/day at 19th.'),
      f(2, 'paladin-divine-grace', 'Divine Grace', 'Add your Cha modifier to all saving throws.'),
      f(2, 'paladin-lay-on-hands', 'Lay on Hands', 'Heal (or harm undead) by touch, ½ level + Cha-mod times per day.'),
      f(3, 'paladin-aura-courage', 'Aura of Courage', 'Immune to fear; allies within 10 ft gain +4 vs fear.'),
      f(3, 'paladin-divine-health', 'Divine Health', 'Immune to all diseases.'),
      f(4, 'paladin-channel', 'Channel Positive Energy', 'Spend two lay-on-hands uses to channel positive energy.'),
      f(4, 'paladin-spells', 'Spellcasting', 'Begin casting divine paladin spells (caster level = paladin level − 3).'),
      f(8, 'paladin-aura-resolve', 'Aura of Resolve', 'Immune to charm; allies gain +4 vs charm.'),
      f(11, 'paladin-aura-justice', 'Aura of Justice', 'Grant allies the use of your smite evil.'),
      f(14, 'paladin-aura-faith', 'Aura of Faith', "Your and nearby allies' weapons count as good-aligned."),
      f(17, 'paladin-aura-righteousness', 'Aura of Righteousness', 'DR 5/evil; allies gain +4 vs compulsion.'),
      f(20, 'paladin-holy-champion', 'Holy Champion', 'Smite is potent against evil outsiders and can banish them.'),
    ],
    choices: [
      { id: 'divine-bond', label: 'Divine bond', kind: 'list', count: 1, levels: [5], options: PALADIN_DIVINE_BOND },
      { id: 'mercy', label: 'Mercy', kind: 'list', count: 1, levels: [3, 6, 9, 12, 15, 18], options: PALADIN_MERCIES },
    ],
  },

  // ---------------------------------------------------------------- Core casters
  cleric: {
    features: [
      f(1, 'cleric-channel', 'Channel Energy 1d6', 'Channel positive or negative energy to heal or harm; +1d6 every odd level to 10d6 at 19th.'),
      f(1, 'cleric-domains', 'Domains', 'Two domains from your deity grant powers and bonus spells.'),
      f(1, 'cleric-orisons', 'Orisons', 'Cast 0-level divine spells at will.'),
      f(1, 'cleric-spontaneous', 'Spontaneous Casting', 'Convert prepared spells into cure or inflict spells.'),
    ],
  },
  druid: {
    features: [
      f(1, 'druid-nature-bond', 'Nature Bond', 'Choose an animal companion or a cleric domain.'),
      f(1, 'druid-nature-sense', 'Nature Sense', '+2 on Knowledge (nature) and Survival checks.',
        { effects: [{ target: 'skill:know-nature', type: 'untyped', value: 2, note: 'Nature Sense' }, { target: 'skill:survival', type: 'untyped', value: 2, note: 'Nature Sense' }] }),
      f(1, 'druid-wild-empathy', 'Wild Empathy', 'Influence animals as a Diplomacy check.'),
      f(1, 'druid-orisons', 'Orisons', 'Cast 0-level divine spells at will.'),
      f(2, 'druid-woodland-stride', 'Woodland Stride', 'Move through undergrowth unhindered.'),
      f(3, 'druid-trackless-step', 'Trackless Step', 'Leave no trail in natural surroundings.'),
      f(4, 'druid-resist-natures-lure', "Resist Nature's Lure", '+4 on saves vs the spell-like abilities of fey.'),
      f(4, 'druid-wild-shape', 'Wild Shape 1/day', 'Assume animal (later elemental/plant) forms; more uses and forms as you level, at will at 20th.'),
      f(9, 'druid-venom-immunity', 'Venom Immunity', 'Immune to all poisons.'),
      f(13, 'druid-thousand-faces', 'A Thousand Faces', 'Change your appearance at will (as alter self).'),
      f(15, 'druid-timeless-body', 'Timeless Body', 'No longer take penalties for aging.'),
    ],
  },
  wizard: {
    bonusFeats: { levels: [5, 10, 15, 20], label: 'Wizard bonus feat' },
    grantedFeats: [{ level: 1, feat: 'scribe-scroll' }],
    features: [
      f(1, 'wizard-arcane-bond', 'Arcane Bond', 'Bond with a familiar or an object to cast through.'),
      f(1, 'wizard-arcane-school', 'Arcane School', 'Specialize in a school (or universalist) for powers and bonus spells.'),
      f(1, 'wizard-cantrips', 'Cantrips', 'Cast 0-level arcane spells at will.'),
      f(1, 'wizard-scribe-scroll', 'Scribe Scroll', 'Gain Scribe Scroll as a bonus feat.'),
      f(5, 'wizard-bonus-feat', 'Bonus Feat', 'A bonus metamagic, item-creation, or arcane feat at 5th, 10th, 15th, 20th.'),
    ],
  },
  sorcerer: {
    features: [
      f(1, 'sorc-bloodline', 'Bloodline', 'Your heritage grants powers at 1st, 3rd, 9th, 15th, 20th and bonus spells.'),
      f(1, 'sorc-cantrips', 'Cantrips', 'Cast 0-level arcane spells at will.'),
      f(1, 'sorc-eschew', 'Eschew Materials', 'Cast without inexpensive material components.'),
      f(3, 'sorc-bloodline-spell', 'Bloodline Spell', 'Add a bloodline spell to your list at 3rd and every 2 levels after.'),
      f(7, 'sorc-bloodline-feat', 'Bloodline Feat', 'A bonus feat from your bloodline at 7th, 13th, 19th.'),
    ],
  },
  bard: {
    features: [
      f(1, 'bard-performance', 'Bardic Performance', 'Inspire courage and other performances a number of rounds/day.'),
      f(1, 'bard-knowledge', 'Bardic Knowledge', 'Add half level to all Knowledge checks and make them untrained.'),
      f(1, 'bard-cantrips', 'Cantrips', 'Cast 0-level bard spells at will.'),
      f(1, 'bard-countersong', 'Countersong / Distraction / Fascinate', 'Performances that counter sound, illusions, or transfix foes.'),
      f(2, 'bard-versatile-performance', 'Versatile Performance', 'Use a Perform skill in place of its associated skills.'),
      f(2, 'bard-well-versed', 'Well-Versed', '+4 on saves vs sonic and language-dependent effects.'),
      f(3, 'bard-inspire-competence', 'Inspire Competence', "Aid an ally's skill check with performance."),
      f(5, 'bard-lore-master', 'Lore Master', 'Take 10 (later 20) on any known Knowledge skill.'),
      f(6, 'bard-suggestion', 'Suggestion', 'Plant a suggestion in a fascinated creature.'),
      f(8, 'bard-dirge-of-doom', 'Dirge of Doom', 'Shake nearby enemies with a grim performance.'),
      f(9, 'bard-inspire-greatness', 'Inspire Greatness', 'Grant allies bonus Hit Dice and attack.'),
      f(12, 'bard-soothing-performance', 'Soothing Performance', 'Perform a mass cure serious wounds.'),
      f(14, 'bard-frightening-tune', 'Frightening Tune', 'Frighten foes who fail their save.'),
      f(15, 'bard-inspire-heroics', 'Inspire Heroics', 'Grant allies large morale bonuses to AC and saves.'),
      f(18, 'bard-mass-suggestion', 'Mass Suggestion', 'Suggestion to all fascinated creatures at once.'),
      f(20, 'bard-deadly-performance', 'Deadly Performance', 'A performance that can kill a single listener.'),
    ],
  },

  // ---------------------------------------------------------------- Base classes
  alchemist: {
    grantedFeats: [
      { level: 1, feat: 'brew-potion' },
      { level: 1, feat: 'throw-anything' },
    ],
    features: [
      f(1, 'alch-alchemy', 'Alchemy', 'Brew extracts (personal spell-in-a-bottle) and identify potions with a bonus.'),
      f(1, 'alch-bomb', 'Bomb 1d6', 'Throw splash bombs for 1d6 + Int, scaling +1d6 every odd level.'),
      f(1, 'alch-brew-potion', 'Brew Potion', 'Gain Brew Potion as a bonus feat.'),
      f(1, 'alch-mutagen', 'Mutagen', 'Brew a mutagen: a physical boost and natural armor at a mental cost.'),
      f(1, 'alch-throw-anything', 'Throw Anything', 'Gain Throw Anything and add Int to splash damage.'),
      f(2, 'alch-poison-resistance', 'Poison Resistance +2', '+2 vs poison, rising to +4/+6 at 5th/8th and immunity at 10th.'),
      f(2, 'alch-poison-use', 'Poison Use', 'Never risk poisoning yourself when applying poison.'),
      f(3, 'alch-swift-alchemy', 'Swift Alchemy', 'Create alchemical items in half the usual time.'),
      f(6, 'alch-swift-poisoning', 'Swift Poisoning', 'Apply poison to a weapon as a move action.'),
      f(14, 'alch-persistent-mutagen', 'Persistent Mutagen', 'Mutagen effects last twice as long.'),
      f(18, 'alch-instant-alchemy', 'Instant Alchemy', 'Create alchemical items and poisons almost instantly.'),
      f(20, 'alch-grand-discovery', 'Grand Discovery', 'A capstone discovery of exceptional power.'),
    ],
    choices: [{ id: 'discovery', label: 'Discovery', kind: 'list', count: 1, levels: [2, 4, 6, 8, 10, 12, 14, 16, 18], options: ALCHEMIST_DISCOVERIES }],
  },
  cavalier: {
    bonusFeats: { levels: [6, 12, 18], label: 'Cavalier bonus feat' },
    features: [
      f(1, 'cav-challenge', 'Challenge 1/day', 'Single out a foe for bonus damage while penalized against others; +1 use every 3 levels.'),
      f(1, 'cav-mount', 'Mount', 'A loyal, combat-trained mount grows with you.'),
      f(1, 'cav-order', 'Order', 'A knightly order grants edicts, skills, and abilities at 2nd, 8th, 15th.'),
      f(1, 'cav-tactician', 'Tactician', 'Grant nearby allies a teamwork feat for a time.'),
      f(3, 'cav-charge', "Cavalier's Charge", '+4 to hit on a charge with no AC penalty.'),
      f(4, 'cav-expert-trainer', 'Expert Trainer', 'Bonus to Handle Animal and to train your mount.'),
      f(5, 'cav-banner', 'Banner', 'A raised banner steadies allies vs fear and aids charges.'),
      f(9, 'cav-greater-tactician', 'Greater Tactician', 'Grant a teamwork feat to more allies.'),
      f(11, 'cav-mighty-charge', 'Mighty Charge', 'Double threat range and a free maneuver on a charge.'),
      f(12, 'cav-demanding-challenge', 'Demanding Challenge', 'A challenged foe is penalized to AC against everyone else.'),
      f(14, 'cav-greater-banner', 'Greater Banner', 'The banner rallies allies and boosts morale saves.'),
      f(17, 'cav-master-tactician', 'Master Tactician', 'Grant teamwork feats more often and to more allies.'),
      f(20, 'cav-supreme-charge', 'Supreme Charge', 'Charges can knock foes prone and stagger them.'),
    ],
  },
  gunslinger: {
    bonusFeats: { levels: [4, 8, 12, 16, 20], label: 'Gunslinger bonus feat' },
    grantedFeats: [{ level: 1, feat: 'gunsmithing', note: 'Gunsmith: comes with a battered firearm of your choice.' }],
    features: [
      f(1, 'gun-deeds-1', "Deeds: Deadeye, Gunslinger's Dodge, Quick Clear", 'Spend grit on daring feats.'),
      f(3, 'gun-deeds-3', 'Deeds: Gunslinger Initiative, Pistol-Whip, Utility Shot', 'New deeds unlock.'),
      f(7, 'gun-deeds-7', 'Deeds: Dead Shot, Startling Shot, Targeting', 'New deeds unlock.'),
      f(11, 'gun-deeds-11', 'Deeds: Bleeding Wound, Expert Loading, Lightning Reload', 'New deeds unlock.'),
      f(15, 'gun-deeds-15', "Deeds: Menacing Shot, Slinger's Reload", 'New deeds unlock.'),
      f(19, 'gun-deeds-19', "Deeds: Cheat Death, Death's Shot, Stunning Shot", 'New deeds unlock.'),
      f(1, 'gun-grit', 'Grit', 'A Wis-based pool, refreshed by crits and killing blows, that powers deeds.'),
      f(1, 'gun-gunsmith', 'Gunsmith', 'Gain a battered firearm and Gunsmithing to build and repair guns.'),
      f(2, 'gun-nimble', 'Nimble +1', 'Dodge bonus to AC in light/no armor, +1 every 4 levels to +5.'),
      f(5, 'gun-gun-training', 'Gun Training 1', 'Add Dex to firearm damage with a chosen group; new groups at 9th, 13th, 17th.'),
      f(20, 'gun-true-grit', 'True Grit', 'Two chosen deeds become dramatically more potent.'),
    ],
  },
  inquisitor: {
    bonusFeats: { levels: [3, 6, 9, 12, 15, 18], label: 'Teamwork feat' },
    features: [
      f(1, 'inq-domain', 'Domain', 'A single cleric domain or inquisition granting a power.'),
      f(1, 'inq-judgment', 'Judgment 1/day', 'Enter a combat judgment for scaling bonuses; +1 use at 4/7/10/13/16/19.'),
      f(1, 'inq-monster-lore', 'Monster Lore', 'Add Wis to Knowledge checks to identify creatures.'),
      f(1, 'inq-orisons', 'Orisons', 'Cast 0-level divine spells at will.'),
      f(1, 'inq-stern-gaze', 'Stern Gaze', '+½ level on Intimidate and Sense Motive.'),
      f(2, 'inq-cunning-initiative', 'Cunning Initiative', 'Add Wis to initiative checks.'),
      f(2, 'inq-detect-alignment', 'Detect Alignment', 'Detect any single alignment at will.'),
      f(2, 'inq-track', 'Track', 'Add half level to Survival to follow tracks.'),
      f(3, 'inq-solo-tactics', 'Solo Tactics', 'Treat allies as sharing your teamwork feats.'),
      f(5, 'inq-bane', 'Bane', 'Empower a weapon against a chosen creature type.'),
      f(5, 'inq-discern-lies', 'Discern Lies', 'Detect lies as the spell.'),
      f(8, 'inq-second-judgment', 'Second Judgment', 'Use two judgments simultaneously.'),
      f(11, 'inq-stalwart', 'Stalwart', 'Successful Fort/Will saves negate effects entirely.'),
      f(12, 'inq-greater-bane', 'Greater Bane', 'Bane deals extra damage.'),
      f(14, 'inq-exploit-weakness', 'Exploit Weakness', 'Ignore some DR and pierce resistances.'),
      f(16, 'inq-third-judgment', 'Third Judgment', 'Use three judgments simultaneously.'),
      f(17, 'inq-slayer', 'Slayer', 'One chosen judgment is always maximized.'),
      f(20, 'inq-true-judgment', 'True Judgment', 'A judgment can slay a foe outright (Fort negates).'),
    ],
  },
  magus: {
    bonusFeats: { levels: [5, 11, 17], label: 'Magus bonus feat' },
    features: [
      f(1, 'magus-arcane-pool', 'Arcane Pool', 'An Int-based pool that enhances your weapon and fuels arcana.'),
      f(1, 'magus-cantrips', 'Cantrips', 'Cast 0-level magus spells at will.'),
      f(1, 'magus-spell-combat', 'Spell Combat', 'Cast a spell and make weapon attacks in the same round.'),
      f(2, 'magus-spellstrike', 'Spellstrike', 'Deliver a touch spell through a melee weapon strike.'),
      f(4, 'magus-spell-recall', 'Spell Recall', 'Spend arcane pool to recall an already-cast spell.'),
      f(7, 'magus-knowledge-pool', 'Knowledge Pool', 'Prepare spells from a stored library on the fly.'),
      f(7, 'magus-medium-armor', 'Medium Armor', 'Cast magus spells in medium armor without failure.'),
      f(8, 'magus-improved-spell-combat', 'Improved Spell Combat', '+2 concentration during spell combat.'),
      f(10, 'magus-fighter-training', 'Fighter Training', 'Count half magus level as fighter levels for feats.'),
      f(11, 'magus-improved-spell-recall', 'Improved Spell Recall', 'Recall spells more cheaply.'),
      f(13, 'magus-heavy-armor', 'Heavy Armor', 'Cast magus spells in heavy armor without failure.'),
      f(14, 'magus-greater-spell-combat', 'Greater Spell Combat', 'No attack penalty and +4 concentration in spell combat.'),
      f(16, 'magus-counterstrike', 'Counterstrike', 'Strike a foe who casts defensively beside you.'),
      f(19, 'magus-greater-spell-access', 'Greater Spell Access', 'Add several wizard spells to your list.'),
      f(20, 'magus-true-magus', 'True Magus', 'Arcane pool abilities become far more potent.'),
    ],
    choices: [{ id: 'magus-arcana', label: 'Magus arcana', kind: 'list', count: 1, levels: [3, 6, 9, 12, 15, 18], options: MAGUS_ARCANA }],
  },
  oracle: {
    features: [
      f(1, 'oracle-mystery', 'Mystery', 'A divine mystery grants bonus spells, class skills, and revelations.'),
      f(1, 'oracle-curse', "Oracle's Curse", 'A hindrance that grants compensating powers as you level.'),
      f(1, 'oracle-orisons', 'Orisons', 'Cast 0-level divine spells at will.'),
      f(1, 'oracle-revelation', 'Revelation', 'A power from your mystery; gain more at 3rd, 7th, 11th, 15th, 19th.'),
      f(20, 'oracle-final-revelation', 'Final Revelation', 'A capstone power unique to your mystery.'),
    ],
    // mystery + curse are defined inline on the class; here we add only the per-level revelation
    // pick, whose options are source-dependent on the chosen mystery (see classChoiceOptions).
    choices: [
      { id: 'revelation', label: 'Revelation', kind: 'oracle-revelation', count: 1, levels: [1, 3, 7, 11, 15, 19] },
    ],
  },
  summoner: {
    features: [
      f(1, 'summ-eidolon', 'Eidolon', 'A customizable outsider companion shaped by an evolution pool.'),
      f(1, 'summ-life-link', 'Life Link', 'Share wounds with your eidolon to keep it from being banished.'),
      f(1, 'summ-summon-monster', 'Summon Monster I', 'Summon monsters as a standard action; the spell level rises every 2 levels to IX at 17th.'),
      f(1, 'summ-cantrips', 'Cantrips', 'Cast 0-level summoner spells at will.'),
      f(2, 'summ-bond-senses', 'Bond Senses', 'Perceive through your eidolon\'s senses.'),
      f(4, 'summ-shield-ally', 'Shield Ally', 'Bonus to AC and saves while near your eidolon.'),
      f(6, 'summ-makers-call', "Maker's Call", 'Teleport your eidolon to your side.'),
      f(8, 'summ-transposition', 'Transposition', "Swap places with your eidolon via Maker's Call."),
      f(10, 'summ-aspect', 'Aspect', 'Give up evolution points to gain evolutions yourself.'),
      f(12, 'summ-greater-shield-ally', 'Greater Shield Ally', 'The shield-ally bonus grows and reaches nearby allies.'),
      f(14, 'summ-life-bond', 'Life Bond', 'Your eidolon\'s life keeps you from dying.'),
      f(16, 'summ-merge-forms', 'Merge Forms', 'Meld into your eidolon to weather danger.'),
      f(18, 'summ-greater-aspect', 'Greater Aspect', 'Draw a larger share of your eidolon\'s evolutions.'),
      f(19, 'summ-gate', 'Gate', 'Cast gate to call powerful outsiders.'),
      f(20, 'summ-twin-eidolon', 'Twin Eidolon', 'Take your eidolon\'s form for a time.'),
    ],
  },
  witch: {
    features: [
      f(1, 'witch-hex-feature', 'Hex', 'Curses and blessings drawn from your patron; gain more at each even level.'),
      f(1, 'witch-patron-spells', 'Patron Spells', 'Your patron adds spells to your list as you level.'),
      f(1, 'witch-cantrips', 'Cantrips', 'Cast 0-level witch spells at will.'),
      f(1, 'witch-familiar', "Witch's Familiar", 'A familiar stores your spells; losing it costs you your magic until recovered.'),
      f(10, 'witch-major-hex', 'Major Hex', 'Unlock more powerful major hexes.'),
      f(18, 'witch-grand-hex', 'Grand Hex', 'Unlock the most powerful grand hexes.'),
    ],
    // patron + the level-1 hex are defined inline on the class; here we add the recurring hexes
    // gained at 2nd and every even level after (same `hex` series → uniqueness enforced).
    choices: [
      { id: 'hex', label: 'Hex', kind: 'list', count: 1, levels: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], options: WITCH_HEXES },
    ],
  },
  warpriest: {
    bonusFeats: { levels: [3, 6, 9, 12, 15, 18], label: 'Warpriest bonus feat' },
    grantedFeats: [{ level: 1, feat: 'weapon-focus', note: "deity's favored weapon" }],
    features: [
      f(1, 'wp-aura', 'Aura', "Project your deity's alignment aura."),
      f(1, 'wp-blessings', 'Blessings', 'Two minor blessings from your deity\'s domains; major versions at 10th.'),
      f(1, 'wp-focus-weapon', 'Focus Weapon', "Gain Weapon Focus with your deity's favored weapon."),
      f(1, 'wp-sacred-weapon', 'Sacred Weapon', 'Empower your weapon with scaling damage dice and, later, alignment and enhancement.'),
      f(2, 'wp-fervor', 'Fervor 1d6', 'Heal or cast a swift buff on yourself; the pool grows every 3 levels.'),
      f(4, 'wp-channel', 'Channel Energy', 'Channel positive or negative energy like a cleric.'),
      f(7, 'wp-sacred-armor', 'Sacred Armor', 'Empower your armor with a scaling enhancement bonus.'),
      f(20, 'wp-aspect-of-war', 'Aspect of War', 'A capstone battle-blessing of your deity.'),
    ],
  },
  arcanist: {
    features: [
      f(1, 'arc-reservoir', 'Arcane Reservoir', 'A pool of arcane energy that fuels exploits and boosts spells.'),
      f(1, 'arc-exploit', 'Arcanist Exploit', 'Flexible magical tricks; gain more as you level, and greater exploits from 11th.'),
      f(1, 'arc-cantrips', 'Cantrips', 'Cast 0-level arcanist spells at will.'),
      f(1, 'arc-consume-spells', 'Consume Spells', 'Burn a prepared spell slot to refill the reservoir.'),
      f(20, 'arc-magical-supremacy', 'Magical Supremacy', 'Cast your best spells with dramatically improved effect.'),
    ],
    choices: [{ id: 'exploit', label: 'Arcanist exploit', kind: 'list', count: 1, levels: [3, 5, 7, 9, 11, 13, 15, 17, 19], options: ARCANIST_EXPLOITS }],
  },
  bloodrager: {
    bonusFeats: { levels: [6, 9, 12, 15, 18], label: 'Bloodline feat' },
    features: [
      f(1, 'br-bloodline', 'Bloodline', 'A bloodline grants powers at 1st, 4th, 8th, 12th, 16th, 20th and bonus spells.'),
      f(1, 'br-bloodrage', 'Bloodrage', 'Rage rounds/day (as a barbarian) that also let you cast while raging.'),
      f(1, 'br-fast-movement', 'Fast Movement', '+10 ft to base land speed.'),
      f(2, 'br-uncanny-dodge', 'Uncanny Dodge', 'Keep Dex to AC when flat-footed or surprised.'),
      f(3, 'br-blood-sanctuary', 'Blood Sanctuary', 'Bonus on saves vs your own and allies\' spells.'),
      f(4, 'br-blood-casting', 'Blood Casting / Eschew Materials', 'Cast spells while bloodraging; ignore cheap components.'),
      f(5, 'br-improved-uncanny-dodge', 'Improved Uncanny Dodge', 'Cannot be flanked except by a rogue 4+ levels higher.'),
      f(7, 'br-dr', 'Damage Reduction 1/—', 'DR 1/—, improving at 10th, 13th, 16th, 19th.'),
      f(11, 'br-greater-bloodrage', 'Greater Bloodrage', 'Bloodrage bonuses increase.'),
      f(14, 'br-indomitable-will', 'Indomitable Will', '+4 vs enchantment while bloodraging.'),
      f(17, 'br-tireless-bloodrage', 'Tireless Bloodrage', 'No longer fatigued after bloodraging.'),
      f(20, 'br-mighty-bloodrage', 'Mighty Bloodrage', 'Bloodrage bonuses reach their peak.'),
    ],
  },
  brawler: {
    bonusFeats: { levels: [2, 5, 8, 11, 14, 17, 20], combatOnly: true, label: 'Brawler bonus feat' },
    features: [
      f(1, 'brawl-cunning', "Brawler's Cunning", 'Treat Int as 13 for combat-feat prerequisites.'),
      f(1, 'brawl-martial-flexibility', 'Martial Flexibility', 'Gain combat feats temporarily as a move action; faster at higher levels.'),
      f(1, 'brawl-martial-training', 'Martial Training', 'Count brawler level as fighter and monk levels for feats and effects.'),
      f(1, 'brawl-unarmed', 'Unarmed Strike', 'Deal scaling lethal unarmed damage; gain Improved Unarmed Strike.'),
      f(2, 'brawl-flurry', "Brawler's Flurry", 'Flurry with unarmed strikes and close/monk weapons as two-weapon fighting.'),
      f(3, 'brawl-maneuver-training', 'Maneuver Training', 'Bonus to CMB with chosen maneuvers; another every 4 levels.'),
      f(4, 'brawl-ac-bonus', 'AC Bonus', 'Dodge bonus to AC in light/no armor; +1 every 5 levels.'),
      f(4, 'brawl-knockout', 'Knockout', 'Once/day (more later), a hit can knock a foe unconscious.'),
      f(5, 'brawl-strike', "Brawler's Strike", 'Unarmed strikes bypass DR/magic, then more materials as you level.'),
      f(5, 'brawl-close-weapon-mastery', 'Close Weapon Mastery', 'Close-group weapons use your (higher) unarmed damage.'),
      f(16, 'brawl-awesome-blow', 'Awesome Blow', 'Gain Awesome Blow against foes your size or smaller.'),
      f(20, 'brawl-improved-awesome-blow', 'Improved Awesome Blow', 'Awesome Blow works on larger foes and improves.'),
    ],
  },

  // ---------------------------------------------------------------- Hybrid classes
  slayer: {
    features: [
      f(1, 'slay-studied-target', 'Studied Target', 'Study a foe to gain scaling bonuses to hit, damage, and skills against it; another at 5th, 10th, 15th, 20th.'),
      f(1, 'slay-track', 'Track', 'Add half level to Survival to follow tracks.'),
      f(3, 'slay-sneak-attack', 'Sneak Attack +1d6', 'Extra 1d6 vs flanked/flat-footed foes; +1d6 at 6th, 9th, 12th, 15th, 18th.'),
      f(7, 'slay-stalker', 'Stalker', 'Studied target also boosts Perception, Sense Motive, and Stealth.'),
      f(11, 'slay-swift-tracker', 'Swift Tracker', 'Track at full speed without penalty.'),
      f(13, 'slay-advance', "Slayer's Advance", 'Once/day (twice at 17th), move your speed as a swift action.'),
      f(14, 'slay-quarry', 'Quarry', 'Designate a studied target for guaranteed tracking and bonus attacks.'),
      f(19, 'slay-improved-quarry', 'Improved Quarry', 'Quarry bonuses increase and re-designate as a free action.'),
      f(20, 'slay-master', 'Master Slayer', 'A studied strike can paralyze or kill (Fort negates).'),
    ],
    choices: [
      { id: 'slayer-talent', label: 'Slayer talent', kind: 'list', count: 1, levels: [2, 4, 6, 8], options: ROGUE_TALENTS },
      { id: 'slayer-adv-talent', label: 'Slayer talent (advanced eligible)', kind: 'list', count: 1, levels: [10, 12, 14, 16, 18, 20], options: ROGUE_TALENTS_ALL },
    ],
  },
  swashbuckler: {
    bonusFeats: { levels: [4, 8, 12, 16, 20], combatOnly: true, label: 'Swashbuckler bonus feat' },
    features: [
      f(1, 'swb-panache', 'Panache', 'A Cha-based pool, refreshed by crits and killing blows with light blades, that fuels deeds.'),
      f(1, 'swb-deeds', 'Deeds', 'Spend panache on flashy feats; more deeds at 3rd, 7th, 11th, 15th, 19th.'),
      f(1, 'swb-finesse', 'Swashbuckler Finesse', 'Weapon Finesse for free with light and one-handed piercing weapons.'),
      f(2, 'swb-charmed-life', 'Charmed Life', 'Add Cha to a save as an immediate action a few times per day.'),
      f(3, 'swb-nimble', 'Nimble +1', 'Dodge bonus to AC in light/no armor; +1 every 4 levels to +5.'),
      f(5, 'swb-weapon-training', 'Swashbuckler Weapon Training +1', '+1 attack/damage with light blades; +1 every 4 levels.'),
      f(20, 'swb-weapon-mastery', 'Swashbuckler Weapon Mastery', 'Crits with light blades auto-confirm and bypass DR.'),
    ],
  },
  investigator: {
    features: [
      f(1, 'inv-alchemy', 'Alchemy', 'Brew extracts and identify potions like an alchemist.'),
      f(1, 'inv-inspiration', 'Inspiration', 'A pool of dice to add to skill checks (later attacks and saves).'),
      f(1, 'inv-trapfinding', 'Trapfinding', 'Add half level to find and disable traps, including magical ones.'),
      f(2, 'inv-poison-lore', 'Poison Lore / Resistance', 'Study poisons; +2 vs poison rising to immunity at 11th.'),
      f(3, 'inv-keen-recollection', 'Keen Recollection', 'Make all Knowledge checks untrained.'),
      f(3, 'inv-trap-sense', 'Trap Sense +1', '+1 to AC and Reflex vs traps; rises every 3 levels.'),
      f(4, 'inv-studied-combat', 'Studied Combat', 'Study a foe for a bonus to hit and to set up a studied strike.'),
      f(4, 'inv-studied-strike', 'Studied Strike +1d6', 'Deal bonus damage against your studied foe; scales to +9d6 at 20th.'),
      f(4, 'inv-swift-alchemy', 'Swift Alchemy', 'Create alchemical items in half the time.'),
      f(20, 'inv-true-inspiration', 'True Inspiration', 'Spend inspiration on nearly any d20 roll and empower extracts.'),
    ],
    choices: [{ id: 'investigator-talent', label: 'Investigator talent', kind: 'list', count: 1, levels: [3, 5, 7, 9, 11, 13, 15, 17, 19], options: ROGUE_TALENTS }],
  },
  hunter: {
    bonusFeats: { levels: [3, 6, 9, 12, 15, 18], label: 'Teamwork feat' },
    features: [
      f(1, 'hunter-animal-companion', 'Animal Companion', 'A loyal companion that advances at your level.'),
      f(1, 'hunter-animal-focus', 'Animal Focus', 'Take on an animal aspect for a bonus; a second focus at 8th.'),
      f(1, 'hunter-nature-training', 'Nature Training', 'Count as a druid and ranger for feats and effects.'),
      f(1, 'hunter-wild-empathy', 'Wild Empathy', 'Influence animals as a Diplomacy check.'),
      f(1, 'hunter-orisons', 'Orisons', 'Cast 0-level divine spells at will.'),
      f(2, 'hunter-precise-companion', 'Precise Companion', 'Gain a teamwork feat you share with your companion.'),
      f(3, 'hunter-tactics', 'Hunter Tactics', 'Grant your teamwork feats to your companion automatically.'),
      f(5, 'hunter-woodland-stride', 'Woodland Stride', 'Move through undergrowth unhindered.'),
      f(8, 'hunter-swift-tracker', 'Swift Tracker', 'Track at full speed.'),
      f(11, 'hunter-speak-with-master', 'Speak with Master', 'Converse with your companion.'),
      f(17, 'hunter-one-with-the-wild', 'One with the Wild', 'Gain all animal foci at once.'),
      f(20, 'hunter-master-hunter', 'Master Hunter', 'Deliver a devastating attack against a studied foe.'),
    ],
  },
  shaman: {
    features: [
      f(1, 'shaman-spirit-feature', 'Spirit', 'A spirit grants spells, a hex, and abilities at 1st, 8th, 16th, 20th.'),
      f(1, 'shaman-spirit-animal', 'Spirit Animal', 'A familiar-like companion that stores your spells.'),
      f(1, 'shaman-orisons', 'Orisons', 'Cast 0-level divine spells at will.'),
      f(4, 'shaman-wandering-spirit', 'Wandering Spirit', 'Bond with a temporary second spirit each day.'),
      f(6, 'shaman-wandering-hex', 'Wandering Hex', 'Borrow a hex from either spirit each day.'),
      f(8, 'shaman-greater-spirit', 'Greater Spirit Ability', 'Unlock a stronger ability from your spirit.'),
      f(16, 'shaman-true-spirit', 'True Spirit Ability', 'Unlock your spirit\'s ultimate ability.'),
      f(20, 'shaman-manifestation', 'Manifestation', 'Manifest as the pinnacle of your spirit.'),
    ],
    choices: [{ id: 'shaman-hex', label: 'Hex', kind: 'list', count: 1, levels: [2, 4, 8, 10, 12, 16, 18, 20], options: WITCH_HEXES }],
  },
  skald: {
    features: [
      f(1, 'skald-knowledge', 'Bardic Knowledge', 'Add half level to all Knowledge checks and use them untrained.'),
      f(1, 'skald-cantrips', 'Cantrips', 'Cast 0-level skald spells at will.'),
      f(1, 'skald-raging-song', 'Raging Song (Inspired Rage)', 'A performance that grants allies a barbarian-style rage; bonuses scale as you level.'),
      f(1, 'skald-scribe-scroll', 'Scribe Scroll', 'Gain Scribe Scroll as a bonus feat.'),
      f(2, 'skald-versatile-performance', 'Versatile Performance', 'Use a Perform skill in place of its associated skills.'),
      f(2, 'skald-well-versed', 'Well-Versed', '+4 on saves vs sonic and language-dependent effects.'),
      f(4, 'skald-uncanny-dodge', 'Uncanny Dodge', 'Keep Dex to AC when flat-footed or surprised.'),
      f(5, 'skald-spell-kenning', 'Spell Kenning', 'Cast any spell on the bard, cleric, or sorcerer/wizard list a few times per day.'),
      f(7, 'skald-lore-master', 'Lore Master', 'Take 10 (later 20) on known Knowledge skills.'),
      f(8, 'skald-improved-uncanny-dodge', 'Improved Uncanny Dodge', 'Cannot be flanked except by a rogue 4+ levels higher.'),
      f(9, 'skald-dr', 'Damage Reduction 1/—', 'DR 1/—, improving at 14th and 19th.'),
      f(10, 'skald-dirge-of-doom', 'Dirge of Doom', 'Shake nearby enemies with a grim performance.'),
      f(20, 'skald-master', 'Master Skald', 'Raging song and spell kenning reach their peak.'),
    ],
    choices: [{ id: 'skald-rage-power', label: 'Rage power', kind: 'list', count: 1, levels: [3, 6, 9, 12, 15, 18], options: BARBARIAN_RAGE_POWERS }],
  },
  shifter: {
    features: [
      f(1, 'shifter-aspect', 'Shifter Aspect', 'Take on a major animal aspect for scaling benefits; more aspects at 5th, 10th, 15th, 20th.'),
      f(1, 'shifter-claws', 'Shifter Claws', 'Grow claws dealing scaling damage that bypass more DR as you level.'),
      f(1, 'shifter-wild-empathy', 'Wild Empathy', 'Influence animals as a Diplomacy check.'),
      f(2, 'shifter-defensive-instinct', 'Defensive Instinct', 'Add Wis to AC while unarmored; improves every 4 levels.'),
      f(2, 'shifter-track', 'Track', 'Add half level to Survival to follow tracks.'),
      f(3, 'shifter-woodland-stride', 'Woodland Stride', 'Move through undergrowth unhindered.'),
      f(4, 'shifter-wild-shape', 'Wild Shape', 'Assume the form of your chosen aspects, improving with level.'),
      f(5, 'shifter-trackless-step', 'Trackless Step', 'Leave no trail in natural surroundings.'),
      f(6, 'shifter-fury', "Shifter's Fury", 'Make a full attack with both claws as a two-weapon flurry.'),
      f(9, 'shifter-chimeric-aspect', 'Chimeric Aspect', 'Blend two minor aspects at once.'),
      f(18, 'shifter-thousand-faces', 'A Thousand Faces', 'Change your appearance at will.'),
      f(20, 'shifter-final-aspect', 'Final Aspect', 'Master your defining animal aspect.'),
    ],
    choices: [{ id: 'shifter-aspect-extra', label: 'Additional aspect', kind: 'list', count: 1, levels: [5, 10, 15, 20], options: SHIFTER_ASPECTS }],
  },
  // Table 1–1 read from the class page's markup. Technique feats are the class's bonus-feat
  // track: 1st, 3rd, and every three levels after.
  'vampire-hunter': {
    bonusFeats: { levels: [1, 3, 6, 9, 12, 15, 18], label: 'Technique feat' },
    features: [
      f(1, 'vh-detect-undead', 'Detect Undead', 'Use detect undead at will; a move action pinpoints one target within 60 ft.'),
      f(1, 'vh-track', 'Track', 'Add half your level to Survival checks to follow tracks.'),
      f(1, 'vh-focus', 'Vampiric Focus', 'Mimic one common vampiric power, gaining its bonus or special ability.'),
      f(2, 'vh-relentless', 'Relentless', 'Press an undead quarry without faltering.'),
      f(4, 'vh-spellcasting', 'Spellcasting', 'Begin casting divine spells spontaneously from the inquisitor list (no orisons, nothing above 4th level).'),
      f(4, 'vh-stake', 'Stake', 'Drive a stake home against a helpless or staggered vampire.'),
      f(5, 'vh-relentless-band', 'Relentless Band', 'Extend your relentless pursuit to allies around you.'),
      f(7, 'vh-vampire-tracker', 'Vampire Tracker', 'Follow a vampire’s trail with supernatural accuracy.'),
      f(8, 'vh-second-focus', 'Second Vampiric Focus', 'Select a second vampiric focus.'),
      f(10, 'vh-swift-tracker', 'Swift Tracker', 'Track at full speed without penalty.'),
      f(11, 'vh-vampire-bane', 'Vampire Bane', 'Your attacks bite deeper against vampires.'),
      f(13, 'vh-remove-vampirism', 'Remove Vampirism', 'Free a victim from a vampire’s corruption.'),
      f(14, 'vh-quarry', 'Quarry', 'Designate a target for bonus attacks and guaranteed tracking.'),
      f(16, 'vh-third-focus', 'Third Vampiric Focus', 'Select a third vampiric focus.'),
      f(17, 'vh-critical-reflexes', 'Critical Reflexes', 'Turn a foe’s opening into a telling blow.'),
      f(19, 'vh-improved-quarry', 'Improved Quarry', 'Quarry bonuses increase and re-designate as a free action.'),
      f(20, 'vh-master', 'Master Vampire Hunter', 'The culmination of the hunt — destroy the undead you have studied.'),
    ],
  },
};
