import type { FeatDef } from './model';
import { WEAPONS } from './equipment';
import { SKILLS } from './skills';

// Parameter option lists are derived from the catalogues rather than hand-listed, so a feat like
// Weapon Focus offers every weapon we know about instead of a frozen subset of eight. Each option
// keeps the catalogue id so the engine can match the pick to a weapon/skill without string-matching.
const byName = (a: { name: string }, b: { name: string }) => a.name.localeCompare(b.name);
const WEAPON_OPTIONS = WEAPONS.map((w) => ({ id: w.id, name: w.name })).sort(byName);
// Exotic Weapon Proficiency names one exotic weapon — except for firearms, where the single pick
// "firearms" grants the whole group at once. That option carries the group id, not a weapon id.
export const FIREARM_GROUP_ID = 'firearms';
const EXOTIC_WEAPON_OPTIONS = [
  // Named for how the feat reads on the sheet — "Exotic Weapon Proficiency (Firearms)".
  { id: FIREARM_GROUP_ID, name: 'Firearms' },
  ...WEAPONS.filter((w) => w.group === 'exotic').map((w) => ({ id: w.id, name: w.name })).sort(byName),
];
const SKILL_OPTIONS = SKILLS.map((s) => ({ id: s.id, name: s.name })).sort(byName);
const CROSSBOW_OPTIONS = WEAPONS.filter((w) => w.id.includes('crossbow')).map((w) => ({ id: w.id, name: w.name }));
const MARTIAL_WEAPON_OPTIONS = WEAPONS.filter((w) => w.group === 'martial').map((w) => ({ id: w.id, name: w.name })).sort(byName);
const SCHOOL_OPTIONS = ['Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation']
  .map((n) => ({ id: n.toLowerCase(), name: n }));

// Core feats. prerequisites use the predicate DSL; effects fold into the stat graph.
export const FEATS: FeatDef[] = [
  { id: 'power-attack', name: 'Power Attack', types: ['combat'], reqText: 'Str 13, BAB +1',
    benefit: 'Take a −1 penalty on melee attack rolls to gain +2 on melee damage (+3 with a two-handed weapon). Penalty and bonus rise every +4 BAB.',
    prerequisites: { all: [{ ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'cleave', name: 'Cleave', types: ['combat'], reqText: 'Power Attack, Str 13, BAB +1',
    benefit: 'As a standard action, make a single melee attack; if it hits, make one more against an adjacent foe.',
    prerequisites: { all: [{ feat: 'power-attack' }, { ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'dodge', name: 'Dodge', types: ['combat'], reqText: 'Dex 13',
    benefit: '+1 dodge bonus to AC.', prerequisites: { ability: 'dex', gte: 13 },
    effects: [{ target: 'ac', type: 'dodge', value: 1, note: 'Dodge' }] },
  { id: 'mobility', name: 'Mobility', types: ['combat'], reqText: 'Dodge, Dex 13',
    benefit: '+4 dodge bonus to AC against attacks of opportunity provoked by movement.',
    prerequisites: { all: [{ feat: 'dodge' }, { ability: 'dex', gte: 13 }] } },
  { id: 'combat-expertise', name: 'Combat Expertise', types: ['combat'], reqText: 'Int 13',
    benefit: 'Take a penalty on attack rolls to gain a dodge bonus to AC.',
    prerequisites: { ability: 'int', gte: 13 } },
  { id: 'weapon-finesse', name: 'Weapon Finesse', types: ['combat'], reqText: '—',
    benefit: 'Use Dex modifier instead of Str on attack rolls with light melee weapons.' },
  { id: 'weapon-focus', name: 'Weapon Focus', types: ['combat'], reqText: 'Proficiency with weapon, BAB +1',
    benefit: '+1 bonus on attack rolls with the selected weapon.', prerequisites: { bab: 1 },
    param: { label: 'Weapon', options: WEAPON_OPTIONS } },
  { id: 'exotic-weapon-proficiency', name: 'Exotic Weapon Proficiency', types: ['combat'], reqText: 'BAB +1',
    benefit: 'You make attacks with the selected exotic weapon normally, without the −4 non-proficiency penalty. Choosing firearms grants proficiency with every firearm at once.',
    prerequisites: { bab: 1 }, param: { label: 'Weapon', options: EXOTIC_WEAPON_OPTIONS } },
  { id: 'gunsmithing', name: 'Gunsmithing', types: ['general'], reqText: '—',
    benefit: "With a gunsmith's kit you can craft and repair firearms, craft bullets and cartridges, and mix black powder without a Craft check. An hour's work each day restores one broken firearm." },
  { id: 'two-weapon-fighting', name: 'Two-Weapon Fighting', types: ['combat'], reqText: 'Dex 15',
    benefit: 'Reduce the penalties for fighting with two weapons.', prerequisites: { ability: 'dex', gte: 15 } },
  { id: 'point-blank-shot', name: 'Point-Blank Shot', types: ['combat'], reqText: '—',
    benefit: '+1 on attack and damage rolls with ranged weapons within 30 feet.' },
  { id: 'precise-shot', name: 'Precise Shot', types: ['combat'], reqText: 'Point-Blank Shot',
    benefit: 'No −4 penalty for shooting into melee.', prerequisites: { feat: 'point-blank-shot' } },
  { id: 'rapid-shot', name: 'Rapid Shot', types: ['combat'], reqText: 'Point-Blank Shot, Dex 13',
    benefit: 'Make one extra ranged attack each round at a −2 penalty to all.',
    prerequisites: { all: [{ feat: 'point-blank-shot' }, { ability: 'dex', gte: 13 }] } },
  { id: 'improved-initiative', name: 'Improved Initiative', types: ['combat'], reqText: '—',
    benefit: '+4 bonus on initiative checks.', effects: [{ target: 'init', type: 'untyped', value: 4, note: 'Improved Initiative' }] },
  { id: 'toughness', name: 'Toughness', types: ['general'], reqText: '—',
    benefit: '+3 hit points, plus 1 more per Hit Die beyond 3rd.', effects: [{ target: 'hp:max', type: 'untyped', value: 3, note: 'Toughness' }] },
  { id: 'iron-will', name: 'Iron Will', types: ['general'], reqText: '—',
    benefit: '+2 bonus on Will saves.', effects: [{ target: 'save:will', type: 'untyped', value: 2, note: 'Iron Will' }] },
  { id: 'lightning-reflexes', name: 'Lightning Reflexes', types: ['general'], reqText: '—',
    benefit: '+2 bonus on Reflex saves.', effects: [{ target: 'save:ref', type: 'untyped', value: 2, note: 'Lightning Reflexes' }] },
  { id: 'great-fortitude', name: 'Great Fortitude', types: ['general'], reqText: '—',
    benefit: '+2 bonus on Fortitude saves.', effects: [{ target: 'save:fort', type: 'untyped', value: 2, note: 'Great Fortitude' }] },
  { id: 'skill-focus', name: 'Skill Focus', types: ['general'], reqText: '—',
    benefit: '+3 bonus on the chosen skill (+6 at 10 ranks).',
    param: { label: 'Skill', options: SKILL_OPTIONS } },
  { id: 'combat-casting', name: 'Combat Casting', types: ['general'], reqText: '—',
    benefit: '+4 bonus on concentration checks made to cast defensively.' },
  { id: 'spell-focus', name: 'Spell Focus', types: ['general'], reqText: 'Ability to cast spells',
    benefit: '+1 to the DC of saving throws against spells of the chosen school.',
    param: { label: 'School', options: SCHOOL_OPTIONS } },
  { id: 'improved-unarmed-strike', name: 'Improved Unarmed Strike', types: ['combat'], reqText: '—',
    benefit: 'Deal lethal damage with unarmed strikes and are always considered armed.' },
  { id: 'throw-anything', name: 'Throw Anything', types: ['combat'], reqText: '—',
    benefit: 'No penalty for using an improvised ranged weapon, and +1 circumstance bonus on attack rolls with thrown splash weapons.' },
  { id: 'weapon-specialization', name: 'Weapon Specialization', types: ['combat'], reqText: 'Weapon Focus, Fighter 4',
    benefit: '+2 bonus on damage rolls with the selected weapon.',
    prerequisites: { all: [{ feat: 'weapon-focus' }, { classId: 'fighter' }] } },
  { id: 'greater-weapon-focus', name: 'Greater Weapon Focus', types: ['combat'], reqText: 'Weapon Focus, Fighter 8',
    benefit: '+1 more on attack rolls with the selected weapon (stacks with Weapon Focus).',
    prerequisites: { all: [{ feat: 'weapon-focus' }, { classId: 'fighter' }] },
    param: { label: 'Weapon', options: WEAPON_OPTIONS } },
  { id: 'greater-weapon-specialization', name: 'Greater Weapon Specialization', types: ['combat'], reqText: 'Weapon Specialization, Fighter 12',
    benefit: '+2 more on damage rolls with the selected weapon (stacks with Weapon Specialization).',
    prerequisites: { all: [{ feat: 'weapon-specialization' }, { classId: 'fighter' }] } },

  // ---- Combat feats (situational; no static stat effect) ----
  { id: 'great-cleave', name: 'Great Cleave', types: ['combat'], reqText: 'Cleave, Str 13, BAB +4',
    benefit: 'As Cleave, but keep making attacks as long as you hit fresh adjacent foes.',
    prerequisites: { all: [{ feat: 'cleave' }, { ability: 'str', gte: 13 }, { bab: 4 }] } },
  { id: 'combat-reflexes', name: 'Combat Reflexes', types: ['combat'], reqText: '—',
    benefit: 'Make a number of extra attacks of opportunity per round equal to your Dex modifier, even when flat-footed.' },
  { id: 'deadly-aim', name: 'Deadly Aim', types: ['combat'], reqText: 'Dex 13, BAB +1',
    benefit: 'Take a −1 penalty on ranged attacks to gain +2 on ranged damage; scales every +4 BAB.',
    prerequisites: { all: [{ ability: 'dex', gte: 13 }, { bab: 1 }] } },
  { id: 'deflect-arrows', name: 'Deflect Arrows', types: ['combat'], reqText: 'Improved Unarmed Strike, Dex 13',
    benefit: 'Once per round, deflect one ranged attack that would hit you.',
    prerequisites: { all: [{ feat: 'improved-unarmed-strike' }, { ability: 'dex', gte: 13 }] } },
  { id: 'improved-bull-rush', name: 'Improved Bull Rush', types: ['combat'], reqText: 'Power Attack, Str 13, BAB +1',
    benefit: 'No attack of opportunity when bull rushing, and +2 on the check.',
    prerequisites: { all: [{ feat: 'power-attack' }, { ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'improved-disarm', name: 'Improved Disarm', types: ['combat'], reqText: 'Combat Expertise, Int 13',
    benefit: 'No attack of opportunity when disarming, and +2 on the check.',
    prerequisites: { all: [{ feat: 'combat-expertise' }, { ability: 'int', gte: 13 }] } },
  { id: 'improved-feint', name: 'Improved Feint', types: ['combat'], reqText: 'Combat Expertise, Int 13',
    benefit: 'Feint in combat as a move action instead of a standard action.',
    prerequisites: { all: [{ feat: 'combat-expertise' }, { ability: 'int', gte: 13 }] } },
  { id: 'improved-grapple', name: 'Improved Grapple', types: ['combat'], reqText: 'Improved Unarmed Strike, Dex 13',
    benefit: 'No attack of opportunity when grappling, and +2 on the check.',
    prerequisites: { all: [{ feat: 'improved-unarmed-strike' }, { ability: 'dex', gte: 13 }] } },
  { id: 'improved-overrun', name: 'Improved Overrun', types: ['combat'], reqText: 'Power Attack, Str 13, BAB +1',
    benefit: 'No attack of opportunity when overrunning; targets cannot avoid you, and +2 on the check.',
    prerequisites: { all: [{ feat: 'power-attack' }, { ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'improved-sunder', name: 'Improved Sunder', types: ['combat'], reqText: 'Power Attack, Str 13, BAB +1',
    benefit: 'No attack of opportunity when sundering, and +2 on the check.',
    prerequisites: { all: [{ feat: 'power-attack' }, { ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'improved-trip', name: 'Improved Trip', types: ['combat'], reqText: 'Combat Expertise, Int 13',
    benefit: 'No attack of opportunity when tripping, and +2 on the check.',
    prerequisites: { all: [{ feat: 'combat-expertise' }, { ability: 'int', gte: 13 }] } },
  { id: 'improved-two-weapon-fighting', name: 'Improved Two-Weapon Fighting', types: ['combat'], reqText: 'Two-Weapon Fighting, Dex 15, BAB +6',
    benefit: 'Gain a second off-hand attack at a −5 penalty.',
    prerequisites: { all: [{ feat: 'two-weapon-fighting' }, { ability: 'dex', gte: 15 }, { bab: 6 }] } },
  { id: 'greater-two-weapon-fighting', name: 'Greater Two-Weapon Fighting', types: ['combat'], reqText: 'Improved Two-Weapon Fighting, Dex 19, BAB +11',
    benefit: 'Gain a third off-hand attack at a −10 penalty.',
    prerequisites: { all: [{ feat: 'improved-two-weapon-fighting' }, { ability: 'dex', gte: 19 }, { bab: 11 }] } },
  { id: 'two-weapon-defense', name: 'Two-Weapon Defense', types: ['combat'], reqText: 'Two-Weapon Fighting, Dex 15',
    benefit: '+1 shield bonus to AC while wielding two weapons (+2 when fighting defensively).',
    prerequisites: { all: [{ feat: 'two-weapon-fighting' }, { ability: 'dex', gte: 15 }] } },
  { id: 'improved-precise-shot', name: 'Improved Precise Shot', types: ['combat'], reqText: 'Precise Shot, Dex 19, BAB +11',
    benefit: 'Ignore concealment (not total) and cover (not total) with ranged attacks.',
    prerequisites: { all: [{ feat: 'precise-shot' }, { ability: 'dex', gte: 19 }, { bab: 11 }] } },
  { id: 'manyshot', name: 'Manyshot', types: ['combat'], reqText: 'Rapid Shot, Dex 17, BAB +6',
    benefit: 'Fire two arrows with the first ranged attack of a full attack.',
    prerequisites: { all: [{ feat: 'rapid-shot' }, { ability: 'dex', gte: 17 }, { bab: 6 }] } },
  { id: 'mounted-combat', name: 'Mounted Combat', types: ['combat'], reqText: 'Ride 1 rank',
    benefit: 'Once per round, negate a hit against your mount with a Ride check.',
    prerequisites: { skillRanks: { skill: 'ride', gte: 1 } } },
  { id: 'rapid-reload', name: 'Rapid Reload', types: ['combat'], reqText: 'Weapon Proficiency (crossbow)',
    benefit: 'Reload the chosen crossbow more quickly (free or move action).',
    param: { label: 'Crossbow', options: CROSSBOW_OPTIONS } },
  { id: 'spring-attack', name: 'Spring Attack', types: ['combat'], reqText: 'Dodge, Mobility, Dex 13, BAB +4',
    benefit: 'Move before and after a melee attack without provoking from the target.',
    prerequisites: { all: [{ feat: 'dodge' }, { feat: 'mobility' }, { ability: 'dex', gte: 13 }, { bab: 4 }] } },
  { id: 'whirlwind-attack', name: 'Whirlwind Attack', types: ['combat'], reqText: 'Combat Expertise, Spring Attack, Int 13, Dex 13, BAB +4',
    benefit: 'As a full-round action, make one melee attack against every foe in reach.',
    prerequisites: { all: [{ feat: 'combat-expertise' }, { feat: 'spring-attack' }, { ability: 'int', gte: 13 }, { ability: 'dex', gte: 13 }, { bab: 4 }] } },
  { id: 'vital-strike', name: 'Vital Strike', types: ['combat'], reqText: 'BAB +6',
    benefit: 'On a single attack, roll weapon damage dice twice.', prerequisites: { bab: 6 } },
  { id: 'improved-vital-strike', name: 'Improved Vital Strike', types: ['combat'], reqText: 'Vital Strike, BAB +11',
    benefit: 'On a single attack, roll weapon damage dice three times.',
    prerequisites: { all: [{ feat: 'vital-strike' }, { bab: 11 }] } },
  { id: 'greater-vital-strike', name: 'Greater Vital Strike', types: ['combat'], reqText: 'Improved Vital Strike, BAB +16',
    benefit: 'On a single attack, roll weapon damage dice four times.',
    prerequisites: { all: [{ feat: 'improved-vital-strike' }, { bab: 16 }] } },
  { id: 'stunning-fist', name: 'Stunning Fist', types: ['combat'], reqText: 'Dex 13, Wis 13, Improved Unarmed Strike, BAB +8',
    benefit: 'Force a struck foe to save or be stunned; usable once per four levels per day.',
    prerequisites: { all: [{ ability: 'dex', gte: 13 }, { ability: 'wis', gte: 13 }, { feat: 'improved-unarmed-strike' }, { bab: 8 }] } },

  // ---- General feats ----
  { id: 'alertness', name: 'Alertness', types: ['general'], reqText: '—',
    benefit: '+2 on Perception and Sense Motive (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:perception', type: 'untyped', value: 2, note: 'Alertness' }, { target: 'skill:sense-motive', type: 'untyped', value: 2, note: 'Alertness' }] },
  { id: 'acrobatic', name: 'Acrobatic', types: ['general'], reqText: '—',
    benefit: '+2 on Acrobatics and Fly (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:acrobatics', type: 'untyped', value: 2, note: 'Acrobatic' }, { target: 'skill:fly', type: 'untyped', value: 2, note: 'Acrobatic' }] },
  { id: 'athletic', name: 'Athletic', types: ['general'], reqText: '—',
    benefit: '+2 on Climb and Swim (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:climb', type: 'untyped', value: 2, note: 'Athletic' }, { target: 'skill:swim', type: 'untyped', value: 2, note: 'Athletic' }] },
  { id: 'deceitful', name: 'Deceitful', types: ['general'], reqText: '—',
    benefit: '+2 on Bluff and Disguise (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:bluff', type: 'untyped', value: 2, note: 'Deceitful' }, { target: 'skill:disguise', type: 'untyped', value: 2, note: 'Deceitful' }] },
  { id: 'deft-hands', name: 'Deft Hands', types: ['general'], reqText: '—',
    benefit: '+2 on Disable Device and Sleight of Hand (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:disable-device', type: 'untyped', value: 2, note: 'Deft Hands' }, { target: 'skill:sleight-of-hand', type: 'untyped', value: 2, note: 'Deft Hands' }] },
  { id: 'persuasive', name: 'Persuasive', types: ['general'], reqText: '—',
    benefit: '+2 on Diplomacy and Intimidate (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:diplomacy', type: 'untyped', value: 2, note: 'Persuasive' }, { target: 'skill:intimidate', type: 'untyped', value: 2, note: 'Persuasive' }] },
  { id: 'self-sufficient', name: 'Self-Sufficient', types: ['general'], reqText: '—',
    benefit: '+2 on Heal and Survival (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:heal', type: 'untyped', value: 2, note: 'Self-Sufficient' }, { target: 'skill:survival', type: 'untyped', value: 2, note: 'Self-Sufficient' }] },
  { id: 'stealthy', name: 'Stealthy', types: ['general'], reqText: '—',
    benefit: '+2 on Escape Artist and Stealth (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:escape-artist', type: 'untyped', value: 2, note: 'Stealthy' }, { target: 'skill:stealth', type: 'untyped', value: 2, note: 'Stealthy' }] },
  { id: 'animal-affinity', name: 'Animal Affinity', types: ['general'], reqText: '—',
    benefit: '+2 on Handle Animal and Ride (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:handle-animal', type: 'untyped', value: 2, note: 'Animal Affinity' }, { target: 'skill:ride', type: 'untyped', value: 2, note: 'Animal Affinity' }] },
  { id: 'endurance', name: 'Endurance', types: ['general'], reqText: '—',
    benefit: '+4 on checks to resist exhaustion, and sleep in medium/light armor without fatigue.' },
  { id: 'diehard', name: 'Diehard', types: ['general'], reqText: 'Endurance',
    benefit: 'Remain conscious and staggered below 0 hit points instead of dying.', prerequisites: { feat: 'endurance' } },
  { id: 'run', name: 'Run', types: ['general'], reqText: '—',
    benefit: 'Run at 5× speed (4× in armor) and gain +4 on running Acrobatics jumps.' },

  // ---- Spellcasting feats ----
  { id: 'greater-spell-focus', name: 'Greater Spell Focus', types: ['general'], reqText: 'Spell Focus',
    benefit: '+1 more to save DCs of the chosen school (stacks with Spell Focus).',
    prerequisites: { feat: 'spell-focus' },
    param: { label: 'School', options: SCHOOL_OPTIONS } },
  { id: 'spell-penetration', name: 'Spell Penetration', types: ['general'], reqText: '—',
    benefit: '+2 on caster level checks to overcome spell resistance.' },
  { id: 'greater-spell-penetration', name: 'Greater Spell Penetration', types: ['general'], reqText: 'Spell Penetration',
    benefit: '+2 more on caster level checks to overcome spell resistance.', prerequisites: { feat: 'spell-penetration' } },
  { id: 'augment-summoning', name: 'Augment Summoning', types: ['general'], reqText: 'Spell Focus (conjuration)',
    benefit: 'Summoned creatures gain +4 Strength and Constitution.', prerequisites: { feat: 'spell-focus' } },
  { id: 'eschew-materials', name: 'Eschew Materials', types: ['general'], reqText: '—',
    benefit: 'Cast spells without material components costing 1 gp or less.' },

  // ---- Metamagic feats ----
  { id: 'empower-spell', name: 'Empower Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Increase a spell\'s variable numeric effects by half (+2 spell levels).' },
  { id: 'extend-spell', name: 'Extend Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Double a spell\'s duration (+1 spell level).' },
  { id: 'maximize-spell', name: 'Maximize Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Maximize a spell\'s variable numeric effects (+3 spell levels).' },
  { id: 'quicken-spell', name: 'Quicken Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Cast a spell as a swift action (+4 spell levels).' },
  { id: 'silent-spell', name: 'Silent Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Cast a spell without verbal components (+1 spell level).' },
  { id: 'still-spell', name: 'Still Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Cast a spell without somatic components (+1 spell level).' },
  { id: 'widen-spell', name: 'Widen Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Double the area of a burst, emanation, line, or spread (+3 spell levels).' },
  { id: 'heighten-spell', name: 'Heighten Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Cast a spell at a higher effective spell level for a higher save DC.' },
  { id: 'enlarge-spell', name: 'Enlarge Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Double a spell\'s range (+1 spell level).' },

  // ---- Item creation feats ----
  { id: 'scribe-scroll', name: 'Scribe Scroll', types: ['item-creation'], reqText: 'Caster level 1',
    benefit: 'Create magic scrolls.', prerequisites: { casterLevel: 1 } },
  { id: 'brew-potion', name: 'Brew Potion', types: ['item-creation'], reqText: 'Caster level 3',
    benefit: 'Create potions of spells you can cast (3rd level or lower).', prerequisites: { casterLevel: 3 } },
  { id: 'craft-wand', name: 'Craft Wand', types: ['item-creation'], reqText: 'Caster level 5',
    benefit: 'Create wands of spells you know (4th level or lower).', prerequisites: { casterLevel: 5 } },
  { id: 'craft-wondrous-item', name: 'Craft Wondrous Item', types: ['item-creation'], reqText: 'Caster level 3',
    benefit: 'Create a wide range of magic wondrous items.', prerequisites: { casterLevel: 3 } },
  { id: 'craft-magic-arms-and-armor', name: 'Craft Magic Arms and Armor', types: ['item-creation'], reqText: 'Caster level 5',
    benefit: 'Create and enhance magic weapons, armor, and shields.', prerequisites: { casterLevel: 5 } },
  { id: 'forge-ring', name: 'Forge Ring', types: ['item-creation'], reqText: 'Caster level 7',
    benefit: 'Create magic rings.', prerequisites: { casterLevel: 7 } },
  { id: 'craft-rod', name: 'Craft Rod', types: ['item-creation'], reqText: 'Caster level 9',
    benefit: 'Create magic rods.', prerequisites: { casterLevel: 9 } },
  { id: 'craft-staff', name: 'Craft Staff', types: ['item-creation'], reqText: 'Caster level 11',
    benefit: 'Create magic staves.', prerequisites: { casterLevel: 11 } },

  // ---- Proficiency feats ----
  { id: 'simple-weapon-proficiency', name: 'Simple Weapon Proficiency', types: ['combat'], reqText: '—',
    benefit: 'You are proficient with all simple weapons.' },
  { id: 'martial-weapon-proficiency', name: 'Martial Weapon Proficiency', types: ['combat'], reqText: '—',
    benefit: 'You are proficient with the selected martial weapon, without the −4 non-proficiency penalty.',
    param: { label: 'Weapon', options: MARTIAL_WEAPON_OPTIONS } },
  { id: 'armor-proficiency-light', name: 'Armor Proficiency (Light)', types: ['combat'], reqText: '—',
    benefit: 'No armor check penalty on attack rolls while wearing light armor.' },
  { id: 'armor-proficiency-medium', name: 'Armor Proficiency (Medium)', types: ['combat'], reqText: 'Armor Proficiency (Light)',
    benefit: 'No armor check penalty on attack rolls while wearing medium armor.', prerequisites: { feat: 'armor-proficiency-light' } },
  { id: 'armor-proficiency-heavy', name: 'Armor Proficiency (Heavy)', types: ['combat'], reqText: 'Armor Proficiency (Medium)',
    benefit: 'No armor check penalty on attack rolls while wearing heavy armor.', prerequisites: { feat: 'armor-proficiency-medium' } },
  { id: 'shield-proficiency', name: 'Shield Proficiency', types: ['combat'], reqText: '—',
    benefit: 'No armor check penalty on attack rolls from a shield you wield (except the tower shield’s).' },

  // ---- Combat feats: maneuvers & positioning ----
  { id: 'agile-maneuvers', name: 'Agile Maneuvers', types: ['combat'], reqText: '—',
    benefit: 'Use your Dexterity bonus in place of Strength when calculating your Combat Maneuver Bonus.' },
  { id: 'defensive-combat-training', name: 'Defensive Combat Training', types: ['combat'], reqText: '—',
    benefit: 'Treat your total Hit Dice as your base attack bonus when determining your CMD.' },
  { id: 'quick-draw', name: 'Quick Draw', types: ['combat'], reqText: 'BAB +1',
    benefit: 'Draw a weapon as a free action, and draw a hidden weapon as a move action.', prerequisites: { bab: 1 } },
  { id: 'step-up', name: 'Step Up', types: ['combat'], reqText: 'BAB +1',
    benefit: 'When an adjacent foe takes a 5-foot step away, follow with a 5-foot step as an immediate action.', prerequisites: { bab: 1 } },
  { id: 'lunge', name: 'Lunge', types: ['combat'], reqText: 'BAB +6',
    benefit: 'Take a −2 penalty to AC to increase your melee reach by 5 feet until your next turn.', prerequisites: { bab: 6 } },
  { id: 'stand-still', name: 'Stand Still', types: ['combat'], reqText: 'Combat Reflexes',
    benefit: 'When a foe provokes an attack of opportunity by moving, make a combat maneuver check to halt its movement.', prerequisites: { feat: 'combat-reflexes' } },
  { id: 'strike-back', name: 'Strike Back', types: ['combat'], reqText: 'BAB +11',
    benefit: 'Ready an action to strike foes attacking you with greater reach.', prerequisites: { bab: 11 } },
  { id: 'nimble-moves', name: 'Nimble Moves', types: ['combat'], reqText: 'Dex 13',
    benefit: 'Move through 5 feet of difficult terrain each round as if it were normal terrain.', prerequisites: { ability: 'dex', gte: 13 } },
  { id: 'acrobatic-steps', name: 'Acrobatic Steps', types: ['combat'], reqText: 'Nimble Moves, Dex 15',
    benefit: 'Move through 20 feet of difficult terrain each round as if it were normal terrain.',
    prerequisites: { all: [{ feat: 'nimble-moves' }, { ability: 'dex', gte: 15 }] } },

  // ---- Combat feats: combat-maneuver chains (greater forms) ----
  { id: 'greater-bull-rush', name: 'Greater Bull Rush', types: ['combat'], reqText: 'Improved Bull Rush, Str 13, Power Attack, BAB +6',
    benefit: 'Foes you bull rush provoke attacks of opportunity from your allies.',
    prerequisites: { all: [{ feat: 'improved-bull-rush' }, { bab: 6 }] } },
  { id: 'greater-disarm', name: 'Greater Disarm', types: ['combat'], reqText: 'Improved Disarm, Combat Expertise, Int 13, BAB +6',
    benefit: 'Disarmed weapons land 15 feet away, and a failed disarm no longer provokes.',
    prerequisites: { all: [{ feat: 'improved-disarm' }, { bab: 6 }] } },
  { id: 'greater-feint', name: 'Greater Feint', types: ['combat'], reqText: 'Improved Feint, Combat Expertise, Int 13, BAB +6',
    benefit: 'A foe you feint loses its Dexterity bonus to AC until the end of your next turn.',
    prerequisites: { all: [{ feat: 'improved-feint' }, { bab: 6 }] } },
  { id: 'greater-grapple', name: 'Greater Grapple', types: ['combat'], reqText: 'Improved Grapple, Improved Unarmed Strike, Dex 13, BAB +6',
    benefit: 'Maintaining a grapple is a move action, letting you make two grapple checks a round.',
    prerequisites: { all: [{ feat: 'improved-grapple' }, { bab: 6 }] } },
  { id: 'greater-overrun', name: 'Greater Overrun', types: ['combat'], reqText: 'Improved Overrun, Str 13, Power Attack, BAB +6',
    benefit: 'Foes you overrun provoke attacks of opportunity from your allies.',
    prerequisites: { all: [{ feat: 'improved-overrun' }, { bab: 6 }] } },
  { id: 'greater-sunder', name: 'Greater Sunder', types: ['combat'], reqText: 'Improved Sunder, Str 13, Power Attack, BAB +6',
    benefit: 'Excess damage from a sunder attempt carries over to the item’s wielder.',
    prerequisites: { all: [{ feat: 'improved-sunder' }, { bab: 6 }] } },
  { id: 'greater-trip', name: 'Greater Trip', types: ['combat'], reqText: 'Improved Trip, Combat Expertise, Int 13, BAB +6',
    benefit: 'Foes you trip provoke attacks of opportunity, and you get +2 more on trip checks.',
    prerequisites: { all: [{ feat: 'improved-trip' }, { bab: 6 }] } },

  // ---- Combat feats: two-weapon & shield ----
  { id: 'double-slice', name: 'Double Slice', types: ['combat'], reqText: 'Two-Weapon Fighting, Dex 15',
    benefit: 'Add your full Strength bonus to off-hand damage rolls.',
    prerequisites: { all: [{ feat: 'two-weapon-fighting' }, { ability: 'dex', gte: 15 }] } },
  { id: 'two-weapon-rend', name: 'Two-Weapon Rend', types: ['combat'], reqText: 'Double Slice, Improved Two-Weapon Fighting, Dex 17, BAB +11',
    benefit: 'Hitting one foe with both weapons in a round deals an extra 1d10 + 1½ × Str damage.',
    prerequisites: { all: [{ feat: 'double-slice' }, { feat: 'improved-two-weapon-fighting' }, { ability: 'dex', gte: 17 }, { bab: 11 }] } },
  { id: 'improved-shield-bash', name: 'Improved Shield Bash', types: ['combat'], reqText: 'Shield Proficiency',
    benefit: 'Keep your shield’s AC bonus in a round you make a shield bash.', prerequisites: { feat: 'shield-proficiency' } },
  { id: 'shield-slam', name: 'Shield Slam', types: ['combat'], reqText: 'Improved Shield Bash, Two-Weapon Fighting, Shield Proficiency, BAB +6',
    benefit: 'A shield bash can also make a free bull rush that provokes no attack of opportunity.',
    prerequisites: { all: [{ feat: 'improved-shield-bash' }, { feat: 'two-weapon-fighting' }, { bab: 6 }] } },
  { id: 'shield-master', name: 'Shield Master', types: ['combat'], reqText: 'Shield Slam, Improved Shield Bash, Two-Weapon Fighting, Shield Proficiency, BAB +11',
    benefit: 'No two-weapon penalty on shield attacks, and add the shield’s enhancement bonus to attack rolls.',
    prerequisites: { all: [{ feat: 'shield-slam' }, { bab: 11 }] } },
  { id: 'shield-focus', name: 'Shield Focus', types: ['combat'], reqText: 'Shield Proficiency, BAB +1',
    benefit: '+1 to the AC bonus granted by any shield you wield.',
    prerequisites: { all: [{ feat: 'shield-proficiency' }, { bab: 1 }] } },
  { id: 'greater-shield-focus', name: 'Greater Shield Focus', types: ['combat'], reqText: 'Shield Focus, Shield Proficiency, Fighter 8',
    benefit: '+1 more to the AC bonus granted by any shield you wield (stacks with Shield Focus).',
    prerequisites: { all: [{ feat: 'shield-focus' }, { classId: 'fighter' }] } },

  // ---- Combat feats: ranged ----
  { id: 'far-shot', name: 'Far Shot', types: ['combat'], reqText: 'Point-Blank Shot',
    benefit: 'Only a −1 penalty per full range increment on ranged attacks, instead of −2.', prerequisites: { feat: 'point-blank-shot' } },
  { id: 'pinpoint-targeting', name: 'Pinpoint Targeting', types: ['combat'], reqText: 'Improved Precise Shot, Dex 19, BAB +16',
    benefit: 'As a standard action, make one ranged attack that ignores the target’s armor, shield, and natural armor bonuses.',
    prerequisites: { all: [{ feat: 'improved-precise-shot' }, { ability: 'dex', gte: 19 }, { bab: 16 }] } },
  { id: 'snatch-arrows', name: 'Snatch Arrows', types: ['combat'], reqText: 'Deflect Arrows, Improved Unarmed Strike, Dex 15',
    benefit: 'When you would deflect a ranged attack, catch it instead if you have a free hand.',
    prerequisites: { all: [{ feat: 'deflect-arrows' }, { ability: 'dex', gte: 15 }] } },
  { id: 'wind-stance', name: 'Wind Stance', types: ['combat'], reqText: 'Dodge, Dex 15, BAB +6',
    benefit: 'If you move more than 5 feet, gain 20% concealment against ranged attacks until your next turn.',
    prerequisites: { all: [{ feat: 'dodge' }, { ability: 'dex', gte: 15 }, { bab: 6 }] } },
  { id: 'lightning-stance', name: 'Lightning Stance', types: ['combat'], reqText: 'Wind Stance, Dodge, Dex 17, BAB +11',
    benefit: 'If you take two actions to move, or a withdraw, gain 50% concealment until your next turn.',
    prerequisites: { all: [{ feat: 'wind-stance' }, { ability: 'dex', gte: 17 }, { bab: 11 }] } },

  // ---- Combat feats: mounted ----
  { id: 'mounted-archery', name: 'Mounted Archery', types: ['combat'], reqText: 'Mounted Combat, Ride 1 rank',
    benefit: 'Halve the penalty for using a ranged weapon while your mount moves.',
    prerequisites: { all: [{ feat: 'mounted-combat' }, { skillRanks: { skill: 'ride', gte: 1 } }] } },
  { id: 'ride-by-attack', name: 'Ride-By Attack', types: ['combat'], reqText: 'Mounted Combat, Ride 1 rank',
    benefit: 'On a mounted charge, move before and after the attack without provoking from the target.',
    prerequisites: { all: [{ feat: 'mounted-combat' }, { skillRanks: { skill: 'ride', gte: 1 } }] } },
  { id: 'spirited-charge', name: 'Spirited Charge', types: ['combat'], reqText: 'Ride-By Attack, Mounted Combat, Ride 1 rank, BAB +4',
    benefit: 'Deal double damage (triple with a lance) on a mounted charge.',
    prerequisites: { all: [{ feat: 'ride-by-attack' }, { bab: 4 }] } },
  { id: 'trample', name: 'Trample', types: ['combat'], reqText: 'Mounted Combat, Ride 1 rank',
    benefit: 'Overrun with your mount, dealing hoof damage to foes you knock down.',
    prerequisites: { all: [{ feat: 'mounted-combat' }, { skillRanks: { skill: 'ride', gte: 1 } }] } },
  { id: 'unseat', name: 'Unseat', types: ['combat'], reqText: 'Mounted Combat, Improved Bull Rush, Power Attack, Str 13, Ride 1 rank, BAB +1',
    benefit: 'A hit with a lance on a mounted charge lets you make a free bull rush to knock the foe from its mount.',
    prerequisites: { all: [{ feat: 'mounted-combat' }, { feat: 'improved-bull-rush' }, { skillRanks: { skill: 'ride', gte: 1 } }] } },
  { id: 'awesome-blow', name: 'Awesome Blow', types: ['combat'], reqText: 'Str 25, Power Attack, Improved Bull Rush, size Large',
    benefit: 'As a standard action, make a bull rush that also knocks a foe back and prone.',
    prerequisites: { all: [{ ability: 'str', gte: 25 }, { feat: 'power-attack' }, { feat: 'improved-bull-rush' }] } },

  // ---- Combat feats: unarmed / style chain ----
  { id: 'scorpion-style', name: 'Scorpion Style', types: ['combat'], reqText: 'Improved Unarmed Strike',
    benefit: 'A hit with an unarmed strike reduces a foe’s speed to 5 feet for a number of rounds equal to your Wis modifier.',
    prerequisites: { feat: 'improved-unarmed-strike' } },
  { id: 'gorgons-fist', name: "Gorgon's Fist", types: ['combat'], reqText: 'Scorpion Style, Improved Unarmed Strike, BAB +6',
    benefit: 'An unarmed strike against a slowed foe forces a Fortitude save or the target is staggered.',
    prerequisites: { all: [{ feat: 'scorpion-style' }, { bab: 6 }] } },
  { id: 'medusas-wrath', name: "Medusa's Wrath", types: ['combat'], reqText: "Gorgon's Fist, Scorpion Style, Improved Unarmed Strike, BAB +11",
    benefit: 'On a full attack against a hampered foe, make two extra unarmed strikes at your highest bonus.',
    prerequisites: { all: [{ feat: 'gorgons-fist' }, { bab: 11 }] } },

  // ---- Combat feats: precision & damage ----
  { id: 'improved-critical', name: 'Improved Critical', types: ['combat'], reqText: 'Proficiency with weapon, BAB +8',
    benefit: 'Double the threat range of the selected weapon (does not stack with keen).',
    prerequisites: { bab: 8 }, param: { label: 'Weapon', options: WEAPON_OPTIONS } },
  { id: 'penetrating-strike', name: 'Penetrating Strike', types: ['combat'], reqText: 'Weapon Focus, Fighter 12',
    benefit: 'Attacks with a weapon you have Weapon Focus in ignore up to 5 points of damage reduction.',
    prerequisites: { all: [{ feat: 'weapon-focus' }, { classId: 'fighter' }] } },
  { id: 'greater-penetrating-strike', name: 'Greater Penetrating Strike', types: ['combat'], reqText: 'Penetrating Strike, Weapon Focus, Fighter 16',
    benefit: 'Your Penetrating Strike ignores up to 10 points of damage reduction.',
    prerequisites: { all: [{ feat: 'penetrating-strike' }, { classId: 'fighter' }] } },
  { id: 'dazzling-display', name: 'Dazzling Display', types: ['combat'], reqText: 'Weapon Focus',
    benefit: 'As a standard action, brandish your chosen weapon to demoralize all foes within 30 feet.',
    prerequisites: { feat: 'weapon-focus' } },
  { id: 'shatter-defenses', name: 'Shatter Defenses', types: ['combat'], reqText: 'Weapon Focus, Dazzling Display, BAB +6',
    benefit: 'A shaken, frightened, or panicked foe you hit is flat-footed until the end of your next turn.',
    prerequisites: { all: [{ feat: 'dazzling-display' }, { bab: 6 }] } },
  { id: 'deadly-stroke', name: 'Deadly Stroke', types: ['combat'], reqText: 'Dazzling Display, Shatter Defenses, Weapon Focus, BAB +11',
    benefit: 'A hit against a stunned or flat-footed foe deals double damage plus 1 point of Constitution bleed.',
    prerequisites: { all: [{ feat: 'shatter-defenses' }, { bab: 11 }] } },
  { id: 'disruptive', name: 'Disruptive', types: ['combat'], reqText: 'Fighter 6',
    benefit: 'The DC to cast defensively rises by 4 for foes within your reach.', prerequisites: { classId: 'fighter' } },
  { id: 'blind-fight', name: 'Blind-Fight', types: ['combat'], reqText: '—',
    benefit: 'Reroll miss chances for concealment in melee, and take no penalty fighting invisible foes you can pinpoint.' },
  { id: 'catch-off-guard', name: 'Catch Off-Guard', types: ['combat'], reqText: '—',
    benefit: 'No penalty for using an improvised melee weapon; unarmed foes are flat-footed against it.' },

  // ---- Combat feats: critical mastery chain ----
  { id: 'critical-focus', name: 'Critical Focus', types: ['combat'], reqText: 'BAB +9',
    benefit: '+4 on attack rolls to confirm critical hits.', prerequisites: { bab: 9 } },
  { id: 'bleeding-critical', name: 'Bleeding Critical', types: ['combat'], reqText: 'Critical Focus, BAB +11',
    benefit: 'A critical hit also deals 2d6 bleed damage each round.',
    prerequisites: { all: [{ feat: 'critical-focus' }, { bab: 11 }] } },
  { id: 'sickening-critical', name: 'Sickening Critical', types: ['combat'], reqText: 'Critical Focus, BAB +11',
    benefit: 'A critical hit also leaves the target sickened for 1 minute.',
    prerequisites: { all: [{ feat: 'critical-focus' }, { bab: 11 }] } },
  { id: 'deafening-critical', name: 'Deafening Critical', types: ['combat'], reqText: 'Critical Focus, BAB +13',
    benefit: 'A critical hit deafens the target (Fortitude negates) permanently.',
    prerequisites: { all: [{ feat: 'critical-focus' }, { bab: 13 }] } },
  { id: 'staggering-critical', name: 'Staggering Critical', types: ['combat'], reqText: 'Critical Focus, BAB +13',
    benefit: 'A critical hit staggers the target for 1d4+1 rounds (Fortitude negates).',
    prerequisites: { all: [{ feat: 'critical-focus' }, { bab: 13 }] } },
  { id: 'tiring-critical', name: 'Tiring Critical', types: ['combat'], reqText: 'Critical Focus, BAB +13',
    benefit: 'A critical hit leaves the target fatigued.',
    prerequisites: { all: [{ feat: 'critical-focus' }, { bab: 13 }] } },
  { id: 'blinding-critical', name: 'Blinding Critical', types: ['combat'], reqText: 'Critical Focus, BAB +15',
    benefit: 'A critical hit blinds the target permanently (Fortitude reduces to dazzled).',
    prerequisites: { all: [{ feat: 'critical-focus' }, { bab: 15 }] } },
  { id: 'exhausting-critical', name: 'Exhausting Critical', types: ['combat'], reqText: 'Critical Focus, Tiring Critical, BAB +15',
    benefit: 'A critical hit leaves the target exhausted.',
    prerequisites: { all: [{ feat: 'tiring-critical' }, { bab: 15 }] } },
  { id: 'stunning-critical', name: 'Stunning Critical', types: ['combat'], reqText: 'Critical Focus, Staggering Critical, BAB +17',
    benefit: 'A critical hit stuns the target for 1d4 rounds (Fortitude negates).',
    prerequisites: { all: [{ feat: 'staggering-critical' }, { bab: 17 }] } },

  // ---- Combat feats: channel & arcane ----
  { id: 'arcane-strike', name: 'Arcane Strike', types: ['combat'], reqText: 'Ability to cast arcane spells',
    benefit: 'As a swift action, weapons deal +1 damage and count as magic; +1 more per five caster levels (max +5).' },
  { id: 'channel-smite', name: 'Channel Smite', types: ['combat'], reqText: 'Channel energy class feature',
    benefit: 'As a swift action before an attack, channel energy through the strike to deal it as bonus damage.' },
  { id: 'arcane-armor-training', name: 'Arcane Armor Training', types: ['combat'], reqText: 'Armor Proficiency (Light), caster level 3rd',
    benefit: 'As a swift action, reduce the arcane spell failure chance of your armor by 10%.',
    prerequisites: { all: [{ feat: 'armor-proficiency-light' }, { casterLevel: 3 }] } },
  { id: 'arcane-armor-mastery', name: 'Arcane Armor Mastery', types: ['combat'], reqText: 'Arcane Armor Training, Armor Proficiency (Medium), caster level 7th',
    benefit: 'As a swift action, reduce the arcane spell failure chance of your armor by 20%.',
    prerequisites: { all: [{ feat: 'arcane-armor-training' }, { feat: 'armor-proficiency-medium' }, { casterLevel: 7 }] } },

  // ---- General feats: improved defenses (one-time reroll, no static bonus) ----
  { id: 'improved-great-fortitude', name: 'Improved Great Fortitude', types: ['general'], reqText: 'Great Fortitude',
    benefit: 'Once per day, reroll a failed Fortitude save.', prerequisites: { feat: 'great-fortitude' } },
  { id: 'improved-iron-will', name: 'Improved Iron Will', types: ['general'], reqText: 'Iron Will',
    benefit: 'Once per day, reroll a failed Will save.', prerequisites: { feat: 'iron-will' } },
  { id: 'improved-lightning-reflexes', name: 'Improved Lightning Reflexes', types: ['general'], reqText: 'Lightning Reflexes',
    benefit: 'Once per day, reroll a failed Reflex save.', prerequisites: { feat: 'lightning-reflexes' } },

  // ---- General feats: skill ----
  { id: 'magical-aptitude', name: 'Magical Aptitude', types: ['general'], reqText: '—',
    benefit: '+2 on Spellcraft and Use Magic Device (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:spellcraft', type: 'untyped', value: 2, note: 'Magical Aptitude' }, { target: 'skill:use-magic-device', type: 'untyped', value: 2, note: 'Magical Aptitude' }] },
  { id: 'intimidating-prowess', name: 'Intimidating Prowess', types: ['combat'], reqText: '—',
    benefit: 'Add your Strength modifier to Intimidate checks in addition to your Charisma modifier.' },

  // ---- General feats: movement ----
  { id: 'fleet', name: 'Fleet', types: ['general'], reqText: '—',
    benefit: 'While wearing light or no armor, your base speed increases by 5 feet. May be taken more than once.' },

  // ---- General feats: channeling ----
  { id: 'selective-channeling', name: 'Selective Channeling', types: ['general'], reqText: 'Cha 13, channel energy class feature',
    benefit: 'Exclude a number of creatures up to your Charisma modifier from the area of your channel energy.',
    prerequisites: { ability: 'cha', gte: 13 } },
  { id: 'improved-channel', name: 'Improved Channel', types: ['general'], reqText: 'Channel energy class feature',
    benefit: '+2 to the DC of saves against your channel energy.' },
  { id: 'extra-channel', name: 'Extra Channel', types: ['general'], reqText: 'Channel energy class feature',
    benefit: 'Channel energy two additional times per day.' },
  { id: 'command-undead', name: 'Command Undead', types: ['general'], reqText: 'Channel negative energy class feature',
    benefit: 'Spend a channel to command undead (Will negates) rather than harm them.' },
  { id: 'turn-undead', name: 'Turn Undead', types: ['general'], reqText: 'Channel positive energy class feature',
    benefit: 'Spend a channel to make undead in the area flee (Will negates).' },
  { id: 'alignment-channel', name: 'Alignment Channel', types: ['general'], reqText: 'Channel energy class feature',
    benefit: 'Channel energy to harm or heal outsiders of a chosen alignment (good, evil, lawful, or chaotic) instead of undead.' },
  { id: 'elemental-channel', name: 'Elemental Channel', types: ['general'], reqText: 'Channel energy class feature',
    benefit: 'Channel energy to harm or heal elementals of a chosen subtype instead of undead.' },

  // ---- General feats: class-resource extras ----
  { id: 'extra-ki', name: 'Extra Ki', types: ['general'], reqText: 'Ki pool class feature',
    benefit: 'Your ki pool increases by 2.' },
  { id: 'extra-lay-on-hands', name: 'Extra Lay On Hands', types: ['general'], reqText: 'Lay on hands class feature',
    benefit: 'You can use lay on hands two additional times per day.' },
  { id: 'extra-mercy', name: 'Extra Mercy', types: ['general'], reqText: 'Lay on hands class feature, mercy class feature',
    benefit: 'Your lay on hands gains one additional mercy.' },
  { id: 'extra-performance', name: 'Extra Performance', types: ['general'], reqText: 'Bardic performance class feature',
    benefit: 'Use bardic performance for 6 additional rounds per day.' },
  { id: 'extra-rage', name: 'Extra Rage', types: ['general'], reqText: 'Rage class feature',
    benefit: 'You can rage for 6 additional rounds per day.' },

  // ---- General feats: leadership & item creation support ----
  { id: 'leadership', name: 'Leadership', types: ['general'], reqText: 'Character level 7th',
    benefit: 'Attract a loyal cohort and a number of followers determined by your Leadership score.' },
  { id: 'master-craftsman', name: 'Master Craftsman', types: ['general'], reqText: '5 ranks in a Craft or Profession skill',
    benefit: 'Use your chosen Craft or Profession skill to qualify for and craft magic items without spellcasting.' },
  { id: 'improved-counterspell', name: 'Improved Counterspell', types: ['general'], reqText: '—',
    benefit: 'Counterspell using any spell of the same school one level higher than the target spell.' },

  // ---- Spellcasting feats ----
  { id: 'natural-spell', name: 'Natural Spell', types: ['general'], reqText: 'Wis 13, wild shape class feature',
    benefit: 'Cast spells while using wild shape, substituting other actions for verbal and somatic components.',
    prerequisites: { ability: 'wis', gte: 13 } },
  { id: 'spell-mastery', name: 'Spell Mastery', types: ['general'], reqText: '1st-level wizard',
    benefit: 'Choose a number of spells equal to your Int modifier; you can prepare them without a spellbook.',
    prerequisites: { classId: 'wizard' } },
  { id: 'improved-familiar', name: 'Improved Familiar', types: ['general'], reqText: 'Ability to acquire a new familiar, compatible alignment, caster level 3rd+',
    benefit: 'Choose a more powerful creature (such as an imp or pseudodragon) as your familiar.' },
];

export const featById = new Map(FEATS.map((f) => [f.id, f]));
