import type { FeatDef } from './model';

// Core feats. prerequisites use the predicate DSL; effects fold into the stat graph.
export const FEATS: FeatDef[] = [
  { id: 'power-attack', name: 'Power Attack', types: ['combat'], reqText: 'Str 13, BAB +1',
    benefit: 'Take a −1 penalty on melee attack rolls to gain +2 on melee damage (+3 with a two-handed weapon). Penalty and bonus rise every +4 BAB.',
    prerequisites: { all: [{ ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'cleave', name: 'Cleave', types: ['combat'], reqText: 'Power Attack, Str 13, BAB +1',
    benefit: 'As a standard action, make a single melee attack; if it hits, make one more against an adjacent foe.',
    prerequisites: { all: [{ feat: 'power-attack' }, { ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'dodge', name: 'Dodge', types: ['combat'], reqText: 'Dex 13',
    benefit: '+1 dodge bonus to AC.', prerequisites: { ability: 'dex', gte: 13 },
    effects: [{ target: 'ac', type: 'dodge', value: 1, note: 'Dodge' }] },
  { id: 'mobility', name: 'Mobility', types: ['combat'], reqText: 'Dodge, Dex 13',
    benefit: '+4 dodge bonus to AC against attacks of opportunity provoked by movement.',
    prerequisites: { all: [{ feat: 'dodge' }, { ability: 'dex', gte: 13 }] } },
  { id: 'combat-expertise', name: 'Combat Expertise', types: ['combat'], reqText: 'Int 13',
    benefit: 'Take a penalty on attack rolls to gain a dodge bonus to AC.',
    prerequisites: { ability: 'int', gte: 13 } },
  { id: 'weapon-finesse', name: 'Weapon Finesse', types: ['combat'], reqText: '—',
    benefit: 'Use Dex modifier instead of Str on attack rolls with light melee weapons.' },
  { id: 'weapon-focus', name: 'Weapon Focus', types: ['combat'], reqText: 'Proficiency with weapon, BAB +1',
    benefit: '+1 bonus on attack rolls with the selected weapon.', prerequisites: { bab: 1 },
    param: { label: 'Weapon', options: ['Longsword', 'Greataxe', 'Longbow', 'Rapier', 'Dagger', 'Scimitar', 'Warhammer', 'Falchion'] } },
  { id: 'two-weapon-fighting', name: 'Two-Weapon Fighting', types: ['combat'], reqText: 'Dex 15',
    benefit: 'Reduce the penalties for fighting with two weapons.', prerequisites: { ability: 'dex', gte: 15 } },
  { id: 'point-blank-shot', name: 'Point-Blank Shot', types: ['combat'], reqText: '—',
    benefit: '+1 on attack and damage rolls with ranged weapons within 30 feet.' },
  { id: 'precise-shot', name: 'Precise Shot', types: ['combat'], reqText: 'Point-Blank Shot',
    benefit: 'No −4 penalty for shooting into melee.', prerequisites: { feat: 'point-blank-shot' } },
  { id: 'rapid-shot', name: 'Rapid Shot', types: ['combat'], reqText: 'Point-Blank Shot, Dex 13',
    benefit: 'Make one extra ranged attack each round at a −2 penalty to all.',
    prerequisites: { all: [{ feat: 'point-blank-shot' }, { ability: 'dex', gte: 13 }] } },
  { id: 'improved-initiative', name: 'Improved Initiative', types: ['combat'], reqText: '—',
    benefit: '+4 bonus on initiative checks.', effects: [{ target: 'init', type: 'untyped', value: 4, note: 'Improved Initiative' }] },
  { id: 'toughness', name: 'Toughness', types: ['general'], reqText: '—',
    benefit: '+3 hit points, plus 1 more per Hit Die beyond 3rd.', effects: [{ target: 'hp:max', type: 'untyped', value: 3, note: 'Toughness' }] },
  { id: 'iron-will', name: 'Iron Will', types: ['general'], reqText: '—',
    benefit: '+2 bonus on Will saves.', effects: [{ target: 'save:will', type: 'untyped', value: 2, note: 'Iron Will' }] },
  { id: 'lightning-reflexes', name: 'Lightning Reflexes', types: ['general'], reqText: '—',
    benefit: '+2 bonus on Reflex saves.', effects: [{ target: 'save:ref', type: 'untyped', value: 2, note: 'Lightning Reflexes' }] },
  { id: 'great-fortitude', name: 'Great Fortitude', types: ['general'], reqText: '—',
    benefit: '+2 bonus on Fortitude saves.', effects: [{ target: 'save:fort', type: 'untyped', value: 2, note: 'Great Fortitude' }] },
  { id: 'skill-focus', name: 'Skill Focus', types: ['general'], reqText: '—',
    benefit: '+3 bonus on the chosen skill (+6 at 10 ranks).',
    param: { label: 'Skill', options: ['Perception', 'Stealth', 'Diplomacy', 'Spellcraft', 'Acrobatics', 'Intimidate', 'Sense Motive', 'Knowledge (arcana)'] } },
  { id: 'combat-casting', name: 'Combat Casting', types: ['general'], reqText: '—',
    benefit: '+4 bonus on concentration checks made to cast defensively.' },
  { id: 'spell-focus', name: 'Spell Focus', types: ['general'], reqText: 'Ability to cast spells',
    benefit: '+1 to the DC of saving throws against spells of the chosen school.',
    param: { label: 'School', options: ['Evocation', 'Conjuration', 'Enchantment', 'Illusion', 'Necromancy', 'Transmutation', 'Abjuration', 'Divination'] } },
  { id: 'improved-unarmed-strike', name: 'Improved Unarmed Strike', types: ['combat'], reqText: '—',
    benefit: 'Deal lethal damage with unarmed strikes and are always considered armed.' },
  { id: 'weapon-specialization', name: 'Weapon Specialization', types: ['combat'], reqText: 'Weapon Focus, Fighter 4',
    benefit: '+2 bonus on damage rolls with the selected weapon.',
    prerequisites: { all: [{ feat: 'weapon-focus' }, { classId: 'fighter' }] } },
];

export const featById = new Map(FEATS.map((f) => [f.id, f]));
