import type { FeatDef } from './model';
import { WEAPONS } from './equipment';
import { SKILLS } from './skills';

// Parameter option lists are derived from the catalogues rather than hand-listed, so a feat like
// Weapon Focus offers every weapon we know about instead of a frozen subset of eight. Each option
// keeps the catalogue id so the engine can match the pick to a weapon/skill without string-matching.
const byName = (a: { name: string }, b: { name: string }) => a.name.localeCompare(b.name);
const WEAPON_OPTIONS = WEAPONS.map((w) => ({ id: w.id, name: w.name })).sort(byName);
// Exotic Weapon Proficiency names one exotic weapon — except for firearms, where the single pick
// "firearms" grants the whole group at once. That option carries the group id, not a weapon id.
export const FIREARM_GROUP_ID = 'firearms';
const EXOTIC_WEAPON_OPTIONS = [
  // Named for how the feat reads on the sheet — "Exotic Weapon Proficiency (Firearms)".
  { id: FIREARM_GROUP_ID, name: 'Firearms' },
  ...WEAPONS.filter((w) => w.group === 'exotic').map((w) => ({ id: w.id, name: w.name })).sort(byName),
];
const SKILL_OPTIONS = SKILLS.map((s) => ({ id: s.id, name: s.name })).sort(byName);
const CROSSBOW_OPTIONS = WEAPONS.filter((w) => w.id.includes('crossbow')).map((w) => ({ id: w.id, name: w.name }));
const SCHOOL_OPTIONS = ['Abjuration', 'Conjuration', 'Divination', 'Enchantment', 'Evocation', 'Illusion', 'Necromancy', 'Transmutation']
  .map((n) => ({ id: n.toLowerCase(), name: n }));

// Core feats. prerequisites use the predicate DSL; effects fold into the stat graph.
export const FEATS: FeatDef[] = [
  { id: 'power-attack', name: 'Power Attack', types: ['combat'], reqText: 'Str 13, BAB +1',
    benefit: 'Take a −1 penalty on melee attack rolls to gain +2 on melee damage (+3 with a two-handed weapon). Penalty and bonus rise every +4 BAB.',
    prerequisites: { all: [{ ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'cleave', name: 'Cleave', types: ['combat'], reqText: 'Power Attack, Str 13, BAB +1',
    benefit: 'As a standard action, make a single melee attack; if it hits, make one more against an adjacent foe.',
    prerequisites: { all: [{ feat: 'power-attack' }, { ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'dodge', name: 'Dodge', types: ['combat'], reqText: 'Dex 13',
    benefit: '+1 dodge bonus to AC.', prerequisites: { ability: 'dex', gte: 13 },
    effects: [{ target: 'ac', type: 'dodge', value: 1, note: 'Dodge' }] },
  { id: 'mobility', name: 'Mobility', types: ['combat'], reqText: 'Dodge, Dex 13',
    benefit: '+4 dodge bonus to AC against attacks of opportunity provoked by movement.',
    prerequisites: { all: [{ feat: 'dodge' }, { ability: 'dex', gte: 13 }] } },
  { id: 'combat-expertise', name: 'Combat Expertise', types: ['combat'], reqText: 'Int 13',
    benefit: 'Take a penalty on attack rolls to gain a dodge bonus to AC.',
    prerequisites: { ability: 'int', gte: 13 } },
  { id: 'weapon-finesse', name: 'Weapon Finesse', types: ['combat'], reqText: '—',
    benefit: 'Use Dex modifier instead of Str on attack rolls with light melee weapons.' },
  { id: 'weapon-focus', name: 'Weapon Focus', types: ['combat'], reqText: 'Proficiency with weapon, BAB +1',
    benefit: '+1 bonus on attack rolls with the selected weapon.', prerequisites: { bab: 1 },
    param: { label: 'Weapon', options: WEAPON_OPTIONS } },
  { id: 'exotic-weapon-proficiency', name: 'Exotic Weapon Proficiency', types: ['combat'], reqText: 'BAB +1',
    benefit: 'You make attacks with the selected exotic weapon normally, without the −4 non-proficiency penalty. Choosing firearms grants proficiency with every firearm at once.',
    prerequisites: { bab: 1 }, param: { label: 'Weapon', options: EXOTIC_WEAPON_OPTIONS } },
  { id: 'gunsmithing', name: 'Gunsmithing', types: ['general'], reqText: '—',
    benefit: "With a gunsmith's kit you can craft and repair firearms, craft bullets and cartridges, and mix black powder without a Craft check. An hour's work each day restores one broken firearm." },
  { id: 'two-weapon-fighting', name: 'Two-Weapon Fighting', types: ['combat'], reqText: 'Dex 15',
    benefit: 'Reduce the penalties for fighting with two weapons.', prerequisites: { ability: 'dex', gte: 15 } },
  { id: 'point-blank-shot', name: 'Point-Blank Shot', types: ['combat'], reqText: '—',
    benefit: '+1 on attack and damage rolls with ranged weapons within 30 feet.' },
  { id: 'precise-shot', name: 'Precise Shot', types: ['combat'], reqText: 'Point-Blank Shot',
    benefit: 'No −4 penalty for shooting into melee.', prerequisites: { feat: 'point-blank-shot' } },
  { id: 'rapid-shot', name: 'Rapid Shot', types: ['combat'], reqText: 'Point-Blank Shot, Dex 13',
    benefit: 'Make one extra ranged attack each round at a −2 penalty to all.',
    prerequisites: { all: [{ feat: 'point-blank-shot' }, { ability: 'dex', gte: 13 }] } },
  { id: 'improved-initiative', name: 'Improved Initiative', types: ['combat'], reqText: '—',
    benefit: '+4 bonus on initiative checks.', effects: [{ target: 'init', type: 'untyped', value: 4, note: 'Improved Initiative' }] },
  { id: 'toughness', name: 'Toughness', types: ['general'], reqText: '—',
    benefit: '+3 hit points, plus 1 more per Hit Die beyond 3rd.', effects: [{ target: 'hp:max', type: 'untyped', value: 3, note: 'Toughness' }] },
  { id: 'iron-will', name: 'Iron Will', types: ['general'], reqText: '—',
    benefit: '+2 bonus on Will saves.', effects: [{ target: 'save:will', type: 'untyped', value: 2, note: 'Iron Will' }] },
  { id: 'lightning-reflexes', name: 'Lightning Reflexes', types: ['general'], reqText: '—',
    benefit: '+2 bonus on Reflex saves.', effects: [{ target: 'save:ref', type: 'untyped', value: 2, note: 'Lightning Reflexes' }] },
  { id: 'great-fortitude', name: 'Great Fortitude', types: ['general'], reqText: '—',
    benefit: '+2 bonus on Fortitude saves.', effects: [{ target: 'save:fort', type: 'untyped', value: 2, note: 'Great Fortitude' }] },
  { id: 'skill-focus', name: 'Skill Focus', types: ['general'], reqText: '—',
    benefit: '+3 bonus on the chosen skill (+6 at 10 ranks).',
    param: { label: 'Skill', options: SKILL_OPTIONS } },
  { id: 'combat-casting', name: 'Combat Casting', types: ['general'], reqText: '—',
    benefit: '+4 bonus on concentration checks made to cast defensively.' },
  { id: 'spell-focus', name: 'Spell Focus', types: ['general'], reqText: 'Ability to cast spells',
    benefit: '+1 to the DC of saving throws against spells of the chosen school.',
    param: { label: 'School', options: SCHOOL_OPTIONS } },
  { id: 'improved-unarmed-strike', name: 'Improved Unarmed Strike', types: ['combat'], reqText: '—',
    benefit: 'Deal lethal damage with unarmed strikes and are always considered armed.' },
  { id: 'throw-anything', name: 'Throw Anything', types: ['combat'], reqText: '—',
    benefit: 'No penalty for using an improvised ranged weapon, and +1 circumstance bonus on attack rolls with thrown splash weapons.' },
  { id: 'weapon-specialization', name: 'Weapon Specialization', types: ['combat'], reqText: 'Weapon Focus, Fighter 4',
    benefit: '+2 bonus on damage rolls with the selected weapon.',
    prerequisites: { all: [{ feat: 'weapon-focus' }, { classId: 'fighter' }] } },
  { id: 'greater-weapon-focus', name: 'Greater Weapon Focus', types: ['combat'], reqText: 'Weapon Focus, Fighter 8',
    benefit: '+1 more on attack rolls with the selected weapon (stacks with Weapon Focus).',
    prerequisites: { all: [{ feat: 'weapon-focus' }, { classId: 'fighter' }] },
    param: { label: 'Weapon', options: WEAPON_OPTIONS } },
  { id: 'greater-weapon-specialization', name: 'Greater Weapon Specialization', types: ['combat'], reqText: 'Weapon Specialization, Fighter 12',
    benefit: '+2 more on damage rolls with the selected weapon (stacks with Weapon Specialization).',
    prerequisites: { all: [{ feat: 'weapon-specialization' }, { classId: 'fighter' }] } },

  // ---- Combat feats (situational; no static stat effect) ----
  { id: 'great-cleave', name: 'Great Cleave', types: ['combat'], reqText: 'Cleave, Str 13, BAB +4',
    benefit: 'As Cleave, but keep making attacks as long as you hit fresh adjacent foes.',
    prerequisites: { all: [{ feat: 'cleave' }, { ability: 'str', gte: 13 }, { bab: 4 }] } },
  { id: 'combat-reflexes', name: 'Combat Reflexes', types: ['combat'], reqText: '—',
    benefit: 'Make a number of extra attacks of opportunity per round equal to your Dex modifier, even when flat-footed.' },
  { id: 'deadly-aim', name: 'Deadly Aim', types: ['combat'], reqText: 'Dex 13, BAB +1',
    benefit: 'Take a −1 penalty on ranged attacks to gain +2 on ranged damage; scales every +4 BAB.',
    prerequisites: { all: [{ ability: 'dex', gte: 13 }, { bab: 1 }] } },
  { id: 'deflect-arrows', name: 'Deflect Arrows', types: ['combat'], reqText: 'Improved Unarmed Strike, Dex 13',
    benefit: 'Once per round, deflect one ranged attack that would hit you.',
    prerequisites: { all: [{ feat: 'improved-unarmed-strike' }, { ability: 'dex', gte: 13 }] } },
  { id: 'improved-bull-rush', name: 'Improved Bull Rush', types: ['combat'], reqText: 'Power Attack, Str 13, BAB +1',
    benefit: 'No attack of opportunity when bull rushing, and +2 on the check.',
    prerequisites: { all: [{ feat: 'power-attack' }, { ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'improved-disarm', name: 'Improved Disarm', types: ['combat'], reqText: 'Combat Expertise, Int 13',
    benefit: 'No attack of opportunity when disarming, and +2 on the check.',
    prerequisites: { all: [{ feat: 'combat-expertise' }, { ability: 'int', gte: 13 }] } },
  { id: 'improved-feint', name: 'Improved Feint', types: ['combat'], reqText: 'Combat Expertise, Int 13',
    benefit: 'Feint in combat as a move action instead of a standard action.',
    prerequisites: { all: [{ feat: 'combat-expertise' }, { ability: 'int', gte: 13 }] } },
  { id: 'improved-grapple', name: 'Improved Grapple', types: ['combat'], reqText: 'Improved Unarmed Strike, Dex 13',
    benefit: 'No attack of opportunity when grappling, and +2 on the check.',
    prerequisites: { all: [{ feat: 'improved-unarmed-strike' }, { ability: 'dex', gte: 13 }] } },
  { id: 'improved-overrun', name: 'Improved Overrun', types: ['combat'], reqText: 'Power Attack, Str 13, BAB +1',
    benefit: 'No attack of opportunity when overrunning; targets cannot avoid you, and +2 on the check.',
    prerequisites: { all: [{ feat: 'power-attack' }, { ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'improved-sunder', name: 'Improved Sunder', types: ['combat'], reqText: 'Power Attack, Str 13, BAB +1',
    benefit: 'No attack of opportunity when sundering, and +2 on the check.',
    prerequisites: { all: [{ feat: 'power-attack' }, { ability: 'str', gte: 13 }, { bab: 1 }] } },
  { id: 'improved-trip', name: 'Improved Trip', types: ['combat'], reqText: 'Combat Expertise, Int 13',
    benefit: 'No attack of opportunity when tripping, and +2 on the check.',
    prerequisites: { all: [{ feat: 'combat-expertise' }, { ability: 'int', gte: 13 }] } },
  { id: 'improved-two-weapon-fighting', name: 'Improved Two-Weapon Fighting', types: ['combat'], reqText: 'Two-Weapon Fighting, Dex 15, BAB +6',
    benefit: 'Gain a second off-hand attack at a −5 penalty.',
    prerequisites: { all: [{ feat: 'two-weapon-fighting' }, { ability: 'dex', gte: 15 }, { bab: 6 }] } },
  { id: 'greater-two-weapon-fighting', name: 'Greater Two-Weapon Fighting', types: ['combat'], reqText: 'Improved Two-Weapon Fighting, Dex 19, BAB +11',
    benefit: 'Gain a third off-hand attack at a −10 penalty.',
    prerequisites: { all: [{ feat: 'improved-two-weapon-fighting' }, { ability: 'dex', gte: 19 }, { bab: 11 }] } },
  { id: 'two-weapon-defense', name: 'Two-Weapon Defense', types: ['combat'], reqText: 'Two-Weapon Fighting, Dex 15',
    benefit: '+1 shield bonus to AC while wielding two weapons (+2 when fighting defensively).',
    prerequisites: { all: [{ feat: 'two-weapon-fighting' }, { ability: 'dex', gte: 15 }] } },
  { id: 'improved-precise-shot', name: 'Improved Precise Shot', types: ['combat'], reqText: 'Precise Shot, Dex 19, BAB +11',
    benefit: 'Ignore concealment (not total) and cover (not total) with ranged attacks.',
    prerequisites: { all: [{ feat: 'precise-shot' }, { ability: 'dex', gte: 19 }, { bab: 11 }] } },
  { id: 'manyshot', name: 'Manyshot', types: ['combat'], reqText: 'Rapid Shot, Dex 17, BAB +6',
    benefit: 'Fire two arrows with the first ranged attack of a full attack.',
    prerequisites: { all: [{ feat: 'rapid-shot' }, { ability: 'dex', gte: 17 }, { bab: 6 }] } },
  { id: 'mounted-combat', name: 'Mounted Combat', types: ['combat'], reqText: 'Ride 1 rank',
    benefit: 'Once per round, negate a hit against your mount with a Ride check.',
    prerequisites: { skillRanks: { skill: 'ride', gte: 1 } } },
  { id: 'rapid-reload', name: 'Rapid Reload', types: ['combat'], reqText: 'Weapon Proficiency (crossbow)',
    benefit: 'Reload the chosen crossbow more quickly (free or move action).',
    param: { label: 'Crossbow', options: CROSSBOW_OPTIONS } },
  { id: 'spring-attack', name: 'Spring Attack', types: ['combat'], reqText: 'Dodge, Mobility, Dex 13, BAB +4',
    benefit: 'Move before and after a melee attack without provoking from the target.',
    prerequisites: { all: [{ feat: 'dodge' }, { feat: 'mobility' }, { ability: 'dex', gte: 13 }, { bab: 4 }] } },
  { id: 'whirlwind-attack', name: 'Whirlwind Attack', types: ['combat'], reqText: 'Combat Expertise, Spring Attack, Int 13, Dex 13, BAB +4',
    benefit: 'As a full-round action, make one melee attack against every foe in reach.',
    prerequisites: { all: [{ feat: 'combat-expertise' }, { feat: 'spring-attack' }, { ability: 'int', gte: 13 }, { ability: 'dex', gte: 13 }, { bab: 4 }] } },
  { id: 'vital-strike', name: 'Vital Strike', types: ['combat'], reqText: 'BAB +6',
    benefit: 'On a single attack, roll weapon damage dice twice.', prerequisites: { bab: 6 } },
  { id: 'improved-vital-strike', name: 'Improved Vital Strike', types: ['combat'], reqText: 'Vital Strike, BAB +11',
    benefit: 'On a single attack, roll weapon damage dice three times.',
    prerequisites: { all: [{ feat: 'vital-strike' }, { bab: 11 }] } },
  { id: 'greater-vital-strike', name: 'Greater Vital Strike', types: ['combat'], reqText: 'Improved Vital Strike, BAB +16',
    benefit: 'On a single attack, roll weapon damage dice four times.',
    prerequisites: { all: [{ feat: 'improved-vital-strike' }, { bab: 16 }] } },
  { id: 'stunning-fist', name: 'Stunning Fist', types: ['combat'], reqText: 'Dex 13, Wis 13, Improved Unarmed Strike, BAB +8',
    benefit: 'Force a struck foe to save or be stunned; usable once per four levels per day.',
    prerequisites: { all: [{ ability: 'dex', gte: 13 }, { ability: 'wis', gte: 13 }, { feat: 'improved-unarmed-strike' }, { bab: 8 }] } },

  // ---- General feats ----
  { id: 'alertness', name: 'Alertness', types: ['general'], reqText: '—',
    benefit: '+2 on Perception and Sense Motive (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:perception', type: 'untyped', value: 2, note: 'Alertness' }, { target: 'skill:sense-motive', type: 'untyped', value: 2, note: 'Alertness' }] },
  { id: 'acrobatic', name: 'Acrobatic', types: ['general'], reqText: '—',
    benefit: '+2 on Acrobatics and Fly (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:acrobatics', type: 'untyped', value: 2, note: 'Acrobatic' }, { target: 'skill:fly', type: 'untyped', value: 2, note: 'Acrobatic' }] },
  { id: 'athletic', name: 'Athletic', types: ['general'], reqText: '—',
    benefit: '+2 on Climb and Swim (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:climb', type: 'untyped', value: 2, note: 'Athletic' }, { target: 'skill:swim', type: 'untyped', value: 2, note: 'Athletic' }] },
  { id: 'deceitful', name: 'Deceitful', types: ['general'], reqText: '—',
    benefit: '+2 on Bluff and Disguise (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:bluff', type: 'untyped', value: 2, note: 'Deceitful' }, { target: 'skill:disguise', type: 'untyped', value: 2, note: 'Deceitful' }] },
  { id: 'deft-hands', name: 'Deft Hands', types: ['general'], reqText: '—',
    benefit: '+2 on Disable Device and Sleight of Hand (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:disable-device', type: 'untyped', value: 2, note: 'Deft Hands' }, { target: 'skill:sleight-of-hand', type: 'untyped', value: 2, note: 'Deft Hands' }] },
  { id: 'persuasive', name: 'Persuasive', types: ['general'], reqText: '—',
    benefit: '+2 on Diplomacy and Intimidate (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:diplomacy', type: 'untyped', value: 2, note: 'Persuasive' }, { target: 'skill:intimidate', type: 'untyped', value: 2, note: 'Persuasive' }] },
  { id: 'self-sufficient', name: 'Self-Sufficient', types: ['general'], reqText: '—',
    benefit: '+2 on Heal and Survival (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:heal', type: 'untyped', value: 2, note: 'Self-Sufficient' }, { target: 'skill:survival', type: 'untyped', value: 2, note: 'Self-Sufficient' }] },
  { id: 'stealthy', name: 'Stealthy', types: ['general'], reqText: '—',
    benefit: '+2 on Escape Artist and Stealth (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:escape-artist', type: 'untyped', value: 2, note: 'Stealthy' }, { target: 'skill:stealth', type: 'untyped', value: 2, note: 'Stealthy' }] },
  { id: 'animal-affinity', name: 'Animal Affinity', types: ['general'], reqText: '—',
    benefit: '+2 on Handle Animal and Ride (+4 at 10 ranks in each).',
    effects: [{ target: 'skill:handle-animal', type: 'untyped', value: 2, note: 'Animal Affinity' }, { target: 'skill:ride', type: 'untyped', value: 2, note: 'Animal Affinity' }] },
  { id: 'endurance', name: 'Endurance', types: ['general'], reqText: '—',
    benefit: '+4 on checks to resist exhaustion, and sleep in medium/light armor without fatigue.' },
  { id: 'diehard', name: 'Diehard', types: ['general'], reqText: 'Endurance',
    benefit: 'Remain conscious and staggered below 0 hit points instead of dying.', prerequisites: { feat: 'endurance' } },
  { id: 'run', name: 'Run', types: ['general'], reqText: '—',
    benefit: 'Run at 5× speed (4× in armor) and gain +4 on running Acrobatics jumps.' },

  // ---- Spellcasting feats ----
  { id: 'greater-spell-focus', name: 'Greater Spell Focus', types: ['general'], reqText: 'Spell Focus',
    benefit: '+1 more to save DCs of the chosen school (stacks with Spell Focus).',
    prerequisites: { feat: 'spell-focus' },
    param: { label: 'School', options: SCHOOL_OPTIONS } },
  { id: 'spell-penetration', name: 'Spell Penetration', types: ['general'], reqText: '—',
    benefit: '+2 on caster level checks to overcome spell resistance.' },
  { id: 'greater-spell-penetration', name: 'Greater Spell Penetration', types: ['general'], reqText: 'Spell Penetration',
    benefit: '+2 more on caster level checks to overcome spell resistance.', prerequisites: { feat: 'spell-penetration' } },
  { id: 'augment-summoning', name: 'Augment Summoning', types: ['general'], reqText: 'Spell Focus (conjuration)',
    benefit: 'Summoned creatures gain +4 Strength and Constitution.', prerequisites: { feat: 'spell-focus' } },
  { id: 'eschew-materials', name: 'Eschew Materials', types: ['general'], reqText: '—',
    benefit: 'Cast spells without material components costing 1 gp or less.' },

  // ---- Metamagic feats ----
  { id: 'empower-spell', name: 'Empower Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Increase a spell\'s variable numeric effects by half (+2 spell levels).' },
  { id: 'extend-spell', name: 'Extend Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Double a spell\'s duration (+1 spell level).' },
  { id: 'maximize-spell', name: 'Maximize Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Maximize a spell\'s variable numeric effects (+3 spell levels).' },
  { id: 'quicken-spell', name: 'Quicken Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Cast a spell as a swift action (+4 spell levels).' },
  { id: 'silent-spell', name: 'Silent Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Cast a spell without verbal components (+1 spell level).' },
  { id: 'still-spell', name: 'Still Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Cast a spell without somatic components (+1 spell level).' },
  { id: 'widen-spell', name: 'Widen Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Double the area of a burst, emanation, line, or spread (+3 spell levels).' },
  { id: 'heighten-spell', name: 'Heighten Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Cast a spell at a higher effective spell level for a higher save DC.' },
  { id: 'enlarge-spell', name: 'Enlarge Spell', types: ['metamagic'], reqText: '—',
    benefit: 'Double a spell\'s range (+1 spell level).' },

  // ---- Item creation feats ----
  { id: 'scribe-scroll', name: 'Scribe Scroll', types: ['item-creation'], reqText: 'Caster level 1',
    benefit: 'Create magic scrolls.', prerequisites: { casterLevel: 1 } },
  { id: 'brew-potion', name: 'Brew Potion', types: ['item-creation'], reqText: 'Caster level 3',
    benefit: 'Create potions of spells you can cast (3rd level or lower).', prerequisites: { casterLevel: 3 } },
  { id: 'craft-wand', name: 'Craft Wand', types: ['item-creation'], reqText: 'Caster level 5',
    benefit: 'Create wands of spells you know (4th level or lower).', prerequisites: { casterLevel: 5 } },
  { id: 'craft-wondrous-item', name: 'Craft Wondrous Item', types: ['item-creation'], reqText: 'Caster level 3',
    benefit: 'Create a wide range of magic wondrous items.', prerequisites: { casterLevel: 3 } },
  { id: 'craft-magic-arms-and-armor', name: 'Craft Magic Arms and Armor', types: ['item-creation'], reqText: 'Caster level 5',
    benefit: 'Create and enhance magic weapons, armor, and shields.', prerequisites: { casterLevel: 5 } },
  { id: 'forge-ring', name: 'Forge Ring', types: ['item-creation'], reqText: 'Caster level 7',
    benefit: 'Create magic rings.', prerequisites: { casterLevel: 7 } },
  { id: 'craft-rod', name: 'Craft Rod', types: ['item-creation'], reqText: 'Caster level 9',
    benefit: 'Create magic rods.', prerequisites: { casterLevel: 9 } },
  { id: 'craft-staff', name: 'Craft Staff', types: ['item-creation'], reqText: 'Caster level 11',
    benefit: 'Create magic staves.', prerequisites: { casterLevel: 11 } },
];

export const featById = new Map(FEATS.map((f) => [f.id, f]));
