import type { Ability } from '../engine/types';
import type { HeritageDef, RaceDef } from './model';

// Featured races (Advanced Race Guide). Stat blocks verified against d20pfsrd. Skill/save/stat
// bonuses fold in as effects; darkvision, resistances, and spell-like abilities are descriptive
// traits (the engine doesn't compute SLAs). Aasimar and tiefling carry their full variant-heritage
// tables (ARG / Blood of Angels / Blood of Fiends), each swapping the ability spread, the 1/day SLA
// and the two skill bonuses — verified against d20pfsrd.

/** Build a variant-heritage entry. `skills` are the two skill ids the heritage grants +2 to, in
 *  place of the race's default Skilled pair; `sla` is the 1/day spell-like ability that replaces the
 *  race's default. */
function heritage(id: string, name: string, mods: Partial<Record<Ability, number>>, skills: [string, string], sla: string, desc: string): HeritageDef {
  return {
    id, name, abilityMods: mods, spellLikeAbility: { name: sla, uses: 1 }, desc,
    effects: skills.map((s) => ({ target: `skill:${s}`, type: 'racial' as const, value: 2, note: `${name} heritage` })),
  };
}

export const FEATURED_RACES: RaceDef[] = [
  {
    id: 'aasimar', name: 'Aasimar', sub: '+2 Wis, +2 Cha',
    desc: 'Mortals touched by celestial power, aasimars are marked by radiant beauty and an innate pull toward good.',
    size: 'medium', speed: 30, abilityMods: { wis: 2, cha: 2 },
    traits: [
      { id: 'aasimar-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'aasimar-resistance', name: 'Celestial Resistance', desc: 'Acid, cold, and electricity resistance 5.',
        energyResistance: [{ type: 'acid', amount: 5 }, { type: 'cold', amount: 5 }, { type: 'electricity', amount: 5 }] },
      { id: 'aasimar-skilled', name: 'Skilled', desc: '+2 racial bonus on Diplomacy and Perception checks.', effects: [{ target: 'skill:diplomacy', type: 'racial', value: 2, note: 'Skilled (Aasimar)' }, { target: 'skill:perception', type: 'racial', value: 2, note: 'Skilled (Aasimar)' }] },
      { id: 'aasimar-sla', name: 'Spell-Like Ability', desc: 'Use daylight once per day (caster level equals class level).', spellLikeAbilities: [{ name: 'Daylight', uses: 1, note: 'CL = character level' }] },
    ],
    altTraits: [],
    heritageReplaces: ['aasimar-skilled', 'aasimar-sla'],
    heritages: [
      heritage('idyllkin', 'Agathion-Blooded (Idyllkin)', { con: 2, cha: 2 }, ['handle-animal', 'survival'], "Summon Nature's Ally II", 'Bestial and calm, idyllkin often mediate between lawful and chaotic agents of good.'),
      heritage('angelkin', 'Angel-Blooded (Angelkin)', { str: 2, cha: 2 }, ['heal', 'know-planes'], 'Alter Self', 'Mortal paragons of beauty who serve as exemplars of good and light.'),
      heritage('lawbringer', 'Archon-Blooded (Lawbringer)', { con: 2, wis: 2 }, ['intimidate', 'sense-motive'], 'Continual Flame', 'Champions of justice who dole out punishment to the wicked.'),
      heritage('musetouched', 'Azata-Blooded (Musetouched)', { dex: 2, cha: 2 }, ['diplomacy', 'perform-oratory'], 'Glitterdust', 'Free spirits who travel the world to liberate the less fortunate.'),
      heritage('plumekith', 'Garuda-Blooded (Plumekith)', { dex: 2, wis: 2 }, ['acrobatics', 'fly'], 'See Invisibility', 'Avian-featured aasimars who never shirk a commitment once made.'),
      heritage('emberkin', 'Peri-Blooded (Emberkin)', { int: 2, cha: 2 }, ['know-planes', 'spellcraft'], 'Pyrotechnics', 'Masters of fire magic, torn between the pull of good and evil.'),
    ],
    languagesAuto: ['common', 'celestial'],
    languagesBonus: ['draconic', 'dwarven', 'elven', 'gnome', 'halfling', 'sylvan'],
  },
  {
    id: 'catfolk', name: 'Catfolk', sub: '+2 Dex, +2 Cha, −2 Wis',
    desc: 'Curious, graceful feline humanoids with an easy charm and a hunter’s instincts.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, cha: 2, wis: -2 },
    traits: [
      { id: 'catfolk-low-light', name: 'Low-Light Vision', desc: 'See twice as far as humans in dim light.', senses: ['Low-light vision'] },
      { id: 'catfolk-luck', name: "Cat's Luck", desc: 'Once per day, roll a Reflex save twice and take the better result (declared before rolling).' },
      { id: 'catfolk-hunter', name: 'Natural Hunter', desc: '+2 racial bonus on Perception, Stealth, and Survival checks.', effects: [{ target: 'skill:perception', type: 'racial', value: 2, note: 'Natural Hunter' }, { target: 'skill:stealth', type: 'racial', value: 2, note: 'Natural Hunter' }, { target: 'skill:survival', type: 'racial', value: 2, note: 'Natural Hunter' }] },
      { id: 'catfolk-sprinter', name: 'Sprinter', desc: '+10 ft to speed when charging, running, or withdrawing.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'catfolk'],
    languagesBonus: ['elven', 'gnoll', 'gnome', 'goblin', 'halfling', 'orc', 'sylvan'],
  },
  {
    id: 'dhampir', name: 'Dhampir', sub: '+2 Dex, +2 Cha, −2 Con',
    desc: 'The living children of vampires — pale, alluring, and sustained by negative energy.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, cha: 2, con: -2 },
    traits: [
      { id: 'dhampir-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet (plus low-light vision).', senses: ['Darkvision 60 ft', 'Low-light vision'] },
      { id: 'dhampir-undead-resist', name: 'Undead Resistance', desc: '+2 racial bonus on saves against disease and mind-affecting effects.', effects: [{ target: 'save:all', type: 'racial', value: 2, note: 'Undead Resistance', condition: 'vs disease and mind-affecting' }] },
      { id: 'dhampir-resist-drain', name: 'Resist Level Drain', desc: 'Take no penalties from energy drain; negative levels clear automatically after 24 hours.' },
      { id: 'dhampir-manipulative', name: 'Manipulative', desc: '+2 racial bonus on Bluff and Perception checks.', effects: [{ target: 'skill:bluff', type: 'racial', value: 2, note: 'Manipulative' }, { target: 'skill:perception', type: 'racial', value: 2, note: 'Manipulative' }] },
      { id: 'dhampir-sla', name: 'Spell-Like Ability', desc: 'Use detect undead three times per day.', spellLikeAbilities: [{ name: 'Detect Undead', uses: 3 }] },
      { id: 'dhampir-light-sens', name: 'Light Sensitivity', desc: 'Dazzled in bright light.' },
      { id: 'dhampir-neg-affinity', name: 'Negative Energy Affinity', desc: 'Healed by negative energy and harmed by positive energy, as though undead.' },
    ],
    altTraits: [],
    languagesAuto: ['common'],
    languagesBonus: ['abyssal', 'aklo', 'dwarven', 'elven', 'halfling', 'infernal'],
  },
  {
    id: 'drow', name: 'Drow', sub: '+2 Dex, +2 Cha, −2 Con',
    desc: 'The dark elves of the deep — beautiful, cruel, and steeped in the intrigues of the underworld.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, cha: 2, con: -2 },
    traits: [
      { id: 'drow-darkvision', name: 'Superior Darkvision', desc: 'See in the dark up to 120 feet.', senses: ['Darkvision 120 ft'] },
      { id: 'drow-immunities', name: 'Drow Immunities', desc: 'Immune to magic sleep; +2 racial bonus on saves against enchantment.', effects: [{ target: 'save:all', type: 'racial', value: 2, note: 'Drow Immunities', condition: 'vs enchantment' }] },
      { id: 'drow-keen-senses', name: 'Keen Senses', desc: '+2 racial bonus on Perception checks.', effects: [{ target: 'skill:perception', type: 'racial', value: 2, note: 'Keen Senses (Drow)' }] },
      { id: 'drow-sr', name: 'Spell Resistance', desc: 'Spell resistance equal to 6 + total class levels.' },
      { id: 'drow-light-blind', name: 'Light Blindness', desc: 'Blinded for 1 round by sudden bright light, then dazzled while it persists.' },
      { id: 'drow-poison-use', name: 'Poison Use', desc: 'Never risk poisoning yourself when applying poison.' },
      { id: 'drow-weapons', name: 'Weapon Familiarity', desc: 'Proficient with hand crossbows, rapiers, and short swords.' },
      { id: 'drow-sla', name: 'Spell-Like Abilities', desc: 'Dancing lights, darkness, and faerie fire once each per day.', spellLikeAbilities: [{ name: 'Dancing Lights', uses: 1 }, { name: 'Darkness', uses: 1 }, { name: 'Faerie Fire', uses: 1 }] },
    ],
    altTraits: [],
    languagesAuto: ['elven', 'undercommon'],
    languagesBonus: ['abyssal', 'aklo', 'aquan', 'common', 'draconic', 'gnome', 'goblin'],
  },
  {
    id: 'fetchling', name: 'Fetchling', sub: '+2 Dex, +2 Cha, −2 Wis',
    desc: 'Descendants of humans lost to the Shadow Plane, fetchlings are wary survivors at home in darkness.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, cha: 2, wis: -2 },
    traits: [
      { id: 'fetchling-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet (plus low-light vision).', senses: ['Darkvision 60 ft', 'Low-light vision'] },
      { id: 'fetchling-resist', name: 'Shadow Resistance', desc: 'Cold and electricity resistance 5.',
        energyResistance: [{ type: 'cold', amount: 5 }, { type: 'electricity', amount: 5 }] },
      { id: 'fetchling-skilled', name: 'Skilled', desc: '+2 racial bonus on Knowledge (planes) and Stealth checks.', effects: [{ target: 'skill:know-planes', type: 'racial', value: 2, note: 'Skilled (Fetchling)' }, { target: 'skill:stealth', type: 'racial', value: 2, note: 'Skilled (Fetchling)' }] },
      { id: 'fetchling-blend', name: 'Shadow Blending', desc: 'In dim light, attacks against you have a 50% miss chance instead of 20%.' },
      { id: 'fetchling-sla', name: 'Spell-Like Ability', desc: 'Use disguise self once per day (shadow walk and plane shift at higher levels).', spellLikeAbilities: [{ name: 'Disguise Self', uses: 1, note: 'shadow walk & plane shift at higher levels' }] },
    ],
    altTraits: [],
    languagesAuto: ['common'],
    languagesBonus: ['aklo', 'aquan', 'auran', 'draconic', 'ignan', 'terran'],
  },
  {
    id: 'goblin', name: 'Goblin', sub: '+4 Dex, −2 Str, −2 Cha · Small',
    desc: 'Small, manic, and fire-loving, goblins are fast, stealthy, and far more dangerous than their size suggests.',
    size: 'small', speed: 30, abilityMods: { dex: 4, str: -2, cha: -2 },
    traits: [
      { id: 'goblin-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'goblin-skilled', name: 'Skilled', desc: '+4 racial bonus on Ride and Stealth checks.', effects: [{ target: 'skill:ride', type: 'racial', value: 4, note: 'Skilled (Goblin)' }, { target: 'skill:stealth', type: 'racial', value: 4, note: 'Skilled (Goblin)' }] },
      { id: 'goblin-fast', name: 'Fast Movement', desc: 'Base speed 30 ft, unusually fast for a Small creature.' },
    ],
    altTraits: [],
    languagesAuto: ['goblin'],
    languagesBonus: ['common', 'draconic', 'dwarven', 'gnoll', 'orc'],
  },
  {
    id: 'hobgoblin', name: 'Hobgoblin', sub: '+2 Dex, +2 Con',
    desc: 'Disciplined, militaristic goblinoids who prize order, strength, and conquest.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, con: 2 },
    traits: [
      { id: 'hobgoblin-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'hobgoblin-sneaky', name: 'Sneaky', desc: '+4 racial bonus on Stealth checks.', effects: [{ target: 'skill:stealth', type: 'racial', value: 4, note: 'Sneaky (Hobgoblin)' }] },
    ],
    altTraits: [],
    languagesAuto: ['common', 'goblin'],
    languagesBonus: ['draconic', 'dwarven', 'giant', 'infernal', 'orc'],
  },
  {
    id: 'ifrit', name: 'Ifrit', sub: '+2 Dex, +2 Cha, −2 Wis',
    desc: 'Descendants of mortals and fire elementals (efreet), ifrits are passionate, quick-tempered, and touched by flame.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, cha: 2, wis: -2 },
    traits: [
      { id: 'ifrit-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'ifrit-resist', name: 'Fire Resistance', desc: 'Fire resistance 5.', energyResistance: [{ type: 'fire', amount: 5 }] },
      { id: 'ifrit-sla', name: 'Spell-Like Ability', desc: 'Use burning hands once per day (DC 11 + Cha modifier).', spellLikeAbilities: [{ name: 'Burning Hands', uses: 1, note: 'DC 11 + Cha' }] },
      { id: 'ifrit-affinity', name: 'Fire Affinity', desc: 'Fire-bloodline sorcerers treat Charisma as 2 higher; Fire-domain clerics gain +1 caster level.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'ignan'],
    languagesBonus: ['aquan', 'auran', 'dwarven', 'elven', 'gnome', 'halfling', 'terran'],
  },
  {
    id: 'kobold', name: 'Kobold', sub: '+2 Dex, −4 Str, −2 Con · Small',
    desc: 'Small, scaly, and treacherous, kobolds are cowardly alone but deadly in numbers, masters of traps and ambush.',
    size: 'small', speed: 30, abilityMods: { dex: 2, str: -4, con: -2 },
    traits: [
      { id: 'kobold-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'kobold-armor', name: 'Natural Armor', desc: '+1 natural armor bonus from scaly hide.', effects: [{ target: 'ac', type: 'natural-armor', value: 1, note: 'Natural Armor (Kobold)' }] },
      { id: 'kobold-skilled', name: 'Crafty', desc: '+2 racial bonus on Perception, and on Craft (trapmaking) and Profession (miner) checks; Stealth and Craft (trapmaking) are always class skills.', effects: [{ target: 'skill:perception', type: 'racial', value: 2, note: 'Crafty (Kobold)' }] },
      { id: 'kobold-light-sens', name: 'Light Sensitivity', desc: 'Dazzled in bright light.' },
    ],
    altTraits: [],
    languagesAuto: ['draconic'],
    languagesBonus: ['common', 'dwarven', 'gnome', 'undercommon'],
  },
  {
    id: 'orc', name: 'Orc', sub: '+4 Str, −2 Int, −2 Wis, −2 Cha',
    desc: 'Brutal, savage, and relentless, full-blooded orcs live for battle and rarely back down from a fight.',
    size: 'medium', speed: 30, abilityMods: { str: 4, int: -2, wis: -2, cha: -2 },
    traits: [
      { id: 'orc-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'orc-ferocity', name: 'Ferocity', desc: 'Once brought below 0 HP, remain conscious and fighting (staggered) as long as you keep acting.' },
      { id: 'orc-weapons', name: 'Weapon Familiarity', desc: 'Proficient with greataxes and falchions; treat "orc" weapons as martial.' },
      { id: 'orc-light-sens', name: 'Light Sensitivity', desc: 'Dazzled in bright light.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'orc'],
    languagesBonus: ['dwarven', 'giant', 'gnoll', 'goblin', 'undercommon'],
  },
  {
    id: 'oread', name: 'Oread', sub: '+2 Str, +2 Wis, −2 Cha',
    desc: 'Stoic and stony descendants of earth elementals, oreads are patient, deliberate, and hard to move.',
    size: 'medium', speed: 20, speedNeverReduced: true, abilityMods: { str: 2, wis: 2, cha: -2 },
    traits: [
      { id: 'oread-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'oread-slow', name: 'Slow and Steady', desc: 'Base speed 20 ft, never modified by armor or encumbrance.' },
      { id: 'oread-resist', name: 'Acid Resistance', desc: 'Acid resistance 5.', energyResistance: [{ type: 'acid', amount: 5 }] },
      { id: 'oread-sla', name: 'Spell-Like Ability', desc: 'Use magic stone once per day.', spellLikeAbilities: [{ name: 'Magic Stone', uses: 1 }] },
      { id: 'oread-affinity', name: 'Earth Affinity', desc: 'Earth-bloodline sorcerers treat Charisma as 2 higher; Earth-domain clerics gain +1 caster level.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'terran'],
    languagesBonus: ['aquan', 'auran', 'dwarven', 'elven', 'gnome', 'halfling', 'ignan', 'undercommon'],
  },
  {
    id: 'ratfolk', name: 'Ratfolk', sub: '+2 Dex, +2 Int, −2 Str · Small',
    desc: 'Small, clever, communal rat-people — tinkerers, traders, and survivors who fight best shoulder to shoulder.',
    size: 'small', speed: 20, abilityMods: { dex: 2, int: 2, str: -2 },
    traits: [
      { id: 'ratfolk-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'ratfolk-slow', name: 'Slow Speed', desc: 'Base speed 20 ft.' },
      { id: 'ratfolk-skilled', name: 'Rodent Empathy & Tinker', desc: '+2 racial bonus on Craft (alchemy), Perception, and Use Magic Device; +4 on Handle Animal with rodents.', effects: [{ target: 'skill:craft-alchemy', type: 'racial', value: 2, note: 'Tinker (Ratfolk)' }, { target: 'skill:perception', type: 'racial', value: 2, note: 'Tinker (Ratfolk)' }, { target: 'skill:use-magic-device', type: 'racial', value: 2, note: 'Tinker (Ratfolk)' }] },
      { id: 'ratfolk-swarming', name: 'Swarming', desc: 'Two ratfolk can share a square; when both attack the same foe they count as flanking.' },
    ],
    altTraits: [],
    languagesAuto: ['common'],
    languagesBonus: ['aklo', 'draconic', 'dwarven', 'gnoll', 'gnome', 'goblin', 'halfling', 'orc', 'undercommon'],
  },
  {
    id: 'sylph', name: 'Sylph', sub: '+2 Dex, +2 Int, −2 Con',
    desc: 'Airy descendants of air elementals, sylphs are secretive, watchful, and light on their feet.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, int: 2, con: -2 },
    traits: [
      { id: 'sylph-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'sylph-resist', name: 'Electricity Resistance', desc: 'Electricity resistance 5.', energyResistance: [{ type: 'electricity', amount: 5 }] },
      { id: 'sylph-sla', name: 'Spell-Like Ability', desc: 'Use feather fall once per day.', spellLikeAbilities: [{ name: 'Feather Fall', uses: 1 }] },
      { id: 'sylph-affinity', name: 'Air Affinity', desc: 'Air-bloodline sorcerers treat Charisma as 2 higher; Air-domain clerics gain +1 caster level.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'auran'],
    languagesBonus: ['aquan', 'dwarven', 'elven', 'gnome', 'halfling', 'ignan', 'terran'],
  },
  {
    id: 'tengu', name: 'Tengu', sub: '+2 Dex, +2 Wis, −2 Con',
    desc: 'Crow-like humanoids famed as gifted linguists and natural swordsmen, curious and quick.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, wis: 2, con: -2 },
    traits: [
      { id: 'tengu-low-light', name: 'Low-Light Vision', desc: 'See twice as far as humans in dim light.', senses: ['Low-light vision'] },
      { id: 'tengu-senses', name: 'Sneaky', desc: '+2 racial bonus on Perception and Stealth checks.', effects: [{ target: 'skill:perception', type: 'racial', value: 2, note: 'Sneaky (Tengu)' }, { target: 'skill:stealth', type: 'racial', value: 2, note: 'Sneaky (Tengu)' }] },
      { id: 'tengu-linguist', name: 'Gifted Linguist', desc: '+4 racial bonus on Linguistics; learn 2 languages each time you gain a rank in it.', effects: [{ target: 'skill:linguistics', type: 'racial', value: 4, note: 'Gifted Linguist' }] },
      { id: 'tengu-bite', name: 'Natural Weapon', desc: 'A bite attack dealing 1d3 damage.', naturalAttacks: [{ name: 'Bite', count: 1, damage: '1d3', dmgType: 'B/P/S', primary: true }] },
      { id: 'tengu-swords', name: 'Swordtrained', desc: 'Proficient with all sword-like weapons (longsword, rapier, scimitar, falchion, and more).' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'tengu'],
    languagesBonus: ['aklo', 'draconic', 'dwarven', 'elven', 'gnoll', 'gnome', 'goblin', 'orc'],
  },
  {
    id: 'tiefling', name: 'Tiefling', sub: '+2 Dex, +2 Int, −2 Cha',
    desc: 'Mortals with fiendish blood, tieflings bear the mark of the lower planes and the suspicion it brings.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, int: 2, cha: -2 },
    traits: [
      { id: 'tiefling-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'tiefling-resist', name: 'Fiendish Resistance', desc: 'Cold, electricity, and fire resistance 5.',
        energyResistance: [{ type: 'cold', amount: 5 }, { type: 'electricity', amount: 5 }, { type: 'fire', amount: 5 }] },
      { id: 'tiefling-skilled', name: 'Skilled', desc: '+2 racial bonus on Bluff and Stealth checks.', effects: [{ target: 'skill:bluff', type: 'racial', value: 2, note: 'Skilled (Tiefling)' }, { target: 'skill:stealth', type: 'racial', value: 2, note: 'Skilled (Tiefling)' }] },
      { id: 'tiefling-sla', name: 'Spell-Like Ability', desc: 'Use darkness once per day.', spellLikeAbilities: [{ name: 'Darkness', uses: 1 }] },
      { id: 'tiefling-sorcery', name: 'Fiendish Sorcery', desc: 'Abyssal or Infernal bloodline sorcerers treat Charisma as 2 higher.' },
    ],
    altTraits: [],
    heritageReplaces: ['tiefling-skilled', 'tiefling-sla'],
    heritages: [
      heritage('faultspawn', 'Asura-Spawn (Faultspawn)', { dex: 2, wis: 2, int: -2 }, ['appraise', 'know-local'], 'Hideous Laughter', 'Swift and wise scions of the exotic asuras, favoring tradition over cunning.'),
      heritage('grimspawn', 'Daemon-Spawn (Grimspawn)', { dex: 2, int: 2, wis: -2 }, ['disable-device', 'sleight-of-hand'], 'Death Knell', 'Shrewd, swift bringers of devastation whose plans hide exploitable flaws.'),
      heritage('foulspawn', 'Demodand-Spawn (Foulspawn)', { con: 2, wis: 2, int: -2 }, ['intimidate', 'know-religion'], "Bear's Endurance", 'Burly, bizarrely cunning spawn who favor brawn over planning.'),
      heritage('pitborn', 'Demon-Spawn (Pitborn)', { str: 2, cha: 2, int: -2 }, ['disable-device', 'perception'], 'Shatter', 'Savage and monstrous, they know the chaotic fury of their Abyssal ancestors.'),
      heritage('hellspawn', 'Devil-Spawn (Hellspawn)', { con: 2, wis: 2, cha: -2 }, ['diplomacy', 'sense-motive'], 'Pyrotechnics', "Stalwart and conniving, they know the discipline and might of Hell's legions."),
      heritage('spitespawn', 'Div-Spawn (Spitespawn)', { dex: 2, cha: 2, int: -2 }, ['diplomacy', 'linguistics'], 'Misdirection', 'Precise and exotic as a desert wind, after their div ancestors.'),
      heritage('shackleborn', 'Kyton-Spawn (Shackleborn)', { con: 2, cha: 2, wis: -2 }, ['escape-artist', 'intimidate'], 'Web', 'Black-hearted spawn of shadow and pain who know their forebears’ sadistic vices.'),
      heritage('hungerseed', 'Oni-Spawn (Hungerseed)', { str: 2, wis: 2, cha: -2 }, ['disguise', 'intimidate'], 'Alter Self', 'Masters of trickery and cruelty in the ways of their ancestral oni.'),
      heritage('motherless', 'Qlippoth-Spawn (Motherless)', { str: 2, wis: 2, int: -2 }, ['escape-artist', 'survival'], 'Blur', 'Rare, warped scions of the eldritch qlippoths, tenacious and insidious.'),
      heritage('beastbrood', 'Rakshasa-Spawn (Beastbrood)', { dex: 2, cha: 2, wis: -2 }, ['disguise', 'sense-motive'], 'Detect Thoughts', 'Deft, charming, bestial tieflings with a rakshasa’s subtlety and guile.'),
    ],
    languagesAuto: ['common'],
    languagesBonus: ['abyssal', 'draconic', 'dwarven', 'elven', 'gnome', 'goblin', 'halfling', 'infernal', 'orc'],
  },
  {
    id: 'undine', name: 'Undine', sub: '+2 Dex, +2 Wis, −2 Str',
    desc: 'Descendants of water elementals, undines are graceful, fluid, and utterly at home beneath the waves.',
    size: 'medium', speed: 30, speeds: { swim: 30 }, abilityMods: { dex: 2, wis: 2, str: -2 },
    traits: [
      { id: 'undine-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.', senses: ['Darkvision 60 ft'] },
      { id: 'undine-swim', name: 'Amphibious & Swim', desc: 'A 30-ft swim speed and the ability to breathe water; Swim is always a class skill.' },
      { id: 'undine-resist', name: 'Cold Resistance', desc: 'Cold resistance 5.', energyResistance: [{ type: 'cold', amount: 5 }] },
      { id: 'undine-sla', name: 'Spell-Like Ability', desc: 'Use hydraulic push once per day.', spellLikeAbilities: [{ name: 'Hydraulic Push', uses: 1 }] },
      { id: 'undine-affinity', name: 'Water Affinity', desc: 'Water-bloodline sorcerers treat Charisma as 2 higher; Water-domain clerics gain +1 caster level.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'aquan'],
    languagesBonus: ['auran', 'dwarven', 'elven', 'gnome', 'halfling', 'ignan', 'terran'],
  },
];
