import type { RaceDef } from './model';

// Uncommon races (Advanced Race Guide). Verified against d20pfsrd. Same conventions as the
// featured races: stat/skill/save bonuses fold in as effects; darkvision, resistances, natural
// attacks, and spell-like abilities are descriptive traits. Fly/swim speeds are noted as traits
// (the engine models a single land speed).

export const UNCOMMON_RACES: RaceDef[] = [
  {
    id: 'changeling', name: 'Changeling', sub: '+2 Wis, +2 Cha, −2 Con',
    desc: 'The abandoned daughters of hags, changelings are marked by mismatched eyes and a whispering call to their monstrous heritage.',
    size: 'medium', speed: 30, abilityMods: { wis: 2, cha: 2, con: -2 },
    traits: [
      { id: 'changeling-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.' },
      { id: 'changeling-armor', name: 'Natural Armor', desc: '+1 natural armor bonus.', effects: [{ target: 'ac', type: 'natural-armor', value: 1, note: 'Natural Armor (Changeling)' }] },
      { id: 'changeling-claws', name: 'Claws', desc: 'Two claw attacks dealing 1d4 damage each.' },
      { id: 'changeling-heritage', name: 'Hag Heritage', desc: 'One trait inherited from your hag mother (a bonus to melee damage, a save, a skill, or similar depending on the hag type).' },
    ],
    altTraits: [],
    languagesAuto: ['common'],
    languagesBonus: ['aklo', 'draconic', 'dwarven', 'elven', 'giant', 'gnoll', 'goblin', 'orc'],
  },
  {
    id: 'duergar', name: 'Duergar', sub: '+2 Con, +2 Wis, −4 Cha',
    desc: 'Grim, gray dwarves of the deep earth — dour, cruel, and enduring, shaped by ages underground.',
    size: 'medium', speed: 20, speedNeverReduced: true, abilityMods: { con: 2, wis: 2, cha: -4 },
    traits: [
      { id: 'duergar-darkvision', name: 'Superior Darkvision', desc: 'See in the dark up to 120 feet.' },
      { id: 'duergar-slow', name: 'Slow and Steady', desc: 'Base speed 20 ft, never modified by armor or encumbrance.' },
      { id: 'duergar-stability', name: 'Stability', desc: '+4 racial bonus to CMD against bull rush and trip while on solid ground.', effects: [{ target: 'cmd', type: 'racial', value: 4, note: 'Stability (Duergar)', condition: 'vs bull rush / trip while on the ground' }] },
      { id: 'duergar-immunities', name: 'Duergar Immunities', desc: 'Immune to paralysis, phantasms, and poison; +2 racial bonus on saves against spells and spell-like abilities.', effects: [{ target: 'save:all', type: 'racial', value: 2, note: 'Duergar Immunities', condition: 'vs spells and spell-like abilities' }] },
      { id: 'duergar-sla', name: 'Spell-Like Abilities', desc: 'Enlarge person and invisibility once each per day (self only).' },
      { id: 'duergar-light-sens', name: 'Light Sensitivity', desc: 'Dazzled in bright light.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'dwarven', 'undercommon'],
    languagesBonus: ['aklo', 'draconic', 'giant', 'goblin', 'orc', 'terran'],
  },
  {
    id: 'gillman', name: 'Gillman', sub: '+2 Con, +2 Cha, −2 Wis',
    desc: 'Aquatic descendants of humans fleshwarped by aboleths, gillmen live between land and the crushing deep.',
    size: 'medium', speed: 30, speeds: { swim: 30 }, abilityMods: { con: 2, cha: 2, wis: -2 },
    traits: [
      { id: 'gillman-low-light', name: 'Low-Light Vision', desc: 'See twice as far as humans in dim light.' },
      { id: 'gillman-amphibious', name: 'Amphibious', desc: 'Breathe both air and water; a 30-ft swim speed and Swim is always a class skill.' },
      { id: 'gillman-water-dep', name: 'Water Dependent', desc: 'Must submerge in water once per day or begin to suffocate.' },
      { id: 'gillman-enchant', name: 'Enchantment Resistance', desc: '+2 on saves against non-aboleth enchantments, but −2 against aboleth ones.', effects: [{ target: 'save:all', type: 'racial', value: 2, note: 'Enchantment Resistance', condition: 'vs non-aboleth enchantment' }] },
    ],
    altTraits: [],
    languagesAuto: ['common', 'aboleth'],
    languagesBonus: ['aklo', 'aquan', 'draconic', 'elven'],
  },
  {
    id: 'grippli', name: 'Grippli', sub: '+2 Dex, +2 Wis, −2 Str · Small',
    desc: 'Small, tree-dwelling frog-folk of the swamps and rainforests — shy, watchful, and quick to hide.',
    size: 'small', speed: 30, speeds: { climb: 20 }, abilityMods: { dex: 2, wis: 2, str: -2 },
    traits: [
      { id: 'grippli-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.' },
      { id: 'grippli-climb', name: 'Climb Speed', desc: 'A 20-ft climb speed (with a +8 racial bonus on Climb checks).' },
      { id: 'grippli-camouflage', name: 'Camouflage', desc: '+4 racial bonus on Stealth checks in marshes and forests.' },
      { id: 'grippli-swamp', name: 'Swamp Stride', desc: 'Move through difficult swamp terrain at normal speed.' },
      { id: 'grippli-weapons', name: 'Weapon Familiarity', desc: 'Proficient with nets.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'grippli'],
    languagesBonus: ['boggard', 'draconic', 'elven', 'gnome', 'goblin', 'sylvan'],
  },
  {
    id: 'kitsune', name: 'Kitsune', sub: '+2 Dex, +2 Cha, −2 Str',
    desc: 'Shapeshifting fox-folk who wear a single human guise, prizing loyalty, mischief, and clever storytelling.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, cha: 2, str: -2 },
    traits: [
      { id: 'kitsune-low-light', name: 'Low-Light Vision', desc: 'See twice as far as humans in dim light.' },
      { id: 'kitsune-change', name: 'Change Shape', desc: 'Assume a fixed human form as a standard action (+10 on Disguise to appear human).' },
      { id: 'kitsune-bite', name: 'Natural Weapon', desc: 'A bite attack dealing 1d4 damage (true form only).' },
      { id: 'kitsune-agile', name: 'Agile', desc: '+2 racial bonus on Acrobatics checks.', effects: [{ target: 'skill:acrobatics', type: 'racial', value: 2, note: 'Agile (Kitsune)' }] },
      { id: 'kitsune-magic', name: 'Kitsune Magic', desc: '+1 to the DC of enchantment spells you cast; dancing lights 3/day with Cha 11+.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'sylvan'],
    languagesBonus: ['aklo', 'celestial', 'elven', 'gnome', 'tengu'],
  },
  {
    id: 'merfolk', name: 'Merfolk', sub: '+2 Dex, +2 Con, +2 Cha',
    desc: 'Graceful fish-tailed folk of the seas — proud, beautiful, and nearly helpless out of the water.',
    size: 'medium', speed: 5, speeds: { swim: 50 }, abilityMods: { dex: 2, con: 2, cha: 2 },
    traits: [
      { id: 'merfolk-low-light', name: 'Low-Light Vision', desc: 'See twice as far as humans in dim light.' },
      { id: 'merfolk-swim', name: 'Aquatic & Swim', desc: 'A 50-ft swim speed; land speed is only 5 ft (they drag themselves ashore).' },
      { id: 'merfolk-amphibious', name: 'Amphibious', desc: 'Breathe both air and water.' },
      { id: 'merfolk-armor', name: 'Natural Armor', desc: '+2 natural armor bonus.', effects: [{ target: 'ac', type: 'natural-armor', value: 2, note: 'Natural Armor (Merfolk)' }] },
      { id: 'merfolk-legless', name: 'Legless', desc: 'Having no legs, merfolk cannot be tripped.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'aquan'],
    languagesBonus: ['aboleth', 'aklo', 'draconic', 'elven', 'sylvan'],
  },
  {
    id: 'nagaji', name: 'Nagaji', sub: '+2 Str, +2 Cha, −2 Int',
    desc: 'Serpentine humanoids bred by nagas as servitors, proud and dutiful, with scaled hides and reptilian grace.',
    size: 'medium', speed: 30, abilityMods: { str: 2, cha: 2, int: -2 },
    traits: [
      { id: 'nagaji-low-light', name: 'Low-Light Vision', desc: 'See twice as far as humans in dim light.' },
      { id: 'nagaji-armor', name: 'Natural Armor', desc: '+1 natural armor bonus from scaly flesh.', effects: [{ target: 'ac', type: 'natural-armor', value: 1, note: 'Natural Armor (Nagaji)' }] },
      { id: 'nagaji-resistant', name: 'Resistant', desc: '+2 racial bonus on saves against mind-affecting effects and poison.', effects: [{ target: 'save:all', type: 'racial', value: 2, note: 'Resistant (Nagaji)', condition: 'vs mind-affecting and poison' }] },
      { id: 'nagaji-senses', name: "Serpent's Sense", desc: '+2 racial bonus on Perception, and +2 on Handle Animal with reptiles.', effects: [{ target: 'skill:perception', type: 'racial', value: 2, note: "Serpent's Sense" }] },
    ],
    altTraits: [],
    languagesAuto: ['common', 'draconic'],
    languagesBonus: ['aklo', 'celestial', 'giant', 'infernal', 'undercommon'],
  },
  {
    id: 'samsaran', name: 'Samsaran', sub: '+2 Int, +2 Wis, −2 Con',
    desc: 'Reincarnating blue-skinned mystics who carry the faint echoes of their many past lives.',
    size: 'medium', speed: 30, abilityMods: { int: 2, wis: 2, con: -2 },
    traits: [
      { id: 'samsaran-low-light', name: 'Low-Light Vision', desc: 'See twice as far as humans in dim light.' },
      { id: 'samsaran-lifebound', name: 'Lifebound', desc: '+2 racial bonus on saves against death effects, negative energy, and to remove negative levels.', effects: [{ target: 'save:all', type: 'racial', value: 2, note: 'Lifebound', condition: 'vs death and negative energy' }] },
      { id: 'samsaran-shards', name: 'Shards of the Past', desc: 'Choose two skills; gain a +2 racial bonus on each, and they are always class skills (echoes of past lives).' },
      { id: 'samsaran-magic', name: 'Samsaran Magic', desc: 'Comprehend languages, deathwatch, and stabilize once each per day with Cha 11+.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'samsaran'],
    languagesBonus: ['abyssal', 'aquan', 'auran', 'celestial', 'draconic', 'giant', 'ignan', 'infernal', 'nagaji', 'tengu', 'terran'],
  },
  {
    id: 'strix', name: 'Strix', sub: '+2 Dex, −2 Cha',
    desc: 'Winged, nocturnal humanoids fiercely defensive of their mountain territory and deeply wary of humankind.',
    size: 'medium', speed: 30, speeds: { fly: 60 }, abilityMods: { dex: 2, cha: -2 },
    traits: [
      { id: 'strix-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.' },
      { id: 'strix-fly', name: 'Flight', desc: 'A 60-ft fly speed (average maneuverability).' },
      { id: 'strix-nocturnal', name: 'Nocturnal', desc: '+2 racial bonus on Perception and Stealth checks in dim light or darkness.' },
      { id: 'strix-hatred', name: 'Hatred', desc: '+1 racial bonus on attack rolls against humanoids of the human subtype.', effects: [{ target: 'attack:melee', type: 'racial', value: 1, note: 'Hatred (Strix)', condition: 'vs humans' }] },
      { id: 'strix-suspicious', name: 'Suspicious', desc: '+2 racial bonus on saves against illusions.', effects: [{ target: 'save:all', type: 'racial', value: 2, note: 'Suspicious (Strix)', condition: 'vs illusions' }] },
    ],
    altTraits: [],
    languagesAuto: ['strix'],
    languagesBonus: ['auran', 'common', 'draconic', 'giant', 'gnome', 'goblin', 'infernal'],
  },
  {
    id: 'suli', name: 'Suli', sub: '+2 Str, +2 Cha, −2 Int',
    desc: 'Descendants of mortals and jann, sulis are charismatic diplomats who can wreathe their limbs in elemental power.',
    size: 'medium', speed: 30, abilityMods: { str: 2, cha: 2, int: -2 },
    traits: [
      { id: 'suli-low-light', name: 'Low-Light Vision', desc: 'See twice as far as humans in dim light.' },
      { id: 'suli-assault', name: 'Elemental Assault', desc: 'Once per day, shroud your limbs in acid, cold, electricity, or fire for +1d6 damage per hit for several rounds.' },
      { id: 'suli-resist', name: 'Energy Resistance', desc: 'Resistance 5 to acid, cold, electricity, and fire.',
        energyResistance: [{ type: 'acid', amount: 5 }, { type: 'cold', amount: 5 }, { type: 'electricity', amount: 5 }, { type: 'fire', amount: 5 }] },
      { id: 'suli-negotiator', name: 'Negotiator', desc: '+2 racial bonus on Diplomacy and Sense Motive checks.', effects: [{ target: 'skill:diplomacy', type: 'racial', value: 2, note: 'Negotiator (Suli)' }, { target: 'skill:sense-motive', type: 'racial', value: 2, note: 'Negotiator (Suli)' }] },
    ],
    altTraits: [],
    languagesAuto: ['common'],
    languagesBonus: ['aquan', 'auran', 'ignan', 'terran'],
  },
  {
    id: 'svirfneblin', name: 'Svirfneblin', sub: '+2 Dex, +2 Wis, −2 Str, −4 Cha · Small',
    desc: 'Deep gnomes of the underworld — dour, secretive, and extraordinarily hard to catch off guard.',
    size: 'small', speed: 20, abilityMods: { dex: 2, wis: 2, str: -2, cha: -4 },
    traits: [
      { id: 'svirf-darkvision', name: 'Superior Darkvision', desc: 'See in the dark up to 120 feet (plus low-light vision).' },
      { id: 'svirf-defensive', name: 'Defensive Training', desc: '+2 dodge bonus to AC.', effects: [{ target: 'ac', type: 'dodge', value: 2, note: 'Defensive Training (Svirfneblin)' }] },
      { id: 'svirf-saves', name: 'Fortunate', desc: '+2 racial bonus on all saving throws.', effects: [{ target: 'save:all', type: 'racial', value: 2, note: 'Fortunate (Svirfneblin)' }] },
      { id: 'svirf-sr', name: 'Spell Resistance', desc: 'Spell resistance equal to 11 + class levels.' },
      { id: 'svirf-skilled', name: 'Skilled', desc: '+2 racial bonus on Craft (alchemy) and Perception; +2 on Stealth (+4 more underground).', effects: [{ target: 'skill:craft-alchemy', type: 'racial', value: 2, note: 'Skilled (Svirfneblin)' }, { target: 'skill:perception', type: 'racial', value: 2, note: 'Skilled (Svirfneblin)' }, { target: 'skill:stealth', type: 'racial', value: 2, note: 'Skilled (Svirfneblin)' }] },
      { id: 'svirf-magic', name: 'Svirfneblin Magic', desc: 'Constant nondetection; blindness/deafness, blur, and disguise self once each per day; +1 illusion DC.' },
    ],
    altTraits: [],
    languagesAuto: ['gnome', 'undercommon'],
    languagesBonus: ['aklo', 'common', 'draconic', 'dwarven', 'elven', 'giant', 'goblin', 'orc', 'terran'],
  },
  {
    id: 'vanara', name: 'Vanara', sub: '+2 Dex, +2 Wis, −2 Cha',
    desc: 'Agile monkey-folk of the deep jungles — playful, curious, and endlessly nimble in the canopy.',
    size: 'medium', speed: 30, speeds: { climb: 20 }, abilityMods: { dex: 2, wis: 2, cha: -2 },
    traits: [
      { id: 'vanara-low-light', name: 'Low-Light Vision', desc: 'See twice as far as humans in dim light.' },
      { id: 'vanara-climb', name: 'Climb Speed', desc: 'A 20-ft climb speed (with a +8 racial bonus on Climb checks).' },
      { id: 'vanara-tail', name: 'Prehensile Tail', desc: 'A grasping tail that can retrieve a stowed object as a swift action (but cannot wield weapons).' },
      { id: 'vanara-nimble', name: 'Nimble', desc: '+2 racial bonus on Acrobatics and Stealth checks.', effects: [{ target: 'skill:acrobatics', type: 'racial', value: 2, note: 'Nimble (Vanara)' }, { target: 'skill:stealth', type: 'racial', value: 2, note: 'Nimble (Vanara)' }] },
    ],
    altTraits: [],
    languagesAuto: ['common', 'vanaran'],
    languagesBonus: ['aklo', 'celestial', 'elven', 'gnome', 'goblin', 'sylvan'],
  },
  {
    id: 'vishkanya', name: 'Vishkanya', sub: '+2 Dex, +2 Cha, −2 Wis',
    desc: 'Sensuous, serpent-eyed humanoids whose blood and saliva carry a natural venom.',
    size: 'medium', speed: 30, abilityMods: { dex: 2, cha: 2, wis: -2 },
    traits: [
      { id: 'vishkanya-low-light', name: 'Low-Light Vision', desc: 'See twice as far as humans in dim light.' },
      { id: 'vishkanya-poison-use', name: 'Poison Use', desc: 'Never risk poisoning yourself when applying poison.' },
      { id: 'vishkanya-toxic', name: 'Toxic', desc: 'Envenom a weapon with your saliva/blood a few times per day (1d2 Dex damage for several rounds).' },
      { id: 'vishkanya-limber', name: 'Limber', desc: '+2 racial bonus on Escape Artist and Stealth checks.', effects: [{ target: 'skill:escape-artist', type: 'racial', value: 2, note: 'Limber (Vishkanya)' }, { target: 'skill:stealth', type: 'racial', value: 2, note: 'Limber (Vishkanya)' }] },
      { id: 'vishkanya-senses', name: 'Keen Senses', desc: '+2 racial bonus on Perception checks.', effects: [{ target: 'skill:perception', type: 'racial', value: 2, note: 'Keen Senses (Vishkanya)' }] },
      { id: 'vishkanya-poison-resist', name: 'Poison Resistance', desc: 'A racial bonus on poison saves equal to your Hit Dice.' },
      { id: 'vishkanya-weapons', name: 'Weapon Familiarity', desc: 'Proficient with blowguns, kukris, and shuriken.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'vishkanya'],
    languagesBonus: ['aklo', 'draconic', 'elven', 'goblin', 'sylvan', 'undercommon'],
  },
  {
    id: 'wayang', name: 'Wayang', sub: '+2 Dex, +2 Int, −2 Wis · Small',
    desc: 'Small shadow-touched folk who believe they are made of living darkness, quiet and inscrutable.',
    size: 'small', speed: 20, abilityMods: { dex: 2, int: 2, wis: -2 },
    traits: [
      { id: 'wayang-darkvision', name: 'Darkvision', desc: 'See in the dark up to 60 feet.' },
      { id: 'wayang-shadow-resist', name: 'Shadow Resistance', desc: '+2 racial bonus on saves against spells of the shadow subschool.', effects: [{ target: 'save:all', type: 'racial', value: 2, note: 'Shadow Resistance (Wayang)', condition: 'vs shadow subschool' }] },
      { id: 'wayang-lurker', name: 'Lurker', desc: '+2 racial bonus on Perception and Stealth checks.', effects: [{ target: 'skill:perception', type: 'racial', value: 2, note: 'Lurker (Wayang)' }, { target: 'skill:stealth', type: 'racial', value: 2, note: 'Lurker (Wayang)' }] },
      { id: 'wayang-magic', name: 'Shadow Magic', desc: '+1 to the DC of shadow spells you cast; ghost sound, pass without trace, and ventriloquism once each per day with Cha 11+.' },
      { id: 'wayang-light-dark', name: 'Light and Dark', desc: 'Once per day, treat positive and negative energy as an undead would for 1 minute.' },
    ],
    altTraits: [],
    languagesAuto: ['common', 'wayang'],
    languagesBonus: ['abyssal', 'aklo', 'draconic', 'goblin', 'infernal', 'nagaji', 'samsaran'],
  },
];
