import type { SkillDef } from './model';

// Core skill list (Knowledge/Craft/Profession/Perform expanded to common subskills).
export const SKILLS: SkillDef[] = [
  { id: 'acrobatics', name: 'Acrobatics', ability: 'dex', acp: true, trainedOnly: false },
  { id: 'appraise', name: 'Appraise', ability: 'int', acp: false, trainedOnly: false },
  { id: 'bluff', name: 'Bluff', ability: 'cha', acp: false, trainedOnly: false },
  { id: 'climb', name: 'Climb', ability: 'str', acp: true, trainedOnly: false },
  { id: 'craft-alchemy', name: 'Craft (alchemy)', ability: 'int', acp: false, trainedOnly: false },
  { id: 'craft-armor', name: 'Craft (armor)', ability: 'int', acp: false, trainedOnly: false },
  { id: 'craft-weapons', name: 'Craft (weapons)', ability: 'int', acp: false, trainedOnly: false },
  { id: 'diplomacy', name: 'Diplomacy', ability: 'cha', acp: false, trainedOnly: false },
  { id: 'disable-device', name: 'Disable Device', ability: 'dex', acp: true, trainedOnly: true },
  { id: 'disguise', name: 'Disguise', ability: 'cha', acp: false, trainedOnly: false },
  { id: 'escape-artist', name: 'Escape Artist', ability: 'dex', acp: true, trainedOnly: false },
  { id: 'fly', name: 'Fly', ability: 'dex', acp: true, trainedOnly: false },
  { id: 'handle-animal', name: 'Handle Animal', ability: 'cha', acp: false, trainedOnly: true },
  { id: 'heal', name: 'Heal', ability: 'wis', acp: false, trainedOnly: false },
  { id: 'intimidate', name: 'Intimidate', ability: 'cha', acp: false, trainedOnly: false },
  { id: 'know-arcana', name: 'Knowledge (arcana)', ability: 'int', acp: false, trainedOnly: true },
  { id: 'know-dungeoneering', name: 'Knowledge (dungeoneering)', ability: 'int', acp: false, trainedOnly: true },
  { id: 'know-engineering', name: 'Knowledge (engineering)', ability: 'int', acp: false, trainedOnly: true },
  { id: 'know-geography', name: 'Knowledge (geography)', ability: 'int', acp: false, trainedOnly: true },
  { id: 'know-history', name: 'Knowledge (history)', ability: 'int', acp: false, trainedOnly: true },
  { id: 'know-local', name: 'Knowledge (local)', ability: 'int', acp: false, trainedOnly: true },
  { id: 'know-nature', name: 'Knowledge (nature)', ability: 'int', acp: false, trainedOnly: true },
  { id: 'know-nobility', name: 'Knowledge (nobility)', ability: 'int', acp: false, trainedOnly: true },
  { id: 'know-planes', name: 'Knowledge (planes)', ability: 'int', acp: false, trainedOnly: true },
  { id: 'know-religion', name: 'Knowledge (religion)', ability: 'int', acp: false, trainedOnly: true },
  { id: 'linguistics', name: 'Linguistics', ability: 'int', acp: false, trainedOnly: true },
  { id: 'perception', name: 'Perception', ability: 'wis', acp: false, trainedOnly: false },
  { id: 'perform-oratory', name: 'Perform (oratory)', ability: 'cha', acp: false, trainedOnly: false },
  { id: 'perform-strings', name: 'Perform (strings)', ability: 'cha', acp: false, trainedOnly: false },
  { id: 'profession-any', name: 'Profession', ability: 'wis', acp: false, trainedOnly: true },
  { id: 'ride', name: 'Ride', ability: 'dex', acp: true, trainedOnly: false },
  { id: 'sense-motive', name: 'Sense Motive', ability: 'wis', acp: false, trainedOnly: false },
  { id: 'sleight-of-hand', name: 'Sleight of Hand', ability: 'dex', acp: true, trainedOnly: true },
  { id: 'spellcraft', name: 'Spellcraft', ability: 'int', acp: false, trainedOnly: true },
  { id: 'stealth', name: 'Stealth', ability: 'dex', acp: true, trainedOnly: false },
  { id: 'survival', name: 'Survival', ability: 'wis', acp: false, trainedOnly: false },
  { id: 'swim', name: 'Swim', ability: 'str', acp: true, trainedOnly: false },
  { id: 'use-magic-device', name: 'Use Magic Device', ability: 'cha', acp: false, trainedOnly: true },
];

export const skillById = new Map(SKILLS.map((s) => [s.id, s]));
