import type { SpellDef } from './model';

// Level 0-1 spells across the arcane/divine/druid/bard lists. Enough to exercise the
// spells step (filtering, opposition markers, spellbook picks) for the elf-wizard seed.
export const SPELLS: SpellDef[] = [
  // Cantrips (arcane 0)
  { id: 'acid-splash', name: 'Acid Splash', level: 0, school: 'Conjuration', lists: ['arcane'], summary: 'Ranged touch, 1d3 acid.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'You fire a small orb of acid at the target, dealing 1d3 acid damage on a successful ranged touch attack.' },
  { id: 'detect-magic', name: 'Detect Magic', level: 0, school: 'Divination', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Sense magical auras nearby.', cast: '1 standard action', comp: 'V, S', range: '60 ft cone', dur: 'Concentration, up to 1 min/level', save: 'None', desc: 'You detect magical auras, learning number, power, and location over up to three rounds of concentration.' },
  { id: 'light', name: 'Light', level: 0, school: 'Evocation', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Object shines like a torch.', cast: '1 standard action', comp: 'V, M/DF', range: 'Touch', dur: '10 min/level', save: 'None', desc: 'This spell causes a touched object to glow like a torch, shedding normal light in a 20-foot radius.' },
  { id: 'mage-hand', name: 'Mage Hand', level: 0, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Telekinetically move 5 lb.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Concentration', save: 'None', desc: 'You point at an object and can lift and move it at will, up to 5 pounds, within range.' },
  { id: 'prestidigitation', name: 'Prestidigitation', level: 0, school: 'Universal', lists: ['arcane', 'bard'], summary: 'Minor magical tricks.', cast: '1 standard action', comp: 'V, S', range: '10 ft', dur: '1 hour', save: 'None', desc: 'Perform simple magical effects: color, clean, chill, warm, flavor, or minor illusions.' },
  { id: 'ray-of-frost', name: 'Ray of Frost', level: 0, school: 'Evocation', lists: ['arcane'], summary: 'Ranged touch, 1d3 cold.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'A ray of freezing air and ice deals 1d3 cold damage on a ranged touch attack.' },
  { id: 'daze', name: 'Daze', level: 0, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'One humanoid loses its next action.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 round', save: 'Will negates', desc: 'A single humanoid of 4 HD or less is dazed for 1 round, taking no actions but suffering no penalty to AC.' },
  { id: 'read-magic', name: 'Read Magic', level: 0, school: 'Divination', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Read scrolls and spellbooks.', cast: '1 standard action', comp: 'V, S, F', range: 'Personal', dur: '10 min/level', save: 'None', desc: 'You can decipher magical inscriptions that would otherwise be unintelligible.' },
  { id: 'disrupt-undead', name: 'Disrupt Undead', level: 0, school: 'Necromancy', lists: ['arcane'], summary: 'Ranged touch, 1d6 vs undead.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'You channel positive energy in a ray, dealing 1d6 damage to a single undead creature.' },

  // Arcane level 1
  { id: 'magic-missile', name: 'Magic Missile', level: 1, school: 'Evocation', lists: ['arcane'], summary: '1d4+1 force, auto-hit; more missiles with level.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: 'Instantaneous', save: 'None', desc: 'A missile of magical energy darts forth and strikes its target, dealing 1d4+1 force damage. You gain additional missiles at higher levels.' },
  { id: 'mage-armor', name: 'Mage Armor', level: 1, school: 'Conjuration', lists: ['arcane'], summary: '+4 armor bonus for hours.', cast: '1 standard action', comp: 'V, S, F', range: 'Touch', dur: '1 hour/level', save: 'Will negates (harmless)', desc: 'An invisible but tangible field of force surrounds the subject, granting a +4 armor bonus to AC.' },
  { id: 'shield', name: 'Shield', level: 1, school: 'Abjuration', lists: ['arcane'], summary: '+4 shield bonus; blocks magic missile.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'An invisible shield grants a +4 shield bonus to AC and negates magic missile.' },
  { id: 'burning-hands', name: 'Burning Hands', level: 1, school: 'Evocation', lists: ['arcane'], summary: '15-ft cone, 1d4/level fire.', cast: '1 standard action', comp: 'V, S', range: '15 ft cone', dur: 'Instantaneous', save: 'Reflex half', desc: 'A cone of searing flame deals 1d4 fire damage per caster level (max 5d4).' },
  { id: 'charm-person', name: 'Charm Person', level: 1, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'Make one humanoid a friend.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '1 hour/level', save: 'Will negates', desc: 'This charm makes a humanoid regard you as its trusted friend and ally.' },
  { id: 'sleep', name: 'Sleep', level: 1, school: 'Enchantment', lists: ['arcane', 'bard'], summary: '4 HD of creatures fall asleep.', cast: '1 round', comp: 'V, S, M', range: 'Medium', dur: '1 min/level', save: 'Will negates', desc: 'A magical slumber comes upon 4 HD of creatures in a 10-ft radius, lowest HD first. One of the strongest 1st-level spells — if you can spare the double slot.' },
  { id: 'grease', name: 'Grease', level: 1, school: 'Conjuration', lists: ['arcane', 'bard'], summary: 'Slick a surface or an object.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 min/level', save: 'Reflex; see text', desc: 'A layer of slippery grease covers a surface or object, causing creatures to slip and fall.' },
  { id: 'enlarge-person', name: 'Enlarge Person', level: 1, school: 'Transmutation', lists: ['arcane'], summary: 'Humanoid grows one size.', cast: '1 round', comp: 'V, S, M', range: 'Close', dur: '1 min/level', save: 'Fortitude negates', desc: 'The target grows to the next size category, gaining +2 Str, −2 Dex, and −1 to attack and AC.' },
  { id: 'identify', name: 'Identify', level: 1, school: 'Divination', lists: ['arcane'], summary: 'Learn a magic item’s properties.', cast: '1 standard action', comp: 'V, S, M', range: '60 ft', dur: '3 rounds/level', save: 'None', desc: 'This spell functions as detect magic, and you gain a +10 bonus on Spellcraft to identify magic auras.' },
  { id: 'chill-touch', name: 'Chill Touch', level: 1, school: 'Necromancy', lists: ['arcane'], summary: 'Touch attacks deal 1d6 and Str damage.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Fort/Will; see text', desc: 'You channel negative energy; each touch deals 1d6 negative energy damage and may cause 1 Str damage.' },
  { id: 'color-spray', name: 'Color Spray', level: 1, school: 'Illusion', lists: ['arcane'], summary: 'Cone stuns, blinds, knocks out.', cast: '1 standard action', comp: 'V, S, M', range: '15 ft cone', dur: 'Instantaneous', save: 'Will negates', desc: 'A vivid cone of light leaves weaker creatures unconscious, blinded, and stunned.' },
  { id: 'expeditious-retreat', name: 'Expeditious Retreat', level: 1, school: 'Transmutation', lists: ['arcane', 'bard'], summary: '+30 ft speed.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'Your base land speed increases by 30 feet.' },
  { id: 'protection-from-evil', name: 'Protection from Evil', level: 1, school: 'Abjuration', lists: ['arcane', 'divine'], summary: '+2 AC and saves vs evil.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains +2 deflection to AC and +2 resistance on saves against evil creatures, plus protection from mental control.' },

  // Divine level 1 (cleric)
  { id: 'cure-light-wounds', name: 'Cure Light Wounds', level: 1, school: 'Conjuration', lists: ['divine', 'druid', 'bard'], summary: 'Heal 1d8 + caster level.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Channeling positive energy, you cure 1d8 damage +1 per caster level (max +5).' },
  { id: 'bless', name: 'Bless', level: 1, school: 'Enchantment', lists: ['divine'], summary: 'Allies +1 attack and vs fear.', cast: '1 standard action', comp: 'V, S, DF', range: '50 ft', dur: '1 min/level', save: 'None', desc: 'Allies gain a +1 morale bonus on attack rolls and saves against fear.' },
  { id: 'shield-of-faith', name: 'Shield of Faith', level: 1, school: 'Abjuration', lists: ['divine'], summary: '+2 (or more) deflection AC.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'A shimmering field grants a +2 deflection bonus to AC, rising at higher caster levels.' },
  { id: 'divine-favor', name: 'Divine Favor', level: 1, school: 'Evocation', lists: ['divine'], summary: '+1/3 levels attack and damage.', cast: '1 standard action', comp: 'V, S, DF', range: 'Personal', dur: '1 minute', save: 'None', desc: 'You gain a +1 luck bonus per three caster levels (min +1) on attack and weapon damage rolls.' },

  // Druid level 1
  { id: 'entangle', name: 'Entangle', level: 1, school: 'Transmutation', lists: ['druid'], summary: 'Plants grapple in a 40-ft area.', cast: '1 standard action', comp: 'V, S, DF', range: 'Long', dur: '1 min/level', save: 'Reflex partial', desc: 'Grasses and vines wrap around creatures in the area, entangling them.' },
  { id: 'produce-flame', name: 'Produce Flame', level: 1, school: 'Evocation', lists: ['druid'], summary: 'Flame in hand, 1d6+level.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'Flames engulf your hand and can be hurled, dealing 1d6 +1 per caster level (max +5) fire damage.' },
];

export const spellById = new Map(SPELLS.map((s) => [s.id, s]));
