import type { SpellDef } from './model';

// Level 0-1 spells across the arcane/divine/druid/bard lists. Enough to exercise the
// spells step (filtering, opposition markers, spellbook picks) for the elf-wizard seed.
export const SPELLS: SpellDef[] = [
  // Cantrips (arcane 0)
  { id: 'acid-splash', name: 'Acid Splash', level: 0, school: 'Conjuration', lists: ['arcane'], summary: 'Ranged touch, 1d3 acid.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'You fire a small orb of acid at the target, dealing 1d3 acid damage on a successful ranged touch attack.' },
  { id: 'detect-magic', name: 'Detect Magic', level: 0, school: 'Divination', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Sense magical auras nearby.', cast: '1 standard action', comp: 'V, S', range: '60 ft cone', dur: 'Concentration, up to 1 min/level', save: 'None', desc: 'You detect magical auras, learning number, power, and location over up to three rounds of concentration.' },
  { id: 'light', name: 'Light', level: 0, school: 'Evocation', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Object shines like a torch.', cast: '1 standard action', comp: 'V, M/DF', range: 'Touch', dur: '10 min/level', save: 'None', desc: 'This spell causes a touched object to glow like a torch, shedding normal light in a 20-foot radius.' },
  { id: 'mage-hand', name: 'Mage Hand', level: 0, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Telekinetically move 5 lb.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Concentration', save: 'None', desc: 'You point at an object and can lift and move it at will, up to 5 pounds, within range.' },
  { id: 'prestidigitation', name: 'Prestidigitation', level: 0, school: 'Universal', lists: ['arcane', 'bard'], summary: 'Minor magical tricks.', cast: '1 standard action', comp: 'V, S', range: '10 ft', dur: '1 hour', save: 'None', desc: 'Perform simple magical effects: color, clean, chill, warm, flavor, or minor illusions.' },
  { id: 'ray-of-frost', name: 'Ray of Frost', level: 0, school: 'Evocation', lists: ['arcane'], summary: 'Ranged touch, 1d3 cold.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'A ray of freezing air and ice deals 1d3 cold damage on a ranged touch attack.' },
  { id: 'daze', name: 'Daze', level: 0, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'One humanoid loses its next action.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 round', save: 'Will negates', desc: 'A single humanoid of 4 HD or less is dazed for 1 round, taking no actions but suffering no penalty to AC.' },
  { id: 'read-magic', name: 'Read Magic', level: 0, school: 'Divination', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Read scrolls and spellbooks.', cast: '1 standard action', comp: 'V, S, F', range: 'Personal', dur: '10 min/level', save: 'None', desc: 'You can decipher magical inscriptions that would otherwise be unintelligible.' },
  { id: 'disrupt-undead', name: 'Disrupt Undead', level: 0, school: 'Necromancy', lists: ['arcane'], summary: 'Ranged touch, 1d6 vs undead.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'You channel positive energy in a ray, dealing 1d6 damage to a single undead creature.' },

  // Arcane level 1
  { id: 'magic-missile', name: 'Magic Missile', level: 1, school: 'Evocation', lists: ['arcane'], summary: '1d4+1 force, auto-hit; more missiles with level.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: 'Instantaneous', save: 'None', desc: 'A missile of magical energy darts forth and strikes its target, dealing 1d4+1 force damage. You gain additional missiles at higher levels.' },
  { id: 'mage-armor', name: 'Mage Armor', level: 1, school: 'Conjuration', lists: ['arcane'], summary: '+4 armor bonus for hours.', cast: '1 standard action', comp: 'V, S, F', range: 'Touch', dur: '1 hour/level', save: 'Will negates (harmless)', desc: 'An invisible but tangible field of force surrounds the subject, granting a +4 armor bonus to AC.' },
  { id: 'shield', name: 'Shield', level: 1, school: 'Abjuration', lists: ['arcane'], summary: '+4 shield bonus; blocks magic missile.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'An invisible shield grants a +4 shield bonus to AC and negates magic missile.' },
  { id: 'burning-hands', name: 'Burning Hands', level: 1, school: 'Evocation', lists: ['arcane'], summary: '15-ft cone, 1d4/level fire.', cast: '1 standard action', comp: 'V, S', range: '15 ft cone', dur: 'Instantaneous', save: 'Reflex half', desc: 'A cone of searing flame deals 1d4 fire damage per caster level (max 5d4).' },
  { id: 'charm-person', name: 'Charm Person', level: 1, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'Make one humanoid a friend.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '1 hour/level', save: 'Will negates', desc: 'This charm makes a humanoid regard you as its trusted friend and ally.' },
  { id: 'sleep', name: 'Sleep', level: 1, school: 'Enchantment', lists: ['arcane', 'bard'], summary: '4 HD of creatures fall asleep.', cast: '1 round', comp: 'V, S, M', range: 'Medium', dur: '1 min/level', save: 'Will negates', desc: 'A magical slumber comes upon 4 HD of creatures in a 10-ft radius, lowest HD first. One of the strongest 1st-level spells — if you can spare the double slot.' },
  { id: 'grease', name: 'Grease', level: 1, school: 'Conjuration', lists: ['arcane', 'bard'], summary: 'Slick a surface or an object.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 min/level', save: 'Reflex; see text', desc: 'A layer of slippery grease covers a surface or object, causing creatures to slip and fall.' },
  { id: 'enlarge-person', name: 'Enlarge Person', level: 1, school: 'Transmutation', lists: ['arcane'], summary: 'Humanoid grows one size.', cast: '1 round', comp: 'V, S, M', range: 'Close', dur: '1 min/level', save: 'Fortitude negates', desc: 'The target grows to the next size category, gaining +2 Str, −2 Dex, and −1 to attack and AC.' },
  { id: 'identify', name: 'Identify', level: 1, school: 'Divination', lists: ['arcane'], summary: 'Learn a magic item’s properties.', cast: '1 standard action', comp: 'V, S, M', range: '60 ft', dur: '3 rounds/level', save: 'None', desc: 'This spell functions as detect magic, and you gain a +10 bonus on Spellcraft to identify magic auras.' },
  { id: 'chill-touch', name: 'Chill Touch', level: 1, school: 'Necromancy', lists: ['arcane'], summary: 'Touch attacks deal 1d6 and Str damage.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Fort/Will; see text', desc: 'You channel negative energy; each touch deals 1d6 negative energy damage and may cause 1 Str damage.' },
  { id: 'color-spray', name: 'Color Spray', level: 1, school: 'Illusion', lists: ['arcane'], summary: 'Cone stuns, blinds, knocks out.', cast: '1 standard action', comp: 'V, S, M', range: '15 ft cone', dur: 'Instantaneous', save: 'Will negates', desc: 'A vivid cone of light leaves weaker creatures unconscious, blinded, and stunned.' },
  { id: 'expeditious-retreat', name: 'Expeditious Retreat', level: 1, school: 'Transmutation', lists: ['arcane', 'bard'], summary: '+30 ft speed.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'Your base land speed increases by 30 feet.' },
  { id: 'protection-from-evil', name: 'Protection from Evil', level: 1, school: 'Abjuration', lists: ['arcane', 'divine'], summary: '+2 AC and saves vs evil.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains +2 deflection to AC and +2 resistance on saves against evil creatures, plus protection from mental control.' },

  // Divine level 1 (cleric)
  { id: 'cure-light-wounds', name: 'Cure Light Wounds', level: 1, school: 'Conjuration', lists: ['divine', 'druid', 'bard'], summary: 'Heal 1d8 + caster level.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Channeling positive energy, you cure 1d8 damage +1 per caster level (max +5).' },
  { id: 'bless', name: 'Bless', level: 1, school: 'Enchantment', lists: ['divine'], summary: 'Allies +1 attack and vs fear.', cast: '1 standard action', comp: 'V, S, DF', range: '50 ft', dur: '1 min/level', save: 'None', desc: 'Allies gain a +1 morale bonus on attack rolls and saves against fear.' },
  { id: 'shield-of-faith', name: 'Shield of Faith', level: 1, school: 'Abjuration', lists: ['divine'], summary: '+2 (or more) deflection AC.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'A shimmering field grants a +2 deflection bonus to AC, rising at higher caster levels.' },
  { id: 'divine-favor', name: 'Divine Favor', level: 1, school: 'Evocation', lists: ['divine'], summary: '+1/3 levels attack and damage.', cast: '1 standard action', comp: 'V, S, DF', range: 'Personal', dur: '1 minute', save: 'None', desc: 'You gain a +1 luck bonus per three caster levels (min +1) on attack and weapon damage rolls.' },

  // Druid level 1
  { id: 'entangle', name: 'Entangle', level: 1, school: 'Transmutation', lists: ['druid'], summary: 'Plants grapple in a 40-ft area.', cast: '1 standard action', comp: 'V, S, DF', range: 'Long', dur: '1 min/level', save: 'Reflex partial', desc: 'Grasses and vines wrap around creatures in the area, entangling them.' },
  { id: 'produce-flame', name: 'Produce Flame', level: 1, school: 'Evocation', lists: ['druid'], summary: 'Flame in hand, 1d6+level.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'Flames engulf your hand and can be hurled, dealing 1d6 +1 per caster level (max +5) fire damage.' },

  // Arcane level 2
  { id: 'scorching-ray', name: 'Scorching Ray', level: 2, school: 'Evocation', lists: ['arcane'], summary: 'Ranged touch rays, 4d6 fire each.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'You fire a ray (more at higher level) dealing 4d6 fire damage on a ranged touch attack.' },
  { id: 'invisibility', name: 'Invisibility', level: 2, school: 'Illusion', lists: ['arcane', 'bard'], summary: 'Turn a creature invisible.', cast: '1 standard action', comp: 'V, S, M', range: 'Personal or touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The target becomes invisible until it attacks or the duration ends.' },
  { id: 'mirror-image', name: 'Mirror Image', level: 2, school: 'Illusion', lists: ['arcane', 'bard'], summary: 'Decoy duplicates absorb attacks.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'Several illusory duplicates of you appear, each of which can absorb an attack meant for you.' },
  { id: 'web', name: 'Web', level: 2, school: 'Conjuration', lists: ['arcane'], summary: 'Fill an area with sticky webs.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: '10 min/level', save: 'Reflex negates', desc: 'Thick, sticky webbing fills the area, entangling creatures within it.' },
  { id: 'glitterdust', name: 'Glitterdust', level: 2, school: 'Conjuration', lists: ['arcane', 'bard'], summary: 'Blinds and outlines foes.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: '1 round/level', save: 'Will negates (blindness)', desc: 'A cloud of golden particles covers everyone in the area, blinding creatures and coating invisible ones.' },
  { id: 'bulls-strength', name: "Bull's Strength", level: 2, school: 'Transmutation', lists: ['arcane', 'divine', 'druid'], summary: '+4 enhancement to Strength.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains a +4 enhancement bonus to Strength.' },
  { id: 'blur', name: 'Blur', level: 2, school: 'Illusion', lists: ['arcane', 'bard'], summary: '20% miss chance vs attacks.', cast: '1 standard action', comp: 'V', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: "The subject's outline is blurred, granting concealment (20% miss chance)." },
  { id: 'acid-arrow', name: 'Acid Arrow', level: 2, school: 'Conjuration', lists: ['arcane'], summary: '2d4 acid, plus ongoing.', cast: '1 standard action', comp: 'V, S, M, F', range: 'Long', dur: '1 round + 1/3 levels', save: 'None', desc: 'A magical arrow of acid deals 2d4 damage on hit and again on following rounds.' },
  { id: 'see-invisibility', name: 'See Invisibility', level: 2, school: 'Divination', lists: ['arcane', 'bard'], summary: 'See invisible creatures.', cast: '1 standard action', comp: 'V, S, M', range: 'Personal', dur: '10 min/level', save: 'None', desc: 'You can see creatures and objects that are invisible as if they were visible.' },
  { id: 'levitate', name: 'Levitate', level: 2, school: 'Transmutation', lists: ['arcane'], summary: 'Move a subject up and down.', cast: '1 standard action', comp: 'V, S, F', range: 'Personal or close', dur: '1 min/level', save: 'None', desc: 'You move yourself or a willing subject up and down as you wish, up to 20 feet per round.' },
  { id: 'resist-energy', name: 'Resist Energy', level: 2, school: 'Abjuration', lists: ['arcane', 'divine', 'druid'], summary: 'Resist 10+ of one energy type.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'The subject gains resistance 10 (more at higher level) to a chosen energy type.' },
  { id: 'hideous-laughter', name: 'Hideous Laughter', level: 2, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'A creature falls down laughing.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 round/level', save: 'Will negates', desc: 'The subject perceives everything as hilarious and collapses into laughter, unable to act.' },

  // Arcane level 3
  { id: 'fireball', name: 'Fireball', level: 3, school: 'Evocation', lists: ['arcane'], summary: '20-ft burst, 1d6/level fire.', cast: '1 standard action', comp: 'V, S, M', range: 'Long', dur: 'Instantaneous', save: 'Reflex half', desc: 'A burst of flame deals 1d6 fire damage per caster level (max 10d6) to all in a 20-ft-radius spread.' },
  { id: 'lightning-bolt', name: 'Lightning Bolt', level: 3, school: 'Evocation', lists: ['arcane'], summary: '120-ft line, 1d6/level electricity.', cast: '1 standard action', comp: 'V, S, M', range: '120 ft line', dur: 'Instantaneous', save: 'Reflex half', desc: 'A stroke of lightning deals 1d6 electricity per caster level (max 10d6) to every creature in a line.' },
  { id: 'fly', name: 'Fly', level: 3, school: 'Transmutation', lists: ['arcane'], summary: 'Fly speed 60 ft.', cast: '1 standard action', comp: 'V, S, F', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains a fly speed of 60 feet (40 if heavily loaded) with good maneuverability.' },
  { id: 'haste', name: 'Haste', level: 3, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Allies gain an extra attack and speed.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 round/level', save: 'Fortitude negates (harmless)', desc: 'One creature per level gains an extra attack, +1 to attack and AC and Reflex, and +30 ft speed.' },
  { id: 'dispel-magic', name: 'Dispel Magic', level: 3, school: 'Abjuration', lists: ['arcane', 'divine', 'druid'], summary: 'End or suppress magic.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: 'Instantaneous', save: 'None', desc: 'You can end ongoing spells, counter another caster, or suppress a magic item with a caster level check.' },
  { id: 'displacement', name: 'Displacement', level: 3, school: 'Illusion', lists: ['arcane', 'bard'], summary: '50% miss chance vs attacks.', cast: '1 standard action', comp: 'V, M', range: 'Touch', dur: '1 round/level', save: 'Will negates (harmless)', desc: 'The subject appears to be about 2 feet from its true location, granting a 50% miss chance.' },
  { id: 'vampiric-touch', name: 'Vampiric Touch', level: 3, school: 'Necromancy', lists: ['arcane'], summary: 'Touch drains HP to you.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'Your touch deals 1d6 per two caster levels; you gain the damage dealt as temporary hit points.' },
  { id: 'stinking-cloud', name: 'Stinking Cloud', level: 3, school: 'Conjuration', lists: ['arcane'], summary: 'Nauseating cloud.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: '1 round/level', save: 'Fortitude negates (nausea)', desc: 'A bank of foul vapor nauseates creatures caught within it.' },
  { id: 'protection-from-energy', name: 'Protection from Energy', level: 3, school: 'Abjuration', lists: ['arcane', 'divine', 'druid'], summary: 'Absorb a lot of one energy type.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'The warded creature ignores damage from a chosen energy type until the spell absorbs 12/level.' },

  // Divine level 2
  { id: 'cure-moderate-wounds', name: 'Cure Moderate Wounds', level: 2, school: 'Conjuration', lists: ['divine', 'druid', 'bard'], summary: 'Heal 2d8 + caster level.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Positive energy cures 2d8 damage +1 per caster level (max +10).' },
  { id: 'hold-person', name: 'Hold Person', level: 2, school: 'Enchantment', lists: ['divine', 'arcane', 'bard'], summary: 'Paralyze one humanoid.', cast: '1 standard action', comp: 'V, S, F/DF', range: 'Medium', dur: '1 round/level', save: 'Will negates', desc: 'The target humanoid is paralyzed, though it may attempt a new save each round.' },
  { id: 'spiritual-weapon', name: 'Spiritual Weapon', level: 2, school: 'Evocation', lists: ['divine'], summary: 'A floating weapon attacks foes.', cast: '1 standard action', comp: 'V, S, DF', range: 'Medium', dur: '1 round/level', save: 'None', desc: "A weapon of force attacks foes at your direction, using your BAB and Wisdom." },
  { id: 'silence', name: 'Silence', level: 2, school: 'Illusion', lists: ['divine', 'bard'], summary: 'No sound in an area.', cast: '1 standard action', comp: 'V, S', range: 'Long', dur: '1 round/level', save: 'Will negates; see text', desc: 'An area is made utterly silent, preventing sound and blocking verbal spellcasting within it.' },
  { id: 'aid', name: 'Aid', level: 2, school: 'Enchantment', lists: ['divine'], summary: '+1 attack, +vs fear, temp HP.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 min/level', save: 'None', desc: 'The subject gains a +1 morale bonus on attacks and vs fear, plus 1d8 temporary hit points.' },
  { id: 'lesser-restoration', name: 'Lesser Restoration', level: 2, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'Heal ability damage.', cast: '3 rounds', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'Dispels magical ability penalties and heals ability damage, plus fatigue or exhaustion.' },

  // Divine level 3
  { id: 'cure-serious-wounds', name: 'Cure Serious Wounds', level: 3, school: 'Conjuration', lists: ['divine', 'druid', 'bard'], summary: 'Heal 3d8 + caster level.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Positive energy cures 3d8 damage +1 per caster level (max +15).' },
  { id: 'prayer', name: 'Prayer', level: 3, school: 'Enchantment', lists: ['divine', 'bard'], summary: 'Allies +1, enemies −1.', cast: '1 standard action', comp: 'V, S, DF', range: '40 ft', dur: '1 round/level', save: 'None', desc: 'Allies gain +1 on most rolls while enemies take −1, within the burst around you.' },
  { id: 'searing-light', name: 'Searing Light', level: 3, school: 'Evocation', lists: ['divine'], summary: 'Ray, extra vs undead.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: 'Instantaneous', save: 'None', desc: 'A ray of divine light deals 1d8 per two levels (more to undead) on a ranged touch attack.' },
  { id: 'bestow-curse', name: 'Bestow Curse', level: 3, school: 'Necromancy', lists: ['divine', 'arcane'], summary: 'Curse a creature.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Permanent', save: 'Will negates', desc: 'You lay a curse: an ability penalty, a chance to lose actions, or a −4 on rolls.' },

  // Druid level 2-3
  { id: 'barkskin', name: 'Barkskin', level: 2, school: 'Transmutation', lists: ['druid'], summary: '+2 (or more) natural armor.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '10 min/level', save: 'None', desc: "The subject's skin toughens, granting a +2 (or better) enhancement to natural armor." },
  { id: 'flaming-sphere', name: 'Flaming Sphere', level: 2, school: 'Evocation', lists: ['druid', 'arcane'], summary: 'Rolling ball of fire.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Medium', dur: '1 round/level', save: 'Reflex negates', desc: 'A burning sphere rolls where you direct, dealing 3d6 fire damage to creatures it touches.' },
  { id: 'call-lightning', name: 'Call Lightning', level: 3, school: 'Evocation', lists: ['druid'], summary: 'Call bolts from the sky.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '1 min/level', save: 'Reflex half', desc: 'You call down bolts of lightning (3d6 each, more outdoors in a storm), one per round.' },
  { id: 'neutralize-poison', name: 'Neutralize Poison', level: 3, school: 'Conjuration', lists: ['druid', 'divine', 'bard'], summary: 'Detoxify a creature or object.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'Neutralizes poisons in a creature or object, preventing further effect.' },
];

export const spellById = new Map(SPELLS.map((s) => [s.id, s]));
