// What a spell is *for*, as authored data.
//
// The playstyle fingerprint classifies a caster by what their chosen spells do. Most of that can
// be read off structure the catalogue already carries — a spell with a `damage` formula is doing
// damage, one whose save reads "(harmless)" is aimed at your own side — and `spellLean` in
// engine/fingerprint.ts does exactly that. Where structure runs out it falls back to the school,
// and the school is a poor proxy: Evocation covers both Fireball and Light, Transmutation covers
// both Bull's Strength and Baleful Polymorph.
//
// This file is the correction. It lists only the spells the structural rules get wrong, so the
// table stays small enough to keep honest — a spell absent here is one the rules already place
// correctly. Adding a spell to the catalogue needs no entry here unless its school misleads.
//
// The judgements are about table use, not rules text, and reasonable people will disagree on the
// edges (is Dimension Door escape or control?). They are grouped by that reasoning below so a
// disagreement is easy to find and change.

/** What a spell is mainly used for. */
export type SpellRole = 'blaster' | 'controller' | 'buffer' | 'healer' | 'utility';

/** Spell id → role, overriding the structural classification. */
export const SPELL_ROLE_OVERRIDES: Record<string, SpellRole> = {
  // --- Abjuration reads as "buffer" by default, but a third of it is locks, wards and answers ---
  'dispel-magic': 'utility',
  'greater-dispel-magic': 'utility',
  'mages-disjunction': 'utility',
  alarm: 'utility',
  'hold-portal': 'utility',
  'arcane-lock': 'utility',
  'obscure-object': 'utility',
  'undetectable-alignment': 'utility',
  'mages-private-sanctum': 'utility',
  sequester: 'utility',
  'break-enchantment': 'healer',
  'remove-curse': 'healer',
  atonement: 'healer',
  freedom: 'healer',
  banishment: 'controller',
  dismissal: 'controller',
  'antimagic-field': 'controller',
  repulsion: 'controller',
  forbiddance: 'controller',
  'guards-and-wards': 'controller',
  'dimensional-anchor': 'controller',
  'dimensional-lock': 'controller',
  'prismatic-wall': 'controller',
  'repel-metal-or-stone': 'controller',
  imprisonment: 'controller',
  'glyph-of-warding': 'controller',
  'greater-glyph-of-warding': 'controller',
  'explosive-runes': 'blaster',
  'fire-trap': 'blaster',

  // --- Conjuration defaults to control, which fits the clouds and the summons but not travel,
  // creation or resurrection ---
  'dimension-door': 'utility',
  'plane-shift': 'utility',
  teleport: 'utility',
  'greater-teleport': 'utility',
  'teleport-object': 'utility',
  'teleportation-circle': 'utility',
  'interplanetary-teleport': 'utility',
  'transport-via-plants': 'utility',
  'word-of-recall': 'utility',
  'phase-door': 'utility',
  refuge: 'utility',
  gate: 'utility',
  'create-water': 'utility',
  'create-food-and-water': 'utility',
  'minor-creation': 'utility',
  'major-creation': 'utility',
  'unseen-servant': 'utility',
  mount: 'utility',
  'phantom-steed': 'utility',
  'secure-shelter': 'utility',
  'secret-chest': 'utility',
  'instant-summons': 'utility',
  'mages-magnificent-mansion': 'utility',
  'mages-faithful-hound': 'utility',
  'summon-instrument': 'utility',
  'lesser-planar-ally': 'utility',
  'planar-ally': 'utility',
  'greater-planar-ally': 'utility',
  'lesser-planar-binding': 'utility',
  'planar-binding': 'utility',
  'greater-planar-binding': 'utility',
  'raise-dead': 'healer',
  resurrection: 'healer',
  'true-resurrection': 'healer',
  'greater-restoration': 'healer',
  'heroes-feast': 'buffer',
  'fire-seeds': 'blaster',
  'incendiary-cloud': 'blaster',
  'storm-of-vengeance': 'blaster',

  // --- Enchantment is almost entirely control; these are the exceptions ---
  rage: 'buffer',
  'zone-of-truth': 'utility',
  'animal-messenger': 'utility',
  'modify-memory': 'utility',

  // --- Evocation defaults to blasting, but it also owns light, darkness, walls and force ---
  light: 'utility',
  'dancing-lights': 'utility',
  daylight: 'utility',
  'continual-flame': 'utility',
  'floating-disk': 'utility',
  shatter: 'utility',
  sending: 'utility',
  'tiny-hut': 'utility',
  'helping-hand': 'utility',
  miracle: 'utility',
  darkness: 'controller',
  'deeper-darkness': 'controller',
  flare: 'controller',
  'faerie-fire': 'controller',
  'gust-of-wind': 'controller',
  'wind-wall': 'controller',
  'wall-of-force': 'controller',
  'wall-of-ice': 'controller',
  forcecage: 'controller',
  'resilient-sphere': 'controller',
  'telekinetic-sphere': 'controller',
  'interposing-hand': 'controller',
  'forceful-hand': 'controller',
  'grasping-hand': 'controller',
  'blade-barrier': 'controller',
  earthquake: 'controller',
  whirlwind: 'controller',
  'holy-word': 'controller',
  blasphemy: 'controller',
  'word-of-chaos': 'controller',
  dictum: 'controller',
  consecrate: 'buffer',
  desecrate: 'buffer',
  hallow: 'buffer',
  unhallow: 'buffer',
  'holy-sword': 'buffer',

  // --- Illusion splits cleanly: the patterns control, the images inform ---
  'ghost-sound': 'utility',
  'silent-image': 'utility',
  'minor-image': 'utility',
  'major-image': 'utility',
  'persistent-image': 'utility',
  'permanent-image': 'utility',
  'programmed-image': 'utility',
  'project-image': 'utility',
  'magic-mouth': 'utility',
  'magic-aura': 'utility',
  ventriloquism: 'utility',
  misdirection: 'utility',
  'false-vision': 'utility',
  screen: 'utility',
  'phantom-trap': 'utility',
  'illusory-script': 'utility',
  'illusory-wall': 'utility',
  'hallucinatory-terrain': 'utility',
  'mirage-arcana': 'utility',
  seeming: 'utility',
  veil: 'utility',
  mislead: 'utility',
  dream: 'utility',
  'shadow-walk': 'utility',
  simulacrum: 'utility',
  // The shadow spells inherit the role of whatever they mimic, so only the two that copy an
  // evocation are blasts. Shadow conjuration, its greater version and shades copy conjurations,
  // which is control — the Illusion default already — so they need no entry.
  'shadow-evocation': 'blaster',
  'greater-shadow-evocation': 'blaster',

  // --- Necromancy defaults to control, correct for the fear and enfeeblement half; the other
  // half kills outright ---
  harm: 'blaster',
  'finger-of-death': 'blaster',
  destruction: 'blaster',
  'slay-living': 'blaster',
  // Circle of death, undeath to death, wail of the banshee and symbol of death are NOT listed:
  // their saves negate outright, so they behave like control rather than damage, and Necromancy's
  // default is already control. Only the ones that leave damage behind on a successful save are
  // overridden to blaster.
  'energy-drain': 'blaster',
  bleed: 'blaster',
  blight: 'blaster',
  'mass-inflict-light-wounds': 'blaster',
  'mass-inflict-moderate-wounds': 'blaster',
  'mass-inflict-serious-wounds': 'blaster',
  'mass-inflict-critical-wounds': 'blaster',
  'speak-with-dead': 'utility',
  deathwatch: 'utility',
  'gentle-repose': 'utility',
  'curse-water': 'utility',
  'magic-jar': 'utility',
  clone: 'utility',
  'astral-projection': 'utility',
  'soul-bind': 'utility',

  // --- Transmutation defaults to buffing, right for the stat and weapon spells, wrong for the
  // terrain-shaping, the polymorph-as-removal, and the whole toolbox ---
  'mage-hand': 'utility',
  message: 'utility',
  mending: 'utility',
  'open-close': 'utility',
  'purify-food-and-drink': 'utility',
  'animate-rope': 'utility',
  knock: 'utility',
  'rope-trick': 'utility',
  'warp-wood': 'utility',
  'gaseous-form': 'utility',
  passwall: 'utility',
  'wood-shape': 'utility',
  'stone-shape': 'utility',
  fabricate: 'utility',
  'plant-growth': 'utility',
  'diminish-plants': 'utility',
  'control-weather': 'utility',
  erase: 'utility',
  'secret-page': 'utility',
  'bless-water': 'utility',
  'make-whole': 'utility',
  'whispering-wind': 'utility',
  quench: 'utility',
  'sculpt-sound': 'utility',
  'shrink-item': 'utility',
  awaken: 'utility',
  ironwood: 'utility',
  liveoak: 'utility',
  'move-earth': 'utility',
  spellstaff: 'utility',
  changestaff: 'utility',
  etherealness: 'utility',
  entangle: 'controller',
  slow: 'controller',
  'baleful-polymorph': 'controller',
  'flesh-to-stone': 'controller',
  'reverse-gravity': 'controller',
  pyrotechnics: 'controller',
  'spike-growth': 'controller',
  'spike-stones': 'controller',
  telekinesis: 'controller',
  'animate-objects': 'controller',
  'control-winds': 'controller',
  'control-water': 'controller',
  'soften-earth-and-stone': 'controller',
  'command-plants': 'controller',
  'control-plants': 'controller',
  'animate-plants': 'controller',
  'repel-wood': 'controller',
  'giant-vermin': 'controller',
  snare: 'controller',
  'transmute-mud-to-rock': 'controller',
  'transmute-rock-to-mud': 'controller',
  'transmute-metal-to-wood': 'controller',
  'polymorph-any-object': 'controller',
  'temporal-stasis': 'controller',
  'heat-metal': 'blaster',
  'chill-metal': 'blaster',
  'rusting-grasp': 'blaster',
  goodberry: 'healer',
  reincarnate: 'healer',
  'stone-to-flesh': 'healer',
};
