import type { SpellDef } from './model';
import { SPELL_ATTACKERS, SPELL_BUFFS, SPELL_DAMAGE } from './spell-effects';

// Level 0-1 spells across the arcane/divine/druid/bard lists. Enough to exercise the
// spells step (filtering, opposition markers, spellbook picks) for the elf-wizard seed.
export const SPELLS: SpellDef[] = [
  // Cantrips (arcane 0)
  { id: 'acid-splash', name: 'Acid Splash', level: 0, school: 'Conjuration', lists: ['arcane'], summary: 'Ranged touch, 1d3 acid.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'You fire a small orb of acid at the target, dealing 1d3 acid damage on a successful ranged touch attack.' },
  { id: 'detect-magic', name: 'Detect Magic', level: 0, school: 'Divination', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Sense magical auras nearby.', cast: '1 standard action', comp: 'V, S', range: '60 ft cone', dur: 'Concentration, up to 1 min/level', save: 'None', desc: 'You detect magical auras, learning number, power, and location over up to three rounds of concentration.' },
  { id: 'light', name: 'Light', level: 0, school: 'Evocation', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Object shines like a torch.', cast: '1 standard action', comp: 'V, M/DF', range: 'Touch', dur: '10 min/level', save: 'None', desc: 'This spell causes a touched object to glow like a torch, shedding normal light in a 20-foot radius.' },
  { id: 'mage-hand', name: 'Mage Hand', level: 0, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Telekinetically move 5 lb.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Concentration', save: 'None', desc: 'You point at an object and can lift and move it at will, up to 5 pounds, within range.' },
  { id: 'prestidigitation', name: 'Prestidigitation', level: 0, school: 'Universal', lists: ['arcane', 'bard'], summary: 'Minor magical tricks.', cast: '1 standard action', comp: 'V, S', range: '10 ft', dur: '1 hour', save: 'None', desc: 'Perform simple magical effects: color, clean, chill, warm, flavor, or minor illusions.' },
  { id: 'ray-of-frost', name: 'Ray of Frost', level: 0, school: 'Evocation', lists: ['arcane'], summary: 'Ranged touch, 1d3 cold.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'A ray of freezing air and ice deals 1d3 cold damage on a ranged touch attack.' },
  { id: 'daze', name: 'Daze', level: 0, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'One humanoid loses its next action.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 round', save: 'Will negates', desc: 'A single humanoid of 4 HD or less is dazed for 1 round, taking no actions but suffering no penalty to AC.' },
  { id: 'read-magic', name: 'Read Magic', level: 0, school: 'Divination', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Read scrolls and spellbooks.', cast: '1 standard action', comp: 'V, S, F', range: 'Personal', dur: '10 min/level', save: 'None', desc: 'You can decipher magical inscriptions that would otherwise be unintelligible.' },
  { id: 'disrupt-undead', name: 'Disrupt Undead', level: 0, school: 'Necromancy', lists: ['arcane'], summary: 'Ranged touch, 1d6 vs undead.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'You channel positive energy in a ray, dealing 1d6 damage to a single undead creature.' },

  // Arcane level 1
  { id: 'magic-missile', name: 'Magic Missile', level: 1, school: 'Evocation', lists: ['arcane'], summary: '1d4+1 force, auto-hit; more missiles with level.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: 'Instantaneous', save: 'None', desc: 'A missile of magical energy darts forth and strikes its target, dealing 1d4+1 force damage. You gain additional missiles at higher levels.' },
  { id: 'mage-armor', name: 'Mage Armor', level: 1, school: 'Conjuration', lists: ['arcane'], summary: '+4 armor bonus for hours.', cast: '1 standard action', comp: 'V, S, F', range: 'Touch', dur: '1 hour/level', save: 'Will negates (harmless)', desc: 'An invisible but tangible field of force surrounds the subject, granting a +4 armor bonus to AC.' },
  { id: 'shield', name: 'Shield', level: 1, school: 'Abjuration', lists: ['arcane'], summary: '+4 shield bonus; blocks magic missile.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'An invisible shield grants a +4 shield bonus to AC and negates magic missile.' },
  { id: 'burning-hands', name: 'Burning Hands', level: 1, school: 'Evocation', lists: ['arcane'], summary: '15-ft cone, 1d4/level fire.', cast: '1 standard action', comp: 'V, S', range: '15 ft cone', dur: 'Instantaneous', save: 'Reflex half', desc: 'A cone of searing flame deals 1d4 fire damage per caster level (max 5d4).' },
  { id: 'charm-person', name: 'Charm Person', level: 1, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'Make one humanoid a friend.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '1 hour/level', save: 'Will negates', desc: 'This charm makes a humanoid regard you as its trusted friend and ally.' },
  { id: 'sleep', name: 'Sleep', level: 1, school: 'Enchantment', lists: ['arcane', 'bard'], summary: '4 HD of creatures fall asleep.', cast: '1 round', comp: 'V, S, M', range: 'Medium', dur: '1 min/level', save: 'Will negates', desc: 'A magical slumber comes upon 4 HD of creatures in a 10-ft radius, lowest HD first. One of the strongest 1st-level spells — if you can spare the double slot.' },
  { id: 'grease', name: 'Grease', level: 1, school: 'Conjuration', lists: ['arcane', 'bard'], summary: 'Slick a surface or an object.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 min/level', save: 'Reflex; see text', desc: 'A layer of slippery grease covers a surface or object, causing creatures to slip and fall.' },
  { id: 'enlarge-person', name: 'Enlarge Person', level: 1, school: 'Transmutation', lists: ['arcane'], summary: 'Humanoid grows one size.', cast: '1 round', comp: 'V, S, M', range: 'Close', dur: '1 min/level', save: 'Fortitude negates', desc: 'The target grows to the next size category, gaining +2 Str, −2 Dex, and −1 to attack and AC.' },
  { id: 'identify', name: 'Identify', level: 1, school: 'Divination', lists: ['arcane'], summary: 'Learn a magic item’s properties.', cast: '1 standard action', comp: 'V, S, M', range: '60 ft', dur: '3 rounds/level', save: 'None', desc: 'This spell functions as detect magic, and you gain a +10 bonus on Spellcraft to identify magic auras.' },
  { id: 'chill-touch', name: 'Chill Touch', level: 1, school: 'Necromancy', lists: ['arcane'], summary: 'Touch attacks deal 1d6 and Str damage.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Fort/Will; see text', desc: 'You channel negative energy; each touch deals 1d6 negative energy damage and may cause 1 Str damage.' },
  { id: 'color-spray', name: 'Color Spray', level: 1, school: 'Illusion', lists: ['arcane'], summary: 'Cone stuns, blinds, knocks out.', cast: '1 standard action', comp: 'V, S, M', range: '15 ft cone', dur: 'Instantaneous', save: 'Will negates', desc: 'A vivid cone of light leaves weaker creatures unconscious, blinded, and stunned.' },
  { id: 'expeditious-retreat', name: 'Expeditious Retreat', level: 1, school: 'Transmutation', lists: ['arcane', 'bard'], summary: '+30 ft speed.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'Your base land speed increases by 30 feet.' },
  { id: 'protection-from-evil', name: 'Protection from Evil', level: 1, school: 'Abjuration', lists: ['arcane', 'divine'], summary: '+2 AC and saves vs evil.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains +2 deflection to AC and +2 resistance on saves against evil creatures, plus protection from mental control.' },

  // Divine level 1 (cleric)
  { id: 'cure-light-wounds', name: 'Cure Light Wounds', level: 1, school: 'Conjuration', lists: ['divine', 'druid', 'bard'], summary: 'Heal 1d8 + caster level.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Channeling positive energy, you cure 1d8 damage +1 per caster level (max +5).' },
  { id: 'bless', name: 'Bless', level: 1, school: 'Enchantment', lists: ['divine'], summary: 'Allies +1 attack and vs fear.', cast: '1 standard action', comp: 'V, S, DF', range: '50 ft', dur: '1 min/level', save: 'None', desc: 'Allies gain a +1 morale bonus on attack rolls and saves against fear.' },
  { id: 'shield-of-faith', name: 'Shield of Faith', level: 1, school: 'Abjuration', lists: ['divine'], summary: '+2 (or more) deflection AC.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'A shimmering field grants a +2 deflection bonus to AC, rising at higher caster levels.' },
  { id: 'divine-favor', name: 'Divine Favor', level: 1, school: 'Evocation', lists: ['divine'], summary: '+1/3 levels attack and damage.', cast: '1 standard action', comp: 'V, S, DF', range: 'Personal', dur: '1 minute', save: 'None', desc: 'You gain a +1 luck bonus per three caster levels (min +1) on attack and weapon damage rolls.' },

  // Druid level 1
  { id: 'entangle', name: 'Entangle', level: 1, school: 'Transmutation', lists: ['druid'], summary: 'Plants grapple in a 40-ft area.', cast: '1 standard action', comp: 'V, S, DF', range: 'Long', dur: '1 min/level', save: 'Reflex partial', desc: 'Grasses and vines wrap around creatures in the area, entangling them.' },
  { id: 'produce-flame', name: 'Produce Flame', level: 1, school: 'Evocation', lists: ['druid'], summary: 'Flame in hand, 1d6+level.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'Flames engulf your hand and can be hurled, dealing 1d6 +1 per caster level (max +5) fire damage.' },

  // Arcane level 2
  { id: 'scorching-ray', name: 'Scorching Ray', level: 2, school: 'Evocation', lists: ['arcane'], summary: 'Ranged touch rays, 4d6 fire each.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'You fire a ray (more at higher level) dealing 4d6 fire damage on a ranged touch attack.' },
  { id: 'invisibility', name: 'Invisibility', level: 2, school: 'Illusion', lists: ['arcane', 'bard'], summary: 'Turn a creature invisible.', cast: '1 standard action', comp: 'V, S, M', range: 'Personal or touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The target becomes invisible until it attacks or the duration ends.' },
  { id: 'mirror-image', name: 'Mirror Image', level: 2, school: 'Illusion', lists: ['arcane', 'bard'], summary: 'Decoy duplicates absorb attacks.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'Several illusory duplicates of you appear, each of which can absorb an attack meant for you.' },
  { id: 'web', name: 'Web', level: 2, school: 'Conjuration', lists: ['arcane'], summary: 'Fill an area with sticky webs.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: '10 min/level', save: 'Reflex negates', desc: 'Thick, sticky webbing fills the area, entangling creatures within it.' },
  { id: 'glitterdust', name: 'Glitterdust', level: 2, school: 'Conjuration', lists: ['arcane', 'bard'], summary: 'Blinds and outlines foes.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: '1 round/level', save: 'Will negates (blindness)', desc: 'A cloud of golden particles covers everyone in the area, blinding creatures and coating invisible ones.' },
  { id: 'bulls-strength', name: "Bull's Strength", level: 2, school: 'Transmutation', lists: ['arcane', 'divine', 'druid'], summary: '+4 enhancement to Strength.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains a +4 enhancement bonus to Strength.' },
  { id: 'blur', name: 'Blur', level: 2, school: 'Illusion', lists: ['arcane', 'bard'], summary: '20% miss chance vs attacks.', cast: '1 standard action', comp: 'V', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: "The subject's outline is blurred, granting concealment (20% miss chance)." },
  { id: 'acid-arrow', name: 'Acid Arrow', level: 2, school: 'Conjuration', lists: ['arcane'], summary: '2d4 acid, plus ongoing.', cast: '1 standard action', comp: 'V, S, M, F', range: 'Long', dur: '1 round + 1/3 levels', save: 'None', desc: 'A magical arrow of acid deals 2d4 damage on hit and again on following rounds.' },
  { id: 'see-invisibility', name: 'See Invisibility', level: 2, school: 'Divination', lists: ['arcane', 'bard'], summary: 'See invisible creatures.', cast: '1 standard action', comp: 'V, S, M', range: 'Personal', dur: '10 min/level', save: 'None', desc: 'You can see creatures and objects that are invisible as if they were visible.' },
  { id: 'levitate', name: 'Levitate', level: 2, school: 'Transmutation', lists: ['arcane'], summary: 'Move a subject up and down.', cast: '1 standard action', comp: 'V, S, F', range: 'Personal or close', dur: '1 min/level', save: 'None', desc: 'You move yourself or a willing subject up and down as you wish, up to 20 feet per round.' },
  { id: 'resist-energy', name: 'Resist Energy', level: 2, school: 'Abjuration', lists: ['arcane', 'divine', 'druid'], summary: 'Resist 10+ of one energy type.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'The subject gains resistance 10 (more at higher level) to a chosen energy type.' },
  { id: 'hideous-laughter', name: 'Hideous Laughter', level: 2, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'A creature falls down laughing.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 round/level', save: 'Will negates', desc: 'The subject perceives everything as hilarious and collapses into laughter, unable to act.' },

  // Arcane level 3
  { id: 'fireball', name: 'Fireball', level: 3, school: 'Evocation', lists: ['arcane'], summary: '20-ft burst, 1d6/level fire.', cast: '1 standard action', comp: 'V, S, M', range: 'Long', dur: 'Instantaneous', save: 'Reflex half', desc: 'A burst of flame deals 1d6 fire damage per caster level (max 10d6) to all in a 20-ft-radius spread.' },
  { id: 'lightning-bolt', name: 'Lightning Bolt', level: 3, school: 'Evocation', lists: ['arcane'], summary: '120-ft line, 1d6/level electricity.', cast: '1 standard action', comp: 'V, S, M', range: '120 ft line', dur: 'Instantaneous', save: 'Reflex half', desc: 'A stroke of lightning deals 1d6 electricity per caster level (max 10d6) to every creature in a line.' },
  { id: 'fly', name: 'Fly', level: 3, school: 'Transmutation', lists: ['arcane'], summary: 'Fly speed 60 ft.', cast: '1 standard action', comp: 'V, S, F', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains a fly speed of 60 feet (40 if heavily loaded) with good maneuverability.' },
  { id: 'haste', name: 'Haste', level: 3, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Allies gain an extra attack and speed.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 round/level', save: 'Fortitude negates (harmless)', desc: 'One creature per level gains an extra attack, +1 to attack and AC and Reflex, and +30 ft speed.' },
  { id: 'dispel-magic', name: 'Dispel Magic', level: 3, school: 'Abjuration', lists: ['arcane', 'divine', 'druid'], summary: 'End or suppress magic.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: 'Instantaneous', save: 'None', desc: 'You can end ongoing spells, counter another caster, or suppress a magic item with a caster level check.' },
  { id: 'displacement', name: 'Displacement', level: 3, school: 'Illusion', lists: ['arcane', 'bard'], summary: '50% miss chance vs attacks.', cast: '1 standard action', comp: 'V, M', range: 'Touch', dur: '1 round/level', save: 'Will negates (harmless)', desc: 'The subject appears to be about 2 feet from its true location, granting a 50% miss chance.' },
  { id: 'vampiric-touch', name: 'Vampiric Touch', level: 3, school: 'Necromancy', lists: ['arcane'], summary: 'Touch drains HP to you.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'Your touch deals 1d6 per two caster levels; you gain the damage dealt as temporary hit points.' },
  { id: 'stinking-cloud', name: 'Stinking Cloud', level: 3, school: 'Conjuration', lists: ['arcane'], summary: 'Nauseating cloud.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: '1 round/level', save: 'Fortitude negates (nausea)', desc: 'A bank of foul vapor nauseates creatures caught within it.' },
  { id: 'protection-from-energy', name: 'Protection from Energy', level: 3, school: 'Abjuration', lists: ['arcane', 'divine', 'druid'], summary: 'Absorb a lot of one energy type.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'The warded creature ignores damage from a chosen energy type until the spell absorbs 12/level.' },

  // Divine level 2
  { id: 'cure-moderate-wounds', name: 'Cure Moderate Wounds', level: 2, school: 'Conjuration', lists: ['divine', 'druid', 'bard'], summary: 'Heal 2d8 + caster level.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Positive energy cures 2d8 damage +1 per caster level (max +10).' },
  { id: 'hold-person', name: 'Hold Person', level: 2, school: 'Enchantment', lists: ['divine', 'arcane', 'bard'], summary: 'Paralyze one humanoid.', cast: '1 standard action', comp: 'V, S, F/DF', range: 'Medium', dur: '1 round/level', save: 'Will negates', desc: 'The target humanoid is paralyzed, though it may attempt a new save each round.' },
  { id: 'spiritual-weapon', name: 'Spiritual Weapon', level: 2, school: 'Evocation', lists: ['divine'], summary: 'A floating weapon attacks foes.', cast: '1 standard action', comp: 'V, S, DF', range: 'Medium', dur: '1 round/level', save: 'None', desc: "A weapon of force attacks foes at your direction, using your BAB and Wisdom." },
  { id: 'silence', name: 'Silence', level: 2, school: 'Illusion', lists: ['divine', 'bard'], summary: 'No sound in an area.', cast: '1 standard action', comp: 'V, S', range: 'Long', dur: '1 round/level', save: 'Will negates; see text', desc: 'An area is made utterly silent, preventing sound and blocking verbal spellcasting within it.' },
  { id: 'aid', name: 'Aid', level: 2, school: 'Enchantment', lists: ['divine'], summary: '+1 attack, +vs fear, temp HP.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 min/level', save: 'None', desc: 'The subject gains a +1 morale bonus on attacks and vs fear, plus 1d8 temporary hit points.' },
  { id: 'lesser-restoration', name: 'Lesser Restoration', level: 2, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'Heal ability damage.', cast: '3 rounds', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'Dispels magical ability penalties and heals ability damage, plus fatigue or exhaustion.' },

  // Divine level 3
  { id: 'cure-serious-wounds', name: 'Cure Serious Wounds', level: 3, school: 'Conjuration', lists: ['divine', 'druid', 'bard'], summary: 'Heal 3d8 + caster level.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Positive energy cures 3d8 damage +1 per caster level (max +15).' },
  { id: 'prayer', name: 'Prayer', level: 3, school: 'Enchantment', lists: ['divine', 'bard'], summary: 'Allies +1, enemies −1.', cast: '1 standard action', comp: 'V, S, DF', range: '40 ft', dur: '1 round/level', save: 'None', desc: 'Allies gain +1 on most rolls while enemies take −1, within the burst around you.' },
  { id: 'searing-light', name: 'Searing Light', level: 3, school: 'Evocation', lists: ['divine'], summary: 'Ray, extra vs undead.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: 'Instantaneous', save: 'None', desc: 'A ray of divine light deals 1d8 per two levels (more to undead) on a ranged touch attack.' },
  { id: 'bestow-curse', name: 'Bestow Curse', level: 3, school: 'Necromancy', lists: ['divine', 'arcane'], summary: 'Curse a creature.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Permanent', save: 'Will negates', desc: 'You lay a curse: an ability penalty, a chance to lose actions, or a −4 on rolls.' },

  // Druid level 2-3
  { id: 'barkskin', name: 'Barkskin', level: 2, school: 'Transmutation', lists: ['druid'], summary: '+2 (or more) natural armor.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '10 min/level', save: 'None', desc: "The subject's skin toughens, granting a +2 (or better) enhancement to natural armor." },
  { id: 'flaming-sphere', name: 'Flaming Sphere', level: 2, school: 'Evocation', lists: ['druid', 'arcane'], summary: 'Rolling ball of fire.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Medium', dur: '1 round/level', save: 'Reflex negates', desc: 'A burning sphere rolls where you direct, dealing 3d6 fire damage to creatures it touches.' },
  { id: 'call-lightning', name: 'Call Lightning', level: 3, school: 'Evocation', lists: ['druid'], summary: 'Call bolts from the sky.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '1 min/level', save: 'Reflex half', desc: 'You call down bolts of lightning (3d6 each, more outdoors in a storm), one per round.' },
  { id: 'neutralize-poison', name: 'Neutralize Poison', level: 3, school: 'Conjuration', lists: ['druid', 'divine', 'bard'], summary: 'Detoxify a creature or object.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'Neutralizes poisons in a creature or object, preventing further effect.' },

  // Arcane level 4
  { id: 'dimension-door', name: 'Dimension Door', level: 4, school: 'Conjuration', lists: ['arcane', 'bard'], summary: 'Teleport a short distance.', cast: '1 standard action', comp: 'V', range: 'Long', dur: 'Instantaneous', save: 'None', desc: 'You instantly transport yourself (and willing companions) a short distance; you can take no further actions that round.' },
  { id: 'greater-invisibility', name: 'Greater Invisibility', level: 4, school: 'Illusion', lists: ['arcane', 'bard'], summary: 'Invisibility that persists through attacks.', cast: '1 standard action', comp: 'V, S', range: 'Personal or touch', dur: '1 round/level', save: 'Will negates (harmless)', desc: 'As invisibility, but the subject can attack and cast without ending the effect.' },
  { id: 'stoneskin', name: 'Stoneskin', level: 4, school: 'Abjuration', lists: ['arcane', 'druid'], summary: 'DR 10/adamantine.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'The subject gains damage reduction 10/adamantine, absorbing up to 10/level total damage.' },
  { id: 'wall-of-fire', name: 'Wall of Fire', level: 4, school: 'Evocation', lists: ['arcane', 'druid'], summary: 'A blazing wall of flame.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Medium', dur: 'Concentration + 1 round/level', save: 'None', desc: 'An opaque sheet of flame deals fire damage to creatures passing through or near it.' },
  { id: 'ice-storm', name: 'Ice Storm', level: 4, school: 'Evocation', lists: ['arcane', 'druid'], summary: '3d6 bludgeon + 2d6 cold in an area.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Long', dur: 'Instantaneous', save: 'None', desc: 'Hail pounds a 20-ft-radius cylinder, dealing damage and hampering movement.' },
  { id: 'black-tentacles', name: 'Black Tentacles', level: 4, school: 'Conjuration', lists: ['arcane'], summary: 'Grasping tentacles grapple foes.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: '1 round/level', save: 'None', desc: 'Rubbery tentacles fill the area, attempting to grapple and crush every creature within.' },
  { id: 'enervation', name: 'Enervation', level: 4, school: 'Necromancy', lists: ['arcane'], summary: 'Ray inflicts negative levels.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'A black ray bestows 1d4 temporary negative levels on a ranged touch hit.' },
  { id: 'fear', name: 'Fear', level: 4, school: 'Necromancy', lists: ['arcane', 'bard'], summary: 'Cone of panic.', cast: '1 standard action', comp: 'V, S, M', range: '30 ft cone', dur: '1 round/level', save: 'Will partial', desc: 'Creatures in a cone become panicked and flee; a successful save leaves them merely shaken.' },
  { id: 'confusion', name: 'Confusion', level: 4, school: 'Enchantment', lists: ['arcane'], summary: 'Randomize foes\' actions.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Medium', dur: '1 round/level', save: 'Will negates', desc: 'Creatures in the area behave randomly each round — babbling, fleeing, attacking, or acting normally.' },
  { id: 'fire-shield', name: 'Fire Shield', level: 4, school: 'Evocation', lists: ['arcane'], summary: 'Flames shield and burn attackers.', cast: '1 standard action', comp: 'V, S, M', range: 'Personal', dur: '1 round/level', save: 'None', desc: 'Flames wreathe you, halving one energy type\'s damage to you and burning those who strike you.' },

  // Divine level 4
  { id: 'cure-critical-wounds', name: 'Cure Critical Wounds', level: 4, school: 'Conjuration', lists: ['divine', 'druid', 'bard'], summary: 'Heal 4d8 + caster level.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Positive energy cures 4d8 damage +1 per caster level (max +20).' },
  { id: 'divine-power', name: 'Divine Power', level: 4, school: 'Evocation', lists: ['divine'], summary: 'BAB, Str, and temp HP boost.', cast: '1 standard action', comp: 'V, S, DF', range: 'Personal', dur: '1 round/level', save: 'None', desc: 'You gain a +1/three-levels luck bonus on attacks, +6 Str for damage, and temporary hit points.' },
  { id: 'freedom-of-movement', name: 'Freedom of Movement', level: 4, school: 'Abjuration', lists: ['divine', 'druid', 'bard'], summary: 'Ignore movement impairment.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'The subject moves and attacks normally despite grapples, webs, or other impediments.' },
  { id: 'restoration', name: 'Restoration', level: 4, school: 'Conjuration', lists: ['divine'], summary: 'Heal ability damage and levels.', cast: '3 rounds', comp: 'V, S, M', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'Dispels magical penalties, restores ability damage, and removes a temporary negative level.' },
  { id: 'death-ward', name: 'Death Ward', level: 4, school: 'Necromancy', lists: ['divine', 'druid'], summary: 'Immunity to death and negative energy.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject is immune to death effects, energy drain, and negative energy.' },
  { id: 'air-walk', name: 'Air Walk', level: 4, school: 'Transmutation', lists: ['divine', 'druid'], summary: 'Walk on air.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '10 min/level', save: 'None', desc: 'The subject can tread on air as if on solid ground, moving upward or downward at an angle.' },

  // Arcane level 5
  { id: 'cone-of-cold', name: 'Cone of Cold', level: 5, school: 'Evocation', lists: ['arcane'], summary: '60-ft cone, 1d6/level cold.', cast: '1 standard action', comp: 'V, S, M', range: '60 ft cone', dur: 'Instantaneous', save: 'Reflex half', desc: 'Freezing air deals 1d6 cold per caster level (max 15d6) in a cone.' },
  { id: 'teleport', name: 'Teleport', level: 5, school: 'Conjuration', lists: ['arcane'], summary: 'Instantly travel a long distance.', cast: '1 standard action', comp: 'V', range: 'Personal and touch', dur: 'Instantaneous', save: 'None', desc: 'You instantly transport yourself and companions to a known destination, any distance on the same plane.' },
  { id: 'wall-of-force', name: 'Wall of Force', level: 5, school: 'Evocation', lists: ['arcane'], summary: 'An invisible, near-indestructible wall.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 round/level', save: 'None', desc: 'An invisible barrier of force blocks all matter and most effects; it cannot be dispelled.' },
  { id: 'dominate-person', name: 'Dominate Person', level: 5, school: 'Enchantment', lists: ['arcane'], summary: 'Control a humanoid.', cast: '1 round', comp: 'V, S', range: 'Close', dur: '1 day/level', save: 'Will negates', desc: 'You control the actions of a humanoid through a telepathic link.' },
  { id: 'hold-monster', name: 'Hold Monster', level: 5, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'Paralyze any one creature.', cast: '1 standard action', comp: 'V, S, M/F', range: 'Medium', dur: '1 round/level', save: 'Will negates', desc: 'As hold person, but affecting any living creature.' },
  { id: 'baleful-polymorph', name: 'Baleful Polymorph', level: 5, school: 'Transmutation', lists: ['arcane', 'druid'], summary: 'Transform a foe into a harmless animal.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Permanent', save: 'Fortitude negates, Will partial', desc: 'You turn the subject into a Small or Tiny animal, possibly overwriting its mind.' },
  { id: 'cloudkill', name: 'Cloudkill', level: 5, school: 'Conjuration', lists: ['arcane'], summary: 'A cloud of deadly poison.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '1 min/level', save: 'Fortitude partial', desc: 'A bank of poisonous fog kills weaker creatures outright and sickens or damages the rest.' },
  { id: 'overland-flight', name: 'Overland Flight', level: 5, school: 'Transmutation', lists: ['arcane'], summary: 'Long-duration self flight.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 hour/level', save: 'None', desc: 'You fly at your land speed with good maneuverability and can travel for hours.' },
  { id: 'break-enchantment', name: 'Break Enchantment', level: 5, school: 'Abjuration', lists: ['arcane', 'divine', 'bard'], summary: 'Free creatures from spells and curses.', cast: '1 minute', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'See text', desc: 'You free subjects from enchantments, transmutations, curses, and petrification with a caster level check.' },

  // Divine level 5
  { id: 'flame-strike', name: 'Flame Strike', level: 5, school: 'Evocation', lists: ['divine', 'druid'], summary: 'Column of divine fire.', cast: '1 standard action', comp: 'V, S, DF', range: 'Medium', dur: 'Instantaneous', save: 'Reflex half', desc: 'A column of fire deals 1d6 per caster level (max 15d6), half of it divine and unresistable.' },
  { id: 'raise-dead', name: 'Raise Dead', level: 5, school: 'Conjuration', lists: ['divine'], summary: 'Return a dead creature to life.', cast: '1 minute', comp: 'V, S, M', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'You restore life to a creature dead no more than one day per level, at the cost of levels and materials.' },
  { id: 'righteous-might', name: 'Righteous Might', level: 5, school: 'Transmutation', lists: ['divine'], summary: 'Grow larger and tougher.', cast: '1 standard action', comp: 'V, S, DF', range: 'Personal', dur: '1 round/level', save: 'None', desc: 'You grow one size category, gaining Strength, natural armor, and damage reduction.' },
  { id: 'true-seeing', name: 'True Seeing', level: 5, school: 'Divination', lists: ['divine', 'druid'], summary: 'See through illusions and disguises.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 min/level', save: 'None', desc: 'You see things as they really are — through illusions, darkness, invisibility, and transmutations.' },
  { id: 'mass-cure-light-wounds', name: 'Mass Cure Light Wounds', level: 5, school: 'Conjuration', lists: ['divine', 'druid', 'bard'], summary: 'Heal many allies at once.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Cures 1d8 +1/level (max +25) to one creature per level in the area.' },

  // Arcane level 6
  { id: 'chain-lightning', name: 'Chain Lightning', level: 6, school: 'Evocation', lists: ['arcane'], summary: 'A bolt that arcs to many foes.', cast: '1 standard action', comp: 'V, S, F', range: 'Long', dur: 'Instantaneous', save: 'Reflex half', desc: 'Lightning strikes a primary target (1d6/level) then arcs to secondary targets at half damage.' },
  { id: 'disintegrate', name: 'Disintegrate', level: 6, school: 'Transmutation', lists: ['arcane'], summary: 'A ray that can reduce a foe to dust.', cast: '1 standard action', comp: 'V, S, M/F', range: 'Medium', dur: 'Instantaneous', save: 'Fortitude partial', desc: 'A thin green ray deals massive damage; a slain creature is reduced to fine dust.' },
  { id: 'greater-dispel-magic', name: 'Greater Dispel Magic', level: 6, school: 'Abjuration', lists: ['arcane', 'divine', 'druid'], summary: 'Dispel multiple or stubborn magics.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: 'Instantaneous', save: 'None', desc: 'As dispel magic, but with a higher cap and the ability to remove all effects in an area.' },
  { id: 'globe-of-invulnerability', name: 'Globe of Invulnerability', level: 6, school: 'Abjuration', lists: ['arcane'], summary: 'Block low-level spells.', cast: '1 standard action', comp: 'V, S, M', range: '10 ft', dur: '1 round/level', save: 'None', desc: 'An immobile globe blocks spell effects of 4th level and lower cast from outside it.' },
  { id: 'contingency', name: 'Contingency', level: 6, school: 'Evocation', lists: ['arcane'], summary: 'Pre-set a spell to trigger later.', cast: '10 minutes', comp: 'V, S, M, F', range: 'Personal', dur: '1 day/level', save: 'None', desc: 'You set a personal spell to activate automatically under a condition you specify.' },
  { id: 'flesh-to-stone', name: 'Flesh to Stone', level: 6, school: 'Transmutation', lists: ['arcane'], summary: 'Turn a creature to stone.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: 'Instantaneous', save: 'Fortitude negates', desc: 'The subject and all it carries turn into a mindless, inert statue.' },

  // Divine level 6
  { id: 'heal', name: 'Heal', level: 6, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'Massive healing and condition removal.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Wipes away 10 HP per level (max 150) and removes many afflictions in a single touch.' },
  { id: 'harm', name: 'Harm', level: 6, school: 'Necromancy', lists: ['divine'], summary: 'Massive negative-energy damage.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half', desc: 'Negative energy deals 10 per level (max 150), leaving a living target at 1 hp.' },
  { id: 'blade-barrier', name: 'Blade Barrier', level: 6, school: 'Evocation', lists: ['divine'], summary: 'A wall of whirling blades.', cast: '1 standard action', comp: 'V, S, DF', range: 'Medium', dur: '1 round/level', save: 'Reflex half', desc: 'A vertical curtain of spinning blades deals 1d6/level (max 15d6) to those passing through.' },
  { id: 'heroes-feast', name: "Heroes' Feast", level: 6, school: 'Conjuration', lists: ['divine', 'bard'], summary: 'A meal that heals and buffs allies.', cast: '10 minutes', comp: 'V, S, DF', range: 'Close', dur: '1 hour + see text', save: 'None', desc: 'You create a feast that cures, wards against poison and fear, and grants attack and save bonuses.' },

  // Arcane level 7
  { id: 'delayed-blast-fireball', name: 'Delayed Blast Fireball', level: 7, school: 'Evocation', lists: ['arcane'], summary: 'A fireball you can delay.', cast: '1 standard action', comp: 'V, S, M', range: 'Long', dur: 'See text', save: 'Reflex half', desc: 'As fireball (1d6/level, max 20d6), but you may set it to detonate up to 5 rounds later.' },
  { id: 'finger-of-death', name: 'Finger of Death', level: 7, school: 'Necromancy', lists: ['arcane', 'druid'], summary: 'Slay a creature, or heavy damage.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'Fortitude partial', desc: 'You attempt to kill a creature outright; a successful save reduces it to 3d6+level damage.' },
  { id: 'prismatic-spray', name: 'Prismatic Spray', level: 7, school: 'Evocation', lists: ['arcane'], summary: 'A cone of random deadly colors.', cast: '1 standard action', comp: 'V, S', range: '60 ft cone', dur: 'Instantaneous', save: 'See text', desc: 'Rays of many colors flash out, each with a different harmful effect from damage to death to banishment.' },
  { id: 'reverse-gravity', name: 'Reverse Gravity', level: 7, school: 'Transmutation', lists: ['arcane', 'druid'], summary: 'Objects and creatures fall up.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Medium', dur: '1 round/level', save: 'None', desc: 'Gravity reverses in the area, sending unattached creatures and objects falling upward.' },
  { id: 'limited-wish', name: 'Limited Wish', level: 7, school: 'Universal', lists: ['arcane'], summary: 'Alter reality within limits.', cast: '1 standard action', comp: 'V, S, M', range: 'See text', dur: 'See text', save: 'None', desc: 'You reshape reality to duplicate lower-level spells or grant modest boons, at a material cost.' },
  { id: 'banishment', name: 'Banishment', level: 7, school: 'Abjuration', lists: ['arcane', 'divine'], summary: 'Force extraplanar creatures away.', cast: '1 standard action', comp: 'V, S, F', range: 'Close', dur: 'Instantaneous', save: 'Will negates', desc: 'You drive extraplanar creatures back to their home plane.' },

  // Divine level 7
  { id: 'resurrection', name: 'Resurrection', level: 7, school: 'Conjuration', lists: ['divine'], summary: 'Fully restore the dead to life.', cast: '10 minutes', comp: 'V, S, M', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'You restore a dead creature to full life and health from even a small remnant of its body.' },
  { id: 'destruction', name: 'Destruction', level: 7, school: 'Necromancy', lists: ['divine'], summary: 'Slay a creature and consume it.', cast: '1 standard action', comp: 'V, S, F', range: 'Close', dur: 'Instantaneous', save: 'Fortitude partial', desc: 'You annihilate a creature; a failed save destroys it utterly, leaving no remains.' },
  { id: 'regenerate', name: 'Regenerate', level: 7, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'Regrow limbs and heal deeply.', cast: '3 rounds', comp: 'V, S, DF', range: 'Touch', dur: 'Instantaneous', save: 'Fortitude negates (harmless)', desc: 'Severed body parts regrow and the subject heals rapidly, curing ability and fatigue effects.' },
  { id: 'greater-restoration', name: 'Greater Restoration', level: 7, school: 'Conjuration', lists: ['divine'], summary: 'Restore levels, abilities, and mind.', cast: '10 minutes', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'Dispels most magical afflictions and restores all ability and level drain.' },

  // Arcane level 8
  { id: 'horrid-wilting', name: 'Horrid Wilting', level: 8, school: 'Necromancy', lists: ['arcane'], summary: 'Drain moisture from many foes.', cast: '1 standard action', comp: 'V, S, M/F', range: 'Long', dur: 'Instantaneous', save: 'Fortitude half', desc: 'You evaporate the moisture from creatures in the area, dealing 1d6 per level (max 20d6).' },
  { id: 'polar-ray', name: 'Polar Ray', level: 8, school: 'Evocation', lists: ['arcane'], summary: 'A ray of intense cold.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: 'Instantaneous', save: 'None', desc: 'A beam of freezing cold deals 1d6 per level (max 25d6) and 1d4 Dexterity damage.' },
  { id: 'mind-blank', name: 'Mind Blank', level: 8, school: 'Abjuration', lists: ['arcane'], summary: 'Total protection from mental magic.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '24 hours', save: 'Will negates (harmless)', desc: 'The subject is immune to all mind-affecting effects and divinations.' },
  { id: 'maze', name: 'Maze', level: 8, school: 'Conjuration', lists: ['arcane'], summary: 'Trap a creature in a labyrinth.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'See text', save: 'None', desc: 'The subject is banished to an extradimensional maze until it escapes with an Intelligence check.' },
  { id: 'power-word-stun', name: 'Power Word Stun', level: 8, school: 'Enchantment', lists: ['arcane'], summary: 'Stun a foe with a word, no save.', cast: '1 standard action', comp: 'V', range: 'Close', dur: 'See text', save: 'None', desc: 'A single word stuns a creature (duration by its current hit points) with no saving throw.' },

  // Divine level 8
  { id: 'fire-storm', name: 'Fire Storm', level: 8, school: 'Evocation', lists: ['divine', 'druid'], summary: 'Fill an area with roaring flame.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: 'Instantaneous', save: 'Reflex half', desc: 'Flames blast every creature in the area for 1d6 per level (max 20d6), sparing plants you choose.' },
  { id: 'earthquake', name: 'Earthquake', level: 8, school: 'Evocation', lists: ['divine', 'druid'], summary: 'Shake and collapse the ground.', cast: '1 standard action', comp: 'V, S, DF', range: 'Long', dur: '1 round', save: 'See text', desc: 'An intense tremor knocks creatures down, collapses structures, and opens fissures in the earth.' },
  { id: 'mass-cure-critical-wounds', name: 'Mass Cure Critical Wounds', level: 8, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'Heavily heal many allies.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Cures 4d8 +1/level (max +40) to one creature per level in range.' },

  // Arcane level 9
  { id: 'wish', name: 'Wish', level: 9, school: 'Universal', lists: ['arcane'], summary: 'Reshape reality.', cast: '1 standard action', comp: 'V, S', range: 'See text', dur: 'See text', save: 'See text', desc: 'The mightiest spell: duplicate almost any spell, undo harm, or alter reality — at a steep material cost.' },
  { id: 'meteor-swarm', name: 'Meteor Swarm', level: 9, school: 'Evocation', lists: ['arcane'], summary: 'Four fiery spheres of destruction.', cast: '1 standard action', comp: 'V, S', range: 'Long', dur: 'Instantaneous', save: 'Reflex half', desc: 'Four meteors strike, each dealing bludgeoning and fire damage in overlapping bursts.' },
  { id: 'time-stop', name: 'Time Stop', level: 9, school: 'Transmutation', lists: ['arcane'], summary: 'Act freely while time is frozen.', cast: '1 standard action', comp: 'V', range: 'Personal', dur: 'See text', save: 'None', desc: 'You take several apparent rounds of actions while everyone else is frozen in time.' },
  { id: 'power-word-kill', name: 'Power Word Kill', level: 9, school: 'Enchantment', lists: ['arcane'], summary: 'Slay a weakened foe with a word.', cast: '1 standard action', comp: 'V', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'A single word kills one creature of 100 hit points or fewer, with no saving throw.' },
  { id: 'gate', name: 'Gate', level: 9, school: 'Conjuration', lists: ['arcane', 'divine'], summary: 'Open a portal to another plane.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: 'See text', save: 'None', desc: 'You tear open a portal between planes, allowing travel or the calling of a powerful outsider.' },
  { id: 'dominate-monster', name: 'Dominate Monster', level: 9, school: 'Enchantment', lists: ['arcane'], summary: 'Control any one creature.', cast: '1 round', comp: 'V, S', range: 'Close', dur: '1 day/level', save: 'Will negates', desc: 'As dominate person, but affecting any creature.' },

  // Divine level 9
  { id: 'miracle', name: 'Miracle', level: 9, school: 'Evocation', lists: ['divine'], summary: 'Beseech your deity for a mighty effect.', cast: '1 standard action', comp: 'V, S', range: 'See text', dur: 'See text', save: 'See text', desc: 'You request an intercession from your deity — duplicating spells, reversing fortunes, or more.' },
  { id: 'mass-heal', name: 'Mass Heal', level: 9, school: 'Conjuration', lists: ['divine'], summary: 'Full healing to many creatures.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'Will half (harmless)', desc: 'Heals 10 per level (max 250) and cures afflictions on many creatures at once.' },
  { id: 'storm-of-vengeance', name: 'Storm of Vengeance', level: 9, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'A devastating multi-round storm.', cast: '1 round', comp: 'V, S', range: 'Long', dur: 'Concentration, up to 10 rounds', save: 'See text', desc: 'A towering storm deafens, then rains acid, lightning, hail, and wind over several rounds.' },
  { id: 'true-resurrection', name: 'True Resurrection', level: 9, school: 'Conjuration', lists: ['divine'], summary: 'Restore the dead even without remains.', cast: '10 minutes', comp: 'V, S, M', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'You restore life and full health to a creature dead up to 10 years per level, even with no body.' },

  // ===== Common-spell breadth pass (core-scope). Levels shown are for the tagged lists; a spell
  // whose level differs on another list is tagged only where it matches (the single-level model). =====

  // ---- Cantrips / orisons (level 0) ----
  { id: 'dancing-lights', name: 'Dancing Lights', level: 0, school: 'Evocation', lists: ['arcane', 'bard'], summary: 'Create up to four moving lights.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '1 minute', save: 'None', desc: 'You create up to four floating lights that you can move as a move action, resembling torches, lanterns, or a glowing humanoid shape.' },
  { id: 'flare', name: 'Flare', level: 0, school: 'Evocation', lists: ['arcane', 'druid', 'bard'], summary: 'Dazzle one creature.', cast: '1 standard action', comp: 'V', range: 'Close', dur: 'Instantaneous', save: 'Fortitude negates', desc: 'A burst of light dazzles one creature (−1 on attack rolls) for 1 minute unless it saves.' },
  { id: 'ghost-sound', name: 'Ghost Sound', level: 0, school: 'Illusion', lists: ['arcane', 'bard'], summary: 'Create illusory sounds.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 round/level', save: 'Will disbelief', desc: 'You create a volume of illusory sound — voices, music, or noise — that you can shape as you like.' },
  { id: 'mending', name: 'Mending', level: 0, school: 'Transmutation', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Repair a damaged object.', cast: '10 minutes', comp: 'V, S', range: '10 ft', dur: 'Instantaneous', save: 'Will negates (harmless, object)', desc: 'You repair a single break or tear in an object, restoring 1d4 hit points to it.' },
  { id: 'message', name: 'Message', level: 0, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Whisper conversation at a distance.', cast: '1 standard action', comp: 'V, S, F', range: 'Medium', dur: '10 min/level', save: 'None', desc: 'You can whisper messages and receive replies with subjects you point to, so long as they have line of effect.' },
  { id: 'open-close', name: 'Open/Close', level: 0, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Open or close a small object.', cast: '1 standard action', comp: 'V, S, F', range: 'Close', dur: 'Instantaneous', save: 'Will negates (object)', desc: 'You open or close a door, chest, box, window, bag, or other object with a movable part.' },
  { id: 'arcane-mark', name: 'Arcane Mark', level: 0, school: 'Universal', lists: ['arcane'], summary: 'Inscribe a personal rune.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Permanent', save: 'None', desc: 'You inscribe a personal rune or mark, visible or invisible, on any substance.' },
  { id: 'bleed', name: 'Bleed', level: 0, school: 'Necromancy', lists: ['arcane', 'divine'], summary: 'Reopen a dying creature’s wounds.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'Will negates', desc: 'A stable or healed creature at negative hit points begins dying again, losing 1 hit point.' },
  { id: 'touch-of-fatigue', name: 'Touch of Fatigue', level: 0, school: 'Necromancy', lists: ['arcane'], summary: 'Touch fatigues a foe.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 round/level', save: 'Fortitude negates', desc: 'Your touch drains a target’s vitality, leaving it fatigued on a failed save.' },
  { id: 'resistance', name: 'Resistance', level: 0, school: 'Abjuration', lists: ['arcane', 'divine', 'druid', 'bard'], summary: '+1 resistance on saves.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '1 minute', save: 'Will negates (harmless)', desc: 'The subject gains a +1 resistance bonus on saving throws for 1 minute.' },
  { id: 'detect-poison', name: 'Detect Poison', level: 0, school: 'Divination', lists: ['arcane', 'divine', 'druid'], summary: 'Detect poison on a creature or object.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'You determine whether a creature, object, or area has been poisoned or is poisonous.' },
  { id: 'create-water', name: 'Create Water', level: 0, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'Create drinking water.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'None', desc: 'You create up to 2 gallons of clean water per caster level.' },
  { id: 'guidance', name: 'Guidance', level: 0, school: 'Divination', lists: ['divine', 'druid'], summary: '+1 on one attack, save, or skill.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: '1 minute or until discharged', save: 'None', desc: 'The subject gains a +1 competence bonus on a single attack roll, saving throw, or skill check.' },
  { id: 'stabilize', name: 'Stabilize', level: 0, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'Stabilize a dying creature.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'Will negates (harmless)', desc: 'A dying creature stabilizes, stopping its loss of hit points.' },
  { id: 'virtue', name: 'Virtue', level: 0, school: 'Transmutation', lists: ['divine', 'druid'], summary: '1 temporary hit point.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 minute', save: 'Fortitude negates (harmless)', desc: 'The subject gains 1 temporary hit point.' },
  { id: 'purify-food-and-drink', name: 'Purify Food and Drink', level: 0, school: 'Transmutation', lists: ['divine', 'druid'], summary: 'Cleanse food and water.', cast: '1 standard action', comp: 'V, S', range: '10 ft', dur: 'Instantaneous', save: 'Will negates (object)', desc: 'You purify spoiled, rotten, poisonous, or contaminated food and water.' },
  { id: 'know-direction', name: 'Know Direction', level: 0, school: 'Divination', lists: ['druid', 'bard'], summary: 'Determine which way is north.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: 'Instantaneous', save: 'None', desc: 'You instantly know which way is north.' },

  // ---- Level 1 ----
  { id: 'true-strike', name: 'True Strike', level: 1, school: 'Divination', lists: ['arcane'], summary: '+20 on your next attack.', cast: '1 standard action', comp: 'V, M', range: 'Personal', dur: 'See text', save: 'None', desc: 'You gain a +20 insight bonus on your next attack roll and ignore the miss chance from concealment.' },
  { id: 'shocking-grasp', name: 'Shocking Grasp', level: 1, school: 'Evocation', lists: ['arcane'], summary: 'Touch, 1d6/level electricity.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'Your touch deals 1d6 electricity per caster level (max 5d6), with +3 to hit against metal.' },
  { id: 'magic-weapon', name: 'Magic Weapon', level: 1, school: 'Transmutation', lists: ['arcane', 'divine'], summary: 'Weapon gains +1.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless, object)', desc: 'A weapon gains a +1 enhancement bonus on attack and damage rolls.' },
  { id: 'feather-fall', name: 'Feather Fall', level: 1, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Fall slowly and safely.', cast: '1 immediate action', comp: 'V', range: 'Close', dur: 'Until landing or 1 round/level', save: 'Will negates (harmless)', desc: 'Falling creatures or objects descend at 60 feet per round, taking no damage on landing.' },
  { id: 'obscuring-mist', name: 'Obscuring Mist', level: 1, school: 'Conjuration', lists: ['arcane', 'divine', 'druid'], summary: 'Fog grants concealment.', cast: '1 standard action', comp: 'V, S', range: '20 ft', dur: '1 min/level', save: 'None', desc: 'A misty vapor rises around you, granting concealment to creatures within it.' },
  { id: 'silent-image', name: 'Silent Image', level: 1, school: 'Illusion', lists: ['arcane', 'bard'], summary: 'Create a visual illusion.', cast: '1 standard action', comp: 'V, S, F', range: 'Long', dur: 'Concentration', save: 'Will disbelief', desc: 'You create the visual illusion of an object, creature, or force, as large as a 10-ft cube, that you can move by concentrating.' },
  { id: 'unseen-servant', name: 'Unseen Servant', level: 1, school: 'Conjuration', lists: ['arcane', 'bard'], summary: 'An invisible force does chores.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 hour/level', save: 'None', desc: 'An invisible, mindless, shapeless force performs simple tasks at your command.' },
  { id: 'reduce-person', name: 'Reduce Person', level: 1, school: 'Transmutation', lists: ['arcane'], summary: 'Humanoid shrinks one size.', cast: '1 round', comp: 'V, S, M', range: 'Close', dur: '1 min/level', save: 'Fortitude negates', desc: 'The target shrinks one size category, gaining +2 Dex, −2 Str, and +1 to attack and AC.' },
  { id: 'ray-of-enfeeblement', name: 'Ray of Enfeeblement', level: 1, school: 'Necromancy', lists: ['arcane'], summary: 'Ray saps Strength.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '1 round/level', save: 'Fortitude half', desc: 'A ray inflicts a penalty to Strength of 1d6 + 1 per two caster levels on a ranged touch hit.' },
  { id: 'comprehend-languages', name: 'Comprehend Languages', level: 1, school: 'Divination', lists: ['arcane', 'divine', 'bard'], summary: 'Understand any language.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Personal', dur: '10 min/level', save: 'None', desc: 'You understand the spoken and written words of any language you encounter.' },
  { id: 'disguise-self', name: 'Disguise Self', level: 1, school: 'Illusion', lists: ['arcane', 'bard'], summary: 'Change your appearance.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '10 min/level', save: 'None', desc: 'You alter your appearance — features, clothing, and equipment — within one size category.' },
  { id: 'cause-fear', name: 'Cause Fear', level: 1, school: 'Necromancy', lists: ['arcane', 'divine', 'bard'], summary: 'Frighten one creature.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '1d4 rounds or 1 round', save: 'Will partial', desc: 'One creature of 5 HD or less becomes frightened; a successful save leaves it shaken for 1 round.' },
  { id: 'summon-monster-i', name: 'Summon Monster I', level: 1, school: 'Conjuration', lists: ['arcane', 'divine', 'bard'], summary: 'Summon one creature to fight.', cast: '1 round', comp: 'V, S, F/DF', range: 'Close', dur: '1 round/level', save: 'None', desc: 'You summon one creature from the 1st-level summoning list to fight for you.' },
  { id: 'endure-elements', name: 'Endure Elements', level: 1, school: 'Abjuration', lists: ['arcane', 'divine', 'druid'], summary: 'Ignore hot and cold.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: '24 hours', save: 'Will negates (harmless)', desc: 'The subject is unharmed by temperatures from 50°F below zero to 140°F.' },
  { id: 'alarm', name: 'Alarm', level: 1, school: 'Abjuration', lists: ['arcane'], summary: 'Ward an area with an alarm.', cast: '1 standard action', comp: 'V, S, F/DF', range: 'Close', dur: '2 hours/level', save: 'None', desc: 'A mental or audible alarm sounds when a creature enters the warded area.' },
  { id: 'jump', name: 'Jump', level: 1, school: 'Transmutation', lists: ['arcane', 'druid'], summary: '+10 (or more) on Acrobatics to jump.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gets a bonus on Acrobatics checks made to jump: +10, rising to +20 at 5th and +30 at 9th level.' },
  { id: 'floating-disk', name: 'Floating Disk', level: 1, school: 'Evocation', lists: ['arcane'], summary: 'A disk carries your load.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 hour/level', save: 'None', desc: 'A slightly concave disk of force floats near you and carries up to 100 pounds per caster level.' },
  { id: 'animate-rope', name: 'Animate Rope', level: 1, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Command a rope to move.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '1 round/level', save: 'None', desc: 'You animate a nonliving rope, causing it to coil, knot, loop, or tie as you direct.' },
  { id: 'hypnotism', name: 'Hypnotism', level: 1, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'Fascinate nearby creatures.', cast: '1 round', comp: 'V, S', range: 'Close', dur: '2d4 rounds', save: 'Will negates', desc: 'Fascinating swirling colors make 2d4 HD of creatures more susceptible to your suggestions.' },
  { id: 'mount', name: 'Mount', level: 1, school: 'Conjuration', lists: ['arcane'], summary: 'Summon a riding horse.', cast: '1 round', comp: 'V, S, M', range: 'Close', dur: '2 hours/level', save: 'None', desc: 'You summon a light horse or pony (your choice) to serve as a mount, with saddle and bit.' },
  { id: 'bane', name: 'Bane', level: 1, school: 'Enchantment', lists: ['divine'], summary: 'Enemies −1 attack and vs fear.', cast: '1 standard action', comp: 'V, S, DF', range: '50 ft', dur: '1 min/level', save: 'Will negates', desc: 'Your enemies take a −1 penalty on attack rolls and saves against fear. Counters bless.' },
  { id: 'command', name: 'Command', level: 1, school: 'Enchantment', lists: ['divine'], summary: 'One-word command to a foe.', cast: '1 standard action', comp: 'V', range: 'Close', dur: '1 round', save: 'Will negates', desc: 'You give a subject a single command — approach, drop, fall, flee, or halt — which it obeys for 1 round.' },
  { id: 'detect-evil', name: 'Detect Evil', level: 1, school: 'Divination', lists: ['divine'], summary: 'Sense evil auras.', cast: '1 standard action', comp: 'V, S, DF', range: '60 ft cone', dur: 'Concentration, up to 10 min/level', save: 'None', desc: 'You sense the presence, number, and power of evil auras over several rounds of concentration.' },
  { id: 'doom', name: 'Doom', level: 1, school: 'Necromancy', lists: ['divine'], summary: 'A foe becomes shaken.', cast: '1 standard action', comp: 'V, S, DF', range: 'Medium', dur: '1 min/level', save: 'Will negates', desc: 'One creature becomes shaken, taking −2 on attacks, saves, skills, and ability checks.' },
  { id: 'sanctuary', name: 'Sanctuary', level: 1, school: 'Abjuration', lists: ['divine'], summary: 'Foes can’t attack the warded creature.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 round/level', save: 'Will negates', desc: 'Creatures cannot attack the warded creature unless they succeed a Will save; it cannot attack in turn.' },
  { id: 'remove-fear', name: 'Remove Fear', level: 1, school: 'Abjuration', lists: ['divine', 'bard'], summary: '+4 vs fear, suppress it.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '10 minutes', save: 'Will negates (harmless)', desc: 'One creature per four levels gains +4 vs fear and suppresses an existing fear effect.' },
  { id: 'entropic-shield', name: 'Entropic Shield', level: 1, school: 'Abjuration', lists: ['divine'], summary: '20% miss vs ranged attacks.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'A field deflects incoming ranged attacks, giving them a 20% miss chance.' },
  { id: 'deathwatch', name: 'Deathwatch', level: 1, school: 'Necromancy', lists: ['divine'], summary: 'See the living and the dead.', cast: '1 standard action', comp: 'V, S', range: '30 ft cone', dur: '10 min/level', save: 'None', desc: 'You see how near death and debilitated the creatures around you are.' },
  { id: 'magic-stone', name: 'Magic Stone', level: 1, school: 'Transmutation', lists: ['divine', 'druid'], summary: 'Throw enchanted stones.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '30 minutes or until discharged', save: 'Will negates (harmless, object)', desc: 'Up to three stones gain +1 to attack and deal 1d6+1 (2d6+2 to undead) when thrown or slung.' },
  { id: 'inflict-light-wounds', name: 'Inflict Light Wounds', level: 1, school: 'Necromancy', lists: ['divine'], summary: '1d8 + level negative energy.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half', desc: 'Negative energy deals 1d8 +1 per caster level (max +5), or heals undead.' },
  { id: 'faerie-fire', name: 'Faerie Fire', level: 1, school: 'Evocation', lists: ['druid'], summary: 'Outline foes in light.', cast: '1 standard action', comp: 'V, S, DF', range: 'Long', dur: '1 min/level', save: 'None', desc: 'A pale glow outlines targets, negating concealment from blur, invisibility, and the like.' },
  { id: 'goodberry', name: 'Goodberry', level: 1, school: 'Transmutation', lists: ['druid'], summary: 'Berries nourish and heal 1 HP.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 day/level', save: 'None', desc: '2d4 berries each provide a day’s nourishment and heal 1 hit point, up to 8 in a day.' },
  { id: 'longstrider', name: 'Longstrider', level: 1, school: 'Transmutation', lists: ['druid'], summary: '+10 ft speed.', cast: '1 standard action', comp: 'V, S, M', range: 'Personal', dur: '1 hour/level', save: 'None', desc: 'Your base land speed increases by 10 feet.' },
  { id: 'magic-fang', name: 'Magic Fang', level: 1, school: 'Transmutation', lists: ['druid'], summary: 'A natural weapon gains +1.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'One natural weapon of the subject gains a +1 enhancement bonus on attack and damage rolls.' },
  { id: 'shillelagh', name: 'Shillelagh', level: 1, school: 'Transmutation', lists: ['druid'], summary: 'Club or staff hits harder.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless, object)', desc: 'Your club or quarterstaff gains +1 to attack and damage and strikes as if two sizes larger.' },
  { id: 'speak-with-animals', name: 'Speak with Animals', level: 1, school: 'Divination', lists: ['druid'], summary: 'Converse with animals.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'You can ask questions of and receive answers from animals.' },
  { id: 'charm-animal', name: 'Charm Animal', level: 1, school: 'Enchantment', lists: ['druid'], summary: 'Make an animal a friend.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '1 hour/level', save: 'Will negates', desc: 'An animal regards you as a trusted friend and ally.' },
  { id: 'pass-without-trace', name: 'Pass Without Trace', level: 1, school: 'Transmutation', lists: ['druid'], summary: 'Leave no trail.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 hour/level', save: 'Will negates (harmless)', desc: 'The subject leaves no tracks or scent and cannot be tracked by nonmagical means.' },

  // ---- Level 2 ----
  { id: 'false-life', name: 'False Life', level: 2, school: 'Necromancy', lists: ['arcane'], summary: 'Gain temporary hit points.', cast: '1 standard action', comp: 'V, S, M', range: 'Personal', dur: '1 hour/level or until discharged', save: 'None', desc: 'You gain 1d10 +1 per caster level (max +10) temporary hit points.' },
  { id: 'knock', name: 'Knock', level: 2, school: 'Transmutation', lists: ['arcane'], summary: 'Open locked doors.', cast: '1 standard action', comp: 'V', range: 'Medium', dur: 'Instantaneous', save: 'None', desc: 'You open a stuck, barred, locked, or magically held door, chest, or shackle.' },
  { id: 'detect-thoughts', name: 'Detect Thoughts', level: 2, school: 'Divination', lists: ['arcane', 'bard'], summary: 'Read surface thoughts.', cast: '1 standard action', comp: 'V, S, F/DF', range: '60 ft cone', dur: 'Concentration, up to 1 min/level', save: 'Will negates', desc: 'You detect the surface thoughts of creatures over several rounds of concentration.' },
  { id: 'touch-of-idiocy', name: 'Touch of Idiocy', level: 2, school: 'Enchantment', lists: ['arcane'], summary: 'Sap mental ability.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: '10 min/level', save: 'None', desc: 'A melee touch imposes a 1d6 penalty to Intelligence, Wisdom, and Charisma.' },
  { id: 'spectral-hand', name: 'Spectral Hand', level: 2, school: 'Necromancy', lists: ['arcane'], summary: 'A ghostly hand delivers touch spells.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'A ghostly hand delivers your touch spells at range while you stay back.' },
  { id: 'darkness', name: 'Darkness', level: 2, school: 'Evocation', lists: ['arcane', 'divine', 'bard'], summary: 'Lower light in an area.', cast: '1 standard action', comp: 'V, M/DF', range: 'Touch', dur: '1 min/level', save: 'None', desc: 'An object radiates darkness, lowering the light level and countering light spells.' },
  { id: 'alter-self', name: 'Alter Self', level: 2, school: 'Transmutation', lists: ['arcane'], summary: 'Take another humanoid form.', cast: '1 standard action', comp: 'V, S', range: 'Personal', dur: '1 min/level', save: 'None', desc: 'You assume the form of a Small or Medium humanoid, gaining some of its physical qualities.' },
  { id: 'rope-trick', name: 'Rope Trick', level: 2, school: 'Transmutation', lists: ['arcane'], summary: 'Hide in an extradimensional space.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 hour/level', save: 'None', desc: 'A rope rises into an extradimensional space that can hold up to eight creatures.' },
  { id: 'pyrotechnics', name: 'Pyrotechnics', level: 2, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Turn a fire into fireworks or smoke.', cast: '1 standard action', comp: 'V, S, M', range: 'Long', dur: 'See text', save: 'Will/Fort negates', desc: 'You transform a fire source into either blinding fireworks or a thick cloud of choking smoke.' },
  { id: 'protection-from-arrows', name: 'Protection from Arrows', level: 2, school: 'Abjuration', lists: ['arcane'], summary: 'DR 10/magic vs ranged.', cast: '1 standard action', comp: 'V, S, F', range: 'Touch', dur: '1 hour/level or until discharged', save: 'Will negates (harmless)', desc: 'The subject gains DR 10/magic against ranged weapons, absorbing 10 points per caster level.' },
  { id: 'summon-monster-ii', name: 'Summon Monster II', level: 2, school: 'Conjuration', lists: ['arcane', 'divine', 'bard'], summary: 'Summon a stronger creature.', cast: '1 round', comp: 'V, S, F/DF', range: 'Close', dur: '1 round/level', save: 'None', desc: 'As summon monster I, but drawing on the 2nd-level summoning list.' },
  { id: 'spider-climb', name: 'Spider Climb', level: 2, school: 'Transmutation', lists: ['arcane', 'druid'], summary: 'Climb walls and ceilings.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'The subject can climb any surface, including ceilings, with a climb speed of 20 feet.' },
  { id: 'cats-grace', name: "Cat's Grace", level: 2, school: 'Transmutation', lists: ['arcane', 'druid', 'bard'], summary: '+4 enhancement to Dexterity.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains a +4 enhancement bonus to Dexterity.' },
  { id: 'foxs-cunning', name: "Fox's Cunning", level: 2, school: 'Transmutation', lists: ['arcane', 'bard'], summary: '+4 enhancement to Intelligence.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains a +4 enhancement bonus to Intelligence.' },
  { id: 'eagles-splendor', name: "Eagle's Splendor", level: 2, school: 'Transmutation', lists: ['arcane', 'divine', 'bard'], summary: '+4 enhancement to Charisma.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains a +4 enhancement bonus to Charisma.' },
  { id: 'bears-endurance', name: "Bear's Endurance", level: 2, school: 'Transmutation', lists: ['arcane', 'divine', 'druid'], summary: '+4 enhancement to Constitution.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains a +4 enhancement bonus to Constitution, and thus temporary hit points.' },
  { id: 'owls-wisdom', name: "Owl's Wisdom", level: 2, school: 'Transmutation', lists: ['arcane', 'divine', 'druid'], summary: '+4 enhancement to Wisdom.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains a +4 enhancement bonus to Wisdom.' },
  { id: 'sound-burst', name: 'Sound Burst', level: 2, school: 'Evocation', lists: ['divine', 'bard'], summary: '1d8 sonic + stun in a burst.', cast: '1 standard action', comp: 'V, S, F/DF', range: 'Close', dur: 'Instantaneous', save: 'Fortitude partial', desc: 'A burst of sound deals 1d8 sonic damage to all in the area and may stun them.' },
  { id: 'align-weapon', name: 'Align Weapon', level: 2, school: 'Transmutation', lists: ['divine'], summary: 'Weapon becomes good/evil/etc.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'A weapon gains an alignment (good, evil, lawful, or chaotic), bypassing matching damage reduction.' },
  { id: 'consecrate', name: 'Consecrate', level: 2, school: 'Evocation', lists: ['divine'], summary: 'Bless an area against undead.', cast: '1 standard action', comp: 'V, S, M, DF', range: 'Close', dur: '2 hours/level', save: 'None', desc: 'You bless an area, weakening undead and boosting channeled positive energy within it.' },
  { id: 'death-knell', name: 'Death Knell', level: 2, school: 'Necromancy', lists: ['divine'], summary: 'Slay the dying for power.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous/10 min/level', save: 'Will negates', desc: 'You kill a dying creature and gain temporary hit points, +2 Strength, and +1 caster level.' },
  { id: 'delay-poison', name: 'Delay Poison', level: 2, school: 'Conjuration', lists: ['divine', 'druid', 'bard'], summary: 'Suspend poison’s effects.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 hour/level', save: 'Fortitude negates (harmless)', desc: 'The subject is immune to poison for the duration, though existing poison resumes after it ends.' },
  { id: 'zone-of-truth', name: 'Zone of Truth', level: 2, school: 'Enchantment', lists: ['divine'], summary: 'Creatures can’t lie.', cast: '1 standard action', comp: 'V, S, DF', range: 'Close', dur: '1 min/level', save: 'Will negates', desc: 'Creatures in the area cannot speak deliberate lies while within it.' },
  { id: 'calm-emotions', name: 'Calm Emotions', level: 2, school: 'Enchantment', lists: ['divine', 'bard'], summary: 'Suppress strong emotions.', cast: '1 standard action', comp: 'V, S, DF', range: 'Medium', dur: 'Concentration, up to 1 round/level', save: 'Will negates', desc: 'You calm agitated creatures, suppressing rage, fear, and other emotion effects and stopping violence.' },
  { id: 'status', name: 'Status', level: 2, school: 'Divination', lists: ['divine'], summary: 'Monitor allies’ condition.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: '1 hour/level', save: 'Will negates (harmless)', desc: 'You keep track of the position and condition of allies you touch when cast.' },
  { id: 'shatter', name: 'Shatter', level: 2, school: 'Evocation', lists: ['arcane', 'divine', 'bard'], summary: 'Shatter objects or crystal.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Close', dur: 'Instantaneous', save: 'Will/Fort negates', desc: 'A shrill noise shatters nonmagical objects or damages crystalline creatures.' },
  { id: 'inflict-moderate-wounds', name: 'Inflict Moderate Wounds', level: 2, school: 'Necromancy', lists: ['divine'], summary: '2d8 + level negative energy.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half', desc: 'Negative energy deals 2d8 +1 per caster level (max +10), or heals undead.' },
  { id: 'flame-blade', name: 'Flame Blade', level: 2, school: 'Evocation', lists: ['druid'], summary: 'A scimitar of fire.', cast: '1 standard action', comp: 'V, S, DF', range: '0 ft', dur: '1 min/level', save: 'None', desc: 'A blade of fire deals 1d8 + 1 per two caster levels (max +10) on a melee touch attack.' },
  { id: 'heat-metal', name: 'Heat Metal', level: 2, school: 'Transmutation', lists: ['druid'], summary: 'Make metal scorching hot.', cast: '1 standard action', comp: 'V, S, DF', range: 'Close', dur: '7 rounds', save: 'Will negates (harmless, object)', desc: 'Metal armor, weapons, or objects grow hot, damaging those touching them over several rounds.' },
  { id: 'fog-cloud', name: 'Fog Cloud', level: 2, school: 'Conjuration', lists: ['arcane', 'druid'], summary: 'A concealing bank of fog.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '10 min/level', save: 'None', desc: 'A bank of fog obscures all sight, including darkvision, beyond 5 feet.' },
  { id: 'gust-of-wind', name: 'Gust of Wind', level: 2, school: 'Evocation', lists: ['arcane', 'druid'], summary: 'A blast of severe wind.', cast: '1 standard action', comp: 'V, S', range: '60 ft line', dur: '1 round', save: 'Fortitude negates', desc: 'A severe blast of wind knocks over small creatures, disperses gases, and scatters light objects.' },
  { id: 'summon-swarm', name: 'Summon Swarm', level: 2, school: 'Conjuration', lists: ['arcane', 'druid', 'bard'], summary: 'Summon a biting swarm.', cast: '1 round', comp: 'V, S, M/DF', range: 'Close', dur: 'Concentration + 2 rounds', save: 'None', desc: 'You summon a swarm of bats, rats, or spiders that attacks creatures in its space.' },
  { id: 'tree-shape', name: 'Tree Shape', level: 2, school: 'Transmutation', lists: ['druid'], summary: 'Take the form of a tree.', cast: '1 standard action', comp: 'V, S, DF', range: 'Personal', dur: '1 hour/level', save: 'None', desc: 'You assume the form of a Large living tree or shrub, gaining excellent camouflage.' },
  { id: 'warp-wood', name: 'Warp Wood', level: 2, school: 'Transmutation', lists: ['druid'], summary: 'Bend and ruin wooden objects.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: 'Instantaneous', save: 'Will negates (object)', desc: 'You cause wood to bend and warp, ruining shafts, hafts, handles, and doors.' },
  { id: 'hold-animal', name: 'Hold Animal', level: 2, school: 'Enchantment', lists: ['druid'], summary: 'Paralyze one animal.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '1 round/level', save: 'Will negates', desc: 'One animal is paralyzed, though it may attempt a new save each round.' },
  { id: 'animal-messenger', name: 'Animal Messenger', level: 2, school: 'Enchantment', lists: ['druid', 'bard'], summary: 'Send a tiny animal with a message.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 day/level', save: 'None', desc: 'You compel a Tiny animal to travel to a destination you designate, carrying a small message.' },

  // ---- Level 3 ----
  { id: 'heroism', name: 'Heroism', level: 3, school: 'Enchantment', lists: ['arcane'], summary: '+2 morale on attacks, saves, skills.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'The subject gains a +2 morale bonus on attack rolls, saves, and skill checks.' },
  { id: 'good-hope', name: 'Good Hope', level: 3, school: 'Enchantment', lists: ['bard'], summary: '+2 morale to allies on many rolls.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'Subjects gain +2 morale on saves, attack rolls, ability checks, skill checks, and weapon damage.' },
  { id: 'slow', name: 'Slow', level: 3, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Halve foes’ actions and speed.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 round/level', save: 'Will negates', desc: 'Affected creatures take one action per round, move at half speed, and take −1 to AC, attacks, and Reflex. Counters haste.' },
  { id: 'gaseous-form', name: 'Gaseous Form', level: 3, school: 'Transmutation', lists: ['arcane', 'bard'], summary: 'Become an insubstantial cloud.', cast: '1 standard action', comp: 'S, M', range: 'Touch', dur: '2 min/level', save: 'None', desc: 'The subject becomes a misty cloud with DR 10/magic and a fly speed, but cannot attack or cast.' },
  { id: 'water-breathing', name: 'Water Breathing', level: 3, school: 'Transmutation', lists: ['arcane', 'divine', 'druid'], summary: 'Breathe underwater.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '2 hours/level (divided)', save: 'Will negates (harmless)', desc: 'The subjects can breathe water freely, the duration divided among all creatures touched.' },
  { id: 'tongues', name: 'Tongues', level: 3, school: 'Divination', lists: ['arcane'], summary: 'Speak and understand any language.', cast: '1 standard action', comp: 'V, M', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'The subject can speak and understand any spoken language.' },
  { id: 'suggestion', name: 'Suggestion', level: 3, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'Compel a reasonable course of action.', cast: '1 standard action', comp: 'V, M', range: 'Close', dur: '1 hour/level', save: 'Will negates', desc: 'You influence a creature to follow a suggested course of action that sounds reasonable.' },
  { id: 'magic-circle-against-evil', name: 'Magic Circle against Evil', level: 3, school: 'Abjuration', lists: ['arcane', 'divine'], summary: 'Protection from evil, in an area.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'As protection from evil, but in a 10-ft radius and also blocking summoned creatures.' },
  { id: 'keen-edge', name: 'Keen Edge', level: 3, school: 'Transmutation', lists: ['arcane'], summary: 'Double a weapon’s threat range.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '10 min/level', save: 'Will negates (harmless, object)', desc: 'A slashing or piercing weapon’s threat range doubles (does not stack with keen or Improved Critical).' },
  { id: 'daylight', name: 'Daylight', level: 3, school: 'Evocation', lists: ['arcane', 'divine', 'druid', 'bard'], summary: 'Bright light in a radius.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: '10 min/level', save: 'None', desc: 'An object sheds bright light in a 60-ft radius, countering and dispelling lower-level darkness effects.' },
  { id: 'inflict-serious-wounds', name: 'Inflict Serious Wounds', level: 3, school: 'Necromancy', lists: ['divine'], summary: '3d8 + level negative energy.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half', desc: 'Negative energy deals 3d8 +1 per caster level (max +15), or heals undead.' },
  { id: 'remove-disease', name: 'Remove Disease', level: 3, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'Cure diseases.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Fortitude negates (harmless)', desc: 'You cure all diseases afflicting the subject.' },
  { id: 'remove-curse', name: 'Remove Curse', level: 3, school: 'Abjuration', lists: ['divine', 'bard'], summary: 'Lift a curse.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'See text', desc: 'You free a creature or object from a curse with a caster level check.' },
  { id: 'magic-vestment', name: 'Magic Vestment', level: 3, school: 'Transmutation', lists: ['divine'], summary: 'Armor or shield gains +1/four levels.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 hour/level', save: 'Will negates (harmless, object)', desc: 'Armor, shield, or clothing gains a +1 enhancement bonus per four caster levels (max +5).' },
  { id: 'animate-dead', name: 'Animate Dead', level: 3, school: 'Necromancy', lists: ['divine'], summary: 'Raise undead servants.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'You create skeletons and zombies from corpses to serve you, limited by your caster level.' },
  { id: 'create-food-and-water', name: 'Create Food and Water', level: 3, school: 'Conjuration', lists: ['divine'], summary: 'Feed several people.', cast: '10 minutes', comp: 'V, S', range: 'Close', dur: '24 hours', save: 'None', desc: 'You create food and water to sustain three humans (or one horse) per caster level for a day.' },
  { id: 'summon-monster-iii', name: 'Summon Monster III', level: 3, school: 'Conjuration', lists: ['arcane', 'divine', 'bard'], summary: 'Summon a yet stronger creature.', cast: '1 round', comp: 'V, S, F/DF', range: 'Close', dur: '1 round/level', save: 'None', desc: 'As summon monster I, but drawing on the 3rd-level summoning list.' },
  { id: 'sleet-storm', name: 'Sleet Storm', level: 3, school: 'Conjuration', lists: ['arcane', 'druid'], summary: 'Blinding, slippery sleet.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Long', dur: '1 round/level', save: 'None', desc: 'Driving sleet blocks sight, snuffs torches, and makes the ground slippery.' },
  { id: 'spike-growth', name: 'Spike Growth', level: 3, school: 'Transmutation', lists: ['druid'], summary: 'Ground spikes injure and slow.', cast: '1 standard action', comp: 'V, S, DF', range: 'Medium', dur: '1 hour/level', save: 'Reflex partial', desc: 'Every surface in the area sprouts spikes that damage and slow creatures moving through it.' },
  { id: 'dominate-animal', name: 'Dominate Animal', level: 3, school: 'Enchantment', lists: ['druid'], summary: 'Control an animal.', cast: '1 round', comp: 'V, S', range: 'Close', dur: '1 round/level', save: 'Will negates', desc: 'You control the actions of an animal through a telepathic link.' },
  { id: 'wind-wall', name: 'Wind Wall', level: 3, school: 'Evocation', lists: ['arcane', 'divine', 'druid'], summary: 'A wall of wind deflects arrows.', cast: '1 standard action', comp: 'V, S, M/DF', range: 'Medium', dur: '1 round/level', save: 'None', desc: 'A wall of strong wind deflects arrows and light creatures and disperses gases.' },

  // ---- Level 4 ----
  { id: 'shout', name: 'Shout', level: 4, school: 'Evocation', lists: ['arcane', 'bard'], summary: '5d6 sonic cone + deafen.', cast: '1 standard action', comp: 'V', range: '30 ft cone', dur: 'Instantaneous', save: 'Fortitude partial', desc: 'A devastating yell deals 5d6 sonic damage and deafens creatures in the cone.' },
  { id: 'charm-monster', name: 'Charm Monster', level: 4, school: 'Enchantment', lists: ['arcane'], summary: 'Make any creature a friend.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '1 day/level', save: 'Will negates', desc: 'As charm person, but affecting any living creature.' },
  { id: 'phantasmal-killer', name: 'Phantasmal Killer', level: 4, school: 'Illusion', lists: ['arcane'], summary: 'A deadly personal nightmare.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: 'Instantaneous', save: 'Will/Fort', desc: 'You craft a fearsome image only the target can see; belief in it can stop the victim’s heart.' },
  { id: 'solid-fog', name: 'Solid Fog', level: 4, school: 'Conjuration', lists: ['arcane'], summary: 'Fog that also impedes movement.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: '1 min/level', save: 'None', desc: 'As fog cloud, but the vapor is so thick it slows movement and weakens attacks within it.' },
  { id: 'resilient-sphere', name: 'Resilient Sphere', level: 4, school: 'Evocation', lists: ['arcane'], summary: 'Trap a creature in a force globe.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: '1 min/level', save: 'Reflex negates', desc: 'A globe of force surrounds the subject, trapping it and blocking anything from passing through.' },
  { id: 'summon-monster-iv', name: 'Summon Monster IV', level: 4, school: 'Conjuration', lists: ['arcane', 'divine', 'bard'], summary: 'Summon a 4th-level creature.', cast: '1 round', comp: 'V, S, F/DF', range: 'Close', dur: '1 round/level', save: 'None', desc: 'As summon monster I, but drawing on the 4th-level summoning list.' },
  { id: 'inflict-critical-wounds', name: 'Inflict Critical Wounds', level: 4, school: 'Necromancy', lists: ['divine'], summary: '4d8 + level negative energy.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: 'Instantaneous', save: 'Will half', desc: 'Negative energy deals 4d8 +1 per caster level (max +20), or heals undead.' },
  { id: 'divination', name: 'Divination', level: 4, school: 'Divination', lists: ['divine'], summary: 'Advice about a course of action.', cast: '10 minutes', comp: 'V, S, M', range: 'Personal', dur: 'Instantaneous', save: 'None', desc: 'You receive a useful piece of advice about a specific goal, event, or activity in the near future.' },
  { id: 'dismissal', name: 'Dismissal', level: 4, school: 'Abjuration', lists: ['divine'], summary: 'Send one outsider home.', cast: '1 standard action', comp: 'V, S, DF', range: 'Close', dur: 'Instantaneous', save: 'Will negates', desc: 'You force a single extraplanar creature back to its home plane.' },
  { id: 'sending', name: 'Sending', level: 4, school: 'Evocation', lists: ['divine'], summary: 'Send a short message anywhere.', cast: '10 minutes', comp: 'V, S, M', range: 'See text', dur: '1 round; see text', save: 'None', desc: 'You contact a specific creature with a short message and receive a brief reply, across any distance or plane.' },
  { id: 'spell-immunity', name: 'Spell Immunity', level: 4, school: 'Abjuration', lists: ['divine'], summary: 'Immunity to chosen spells.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'The subject is immune to the effects of one spell per four caster levels that it chooses.' },
  { id: 'rusting-grasp', name: 'Rusting Grasp', level: 4, school: 'Transmutation', lists: ['druid'], summary: 'Corrode metal by touch.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: 'Instantaneous', save: 'None', desc: 'Your touch corrodes and destroys metal objects or deals heavy damage to metal creatures.' },
  { id: 'command-plants', name: 'Command Plants', level: 4, school: 'Transmutation', lists: ['druid'], summary: 'Control plant creatures.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '1 day/level', save: 'Will negates', desc: 'You can suppress the hostility of and command plant creatures within range.' },
  { id: 'giant-vermin', name: 'Giant Vermin', level: 4, school: 'Transmutation', lists: ['divine', 'druid'], summary: 'Enlarge insects into monsters.', cast: '1 standard action', comp: 'V, S, DF', range: 'Close', dur: '1 min/level', save: 'None', desc: 'You turn ordinary centipedes, scorpions, or spiders into giant vermin that fight for you.' },
  { id: 'summon-natures-ally-iv', name: "Summon Nature's Ally IV", level: 4, school: 'Conjuration', lists: ['druid'], summary: 'Summon a natural creature.', cast: '1 round', comp: 'V, S, DF', range: 'Close', dur: '1 round/level', save: 'None', desc: 'You summon a natural creature from the 4th-level list to fight for you.' },

  // ---- Level 5 ----
  { id: 'feeblemind', name: 'Feeblemind', level: 5, school: 'Enchantment', lists: ['arcane'], summary: 'Shatter a mind.', cast: '1 standard action', comp: 'V, S, M', range: 'Medium', dur: 'Instantaneous', save: 'Will negates', desc: 'The target’s Intelligence and Charisma drop to 1; casters save at a steep penalty.' },
  { id: 'passwall', name: 'Passwall', level: 5, school: 'Transmutation', lists: ['arcane'], summary: 'Open a passage through a wall.', cast: '1 standard action', comp: 'V, S, M', range: 'Touch', dur: '1 hour/level', save: 'None', desc: 'You create a passage through a wooden, plaster, or stone wall, but not metal or worked stone.' },
  { id: 'telekinesis', name: 'Telekinesis', level: 5, school: 'Transmutation', lists: ['arcane'], summary: 'Move objects or creatures at range.', cast: '1 standard action', comp: 'V, S', range: 'Long', dur: 'Concentration or instantaneous', save: 'See text', desc: 'You move objects or creatures by concentration, or hurl them in a violent thrust.' },
  { id: 'mind-fog', name: 'Mind Fog', level: 5, school: 'Enchantment', lists: ['arcane', 'bard'], summary: 'Fog weakens Will saves.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '30 minutes; see text', save: 'Will negates', desc: 'A cloud of fog leaves those inside with a −10 penalty on Wisdom checks and Will saves.' },
  { id: 'persistent-image', name: 'Persistent Image', level: 5, school: 'Illusion', lists: ['arcane', 'bard'], summary: 'A complex, lasting illusion.', cast: '1 standard action', comp: 'V, S, F', range: 'Long', dur: '1 min/level', save: 'Will disbelief', desc: 'As silent image, but with sound, smell, and thermal effects, and it persists without concentration.' },
  { id: 'summon-monster-v', name: 'Summon Monster V', level: 5, school: 'Conjuration', lists: ['arcane', 'divine', 'bard'], summary: 'Summon a 5th-level creature.', cast: '1 round', comp: 'V, S, F/DF', range: 'Close', dur: '1 round/level', save: 'None', desc: 'As summon monster I, but drawing on the 5th-level summoning list.' },
  { id: 'slay-living', name: 'Slay Living', level: 5, school: 'Necromancy', lists: ['divine'], summary: 'Touch of death.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: 'Instantaneous', save: 'Fortitude partial', desc: 'Your touch may slay a living creature outright, or deal 12d6 + caster level on a successful save.' },
  { id: 'greater-command', name: 'Greater Command', level: 5, school: 'Enchantment', lists: ['divine'], summary: 'Command several creatures.', cast: '1 standard action', comp: 'V, S, DF', range: 'Close', dur: '1 round/level', save: 'Will negates', desc: 'As command, but affecting one creature per level and repeating each round.' },
  { id: 'spell-resistance', name: 'Spell Resistance', level: 5, school: 'Abjuration', lists: ['divine'], summary: 'Grant spell resistance.', cast: '1 standard action', comp: 'V, S, DF', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'The subject gains spell resistance equal to 12 + your caster level.' },
  { id: 'commune', name: 'Commune', level: 5, school: 'Divination', lists: ['divine'], summary: 'Ask your deity yes/no questions.', cast: '10 minutes', comp: 'V, S, M, DF', range: 'Personal', dur: '1 round/level', save: 'None', desc: 'You contact your deity and receive correct yes-or-no answers to one question per caster level.' },
  { id: 'plane-shift', name: 'Plane Shift', level: 5, school: 'Conjuration', lists: ['divine'], summary: 'Travel to another plane.', cast: '1 standard action', comp: 'V, S, F', range: 'Touch', dur: 'Instantaneous', save: 'Will negates', desc: 'You move yourself or others to another plane of existence, arriving somewhat off target.' },
  { id: 'call-lightning-storm', name: 'Call Lightning Storm', level: 5, school: 'Evocation', lists: ['druid'], summary: 'Stronger call lightning, 3d10 bolts.', cast: '1 standard action', comp: 'V, S', range: 'Long', dur: '1 min/level', save: 'Reflex half', desc: 'As call lightning, but each bolt deals 3d10 and the range is greater.' },
  { id: 'wall-of-thorns', name: 'Wall of Thorns', level: 5, school: 'Conjuration', lists: ['druid'], summary: 'A barrier of slashing thorns.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '10 min/level', save: 'None', desc: 'A thick, thorny barrier damages creatures trying to move through it.' },
  { id: 'insect-plague', name: 'Insect Plague', level: 5, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'Summon locust swarms.', cast: '1 round', comp: 'V, S, DF', range: 'Long', dur: '1 min/level', save: 'None', desc: 'Swarms of biting locusts attack creatures in the area and disrupt spellcasting.' },
  { id: 'tree-stride', name: 'Tree Stride', level: 5, school: 'Conjuration', lists: ['druid'], summary: 'Step between trees.', cast: '1 standard action', comp: 'V, S, DF', range: 'Personal', dur: '1 hour/level or until spent', save: 'None', desc: 'You step into one tree and emerge from another of the same kind, some distance away.' },
  { id: 'commune-with-nature', name: 'Commune with Nature', level: 5, school: 'Divination', lists: ['druid'], summary: 'Learn the surrounding land.', cast: '10 minutes', comp: 'V, S', range: 'Personal', dur: 'Instantaneous', save: 'None', desc: 'You learn about the terrain, creatures, water, and features of the natural area around you.' },
  { id: 'animal-growth', name: 'Animal Growth', level: 5, school: 'Transmutation', lists: ['arcane', 'druid'], summary: 'Double an animal’s size.', cast: '1 standard action', comp: 'V, S', range: 'Medium', dur: '1 min/level', save: 'Fortitude negates', desc: 'One animal per two levels grows to twice its size, gaining Strength, Constitution, and natural armor.' },

  // ---- Level 6 ----
  { id: 'greater-heroism', name: 'Greater Heroism', level: 6, school: 'Enchantment', lists: ['arcane'], summary: '+4 morale, fearless, temp HP.', cast: '1 standard action', comp: 'V, S', range: 'Touch', dur: '1 min/level', save: 'Will negates (harmless)', desc: 'As heroism, but +4 morale, immunity to fear, and 8 temporary hit points.' },
  { id: 'antimagic-field', name: 'Antimagic Field', level: 6, school: 'Abjuration', lists: ['arcane', 'divine'], summary: 'Suppress magic around you.', cast: '1 standard action', comp: 'V, S, M/DF', range: '10 ft', dur: '10 min/level', save: 'None', desc: 'An invisible barrier suppresses most magical effects, items, and creatures within 10 feet of you.' },
  { id: 'circle-of-death', name: 'Circle of Death', level: 6, school: 'Necromancy', lists: ['arcane'], summary: 'Slay weak creatures in a burst.', cast: '1 standard action', comp: 'V, S, M', range: 'Close', dur: 'Instantaneous', save: 'Fortitude negates', desc: 'Negative energy slays up to 1d4 HD of creatures per caster level, affecting the weakest first.' },
  { id: 'eyebite', name: 'Eyebite', level: 6, school: 'Necromancy', lists: ['arcane', 'bard'], summary: 'Gaze sickens, panics, or drops foes.', cast: '1 standard action', comp: 'V, S', range: 'Close', dur: '1 round/level', save: 'Fortitude negates', desc: 'Each round your gaze afflicts a creature with sickness, panic, or comatose sleep by its Hit Dice.' },
  { id: 'mislead', name: 'Mislead', level: 6, school: 'Illusion', lists: ['arcane', 'bard'], summary: 'Turn invisible and send a double.', cast: '1 standard action', comp: 'S, F', range: 'Close', dur: 'See text', save: 'None', desc: 'You become invisible while an illusory double of you appears and can be scripted to act.' },
  { id: 'word-of-recall', name: 'Word of Recall', level: 6, school: 'Conjuration', lists: ['divine', 'druid'], summary: 'Teleport to a sanctuary.', cast: '1 standard action', comp: 'V', range: 'Unlimited', dur: 'Instantaneous', save: 'None', desc: 'You are instantly transported back to a designated sanctuary, with willing companions.' },
  { id: 'find-the-path', name: 'Find the Path', level: 6, school: 'Divination', lists: ['divine', 'druid', 'bard'], summary: 'Know the way to a place.', cast: '3 rounds', comp: 'V, S, F', range: 'Personal or touch', dur: '10 min/level', save: 'Will negates (harmless)', desc: 'You know the shortest, most direct route to a specified destination.' },
];

// Structured effects live beside the prose rather than inline, so this table stays readable and the
// verified scaling clauses sit together in one file. Attached here so every consumer sees them.
for (const s of SPELLS) {
  const buff = SPELL_BUFFS[s.id];
  if (buff) s.buff = buff;
  const damage = SPELL_DAMAGE[s.id];
  if (damage) s.damage = damage;
  const attacker = SPELL_ATTACKERS[s.id];
  if (attacker) s.attacker = attacker;
}

export const spellById = new Map(SPELLS.map((s) => [s.id, s]));
